// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/annotations.proto

package keelithv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceDependencyBinding int32

const (
	ServiceDependencyBinding_SERVICE_DEPENDENCY_BINDING_UNSPECIFIED ServiceDependencyBinding = 0
	ServiceDependencyBinding_SERVICE_DEPENDENCY_BINDING_REMOTE      ServiceDependencyBinding = 1
	ServiceDependencyBinding_SERVICE_DEPENDENCY_BINDING_AUTO        ServiceDependencyBinding = 2
	ServiceDependencyBinding_SERVICE_DEPENDENCY_BINDING_LOCAL       ServiceDependencyBinding = 3
)

// Enum value maps for ServiceDependencyBinding.
var (
	ServiceDependencyBinding_name = map[int32]string{
		0: "SERVICE_DEPENDENCY_BINDING_UNSPECIFIED",
		1: "SERVICE_DEPENDENCY_BINDING_REMOTE",
		2: "SERVICE_DEPENDENCY_BINDING_AUTO",
		3: "SERVICE_DEPENDENCY_BINDING_LOCAL",
	}
	ServiceDependencyBinding_value = map[string]int32{
		"SERVICE_DEPENDENCY_BINDING_UNSPECIFIED": 0,
		"SERVICE_DEPENDENCY_BINDING_REMOTE":      1,
		"SERVICE_DEPENDENCY_BINDING_AUTO":        2,
		"SERVICE_DEPENDENCY_BINDING_LOCAL":       3,
	}
)

func (x ServiceDependencyBinding) Enum() *ServiceDependencyBinding {
	p := new(ServiceDependencyBinding)
	*p = x
	return p
}

func (x ServiceDependencyBinding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceDependencyBinding) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_annotations_proto_enumTypes[0].Descriptor()
}

func (ServiceDependencyBinding) Type() protoreflect.EnumType {
	return &file_v1_annotations_proto_enumTypes[0]
}

func (x ServiceDependencyBinding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceDependencyBinding.Descriptor instead.
func (ServiceDependencyBinding) EnumDescriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{0}
}

type ProjectionDropPolicy int32

const (
	ProjectionDropPolicy_PROJECTION_DROP_POLICY_UNSPECIFIED ProjectionDropPolicy = 0
	ProjectionDropPolicy_PROJECTION_DROP_POLICY_ALLOW       ProjectionDropPolicy = 1
)

// Enum value maps for ProjectionDropPolicy.
var (
	ProjectionDropPolicy_name = map[int32]string{
		0: "PROJECTION_DROP_POLICY_UNSPECIFIED",
		1: "PROJECTION_DROP_POLICY_ALLOW",
	}
	ProjectionDropPolicy_value = map[string]int32{
		"PROJECTION_DROP_POLICY_UNSPECIFIED": 0,
		"PROJECTION_DROP_POLICY_ALLOW":       1,
	}
)

func (x ProjectionDropPolicy) Enum() *ProjectionDropPolicy {
	p := new(ProjectionDropPolicy)
	*p = x
	return p
}

func (x ProjectionDropPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectionDropPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_annotations_proto_enumTypes[1].Descriptor()
}

func (ProjectionDropPolicy) Type() protoreflect.EnumType {
	return &file_v1_annotations_proto_enumTypes[1]
}

func (x ProjectionDropPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectionDropPolicy.Descriptor instead.
func (ProjectionDropPolicy) EnumDescriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{1}
}

type ServiceDependency struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       string                   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Transport     string                   `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	Reason        string                   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Binding       ServiceDependencyBinding `protobuf:"varint,4,opt,name=binding,proto3,enum=keelith.v1.ServiceDependencyBinding" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDependency) Reset() {
	*x = ServiceDependency{}
	mi := &file_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDependency) ProtoMessage() {}

func (x *ServiceDependency) ProtoReflect() protoreflect.Message {
	mi := &file_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDependency.ProtoReflect.Descriptor instead.
func (*ServiceDependency) Descriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceDependency) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceDependency) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ServiceDependency) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ServiceDependency) GetBinding() ServiceDependencyBinding {
	if x != nil {
		return x.Binding
	}
	return ServiceDependencyBinding_SERVICE_DEPENDENCY_BINDING_UNSPECIFIED
}

// IdempotencyRule explicitly enables fenced request deduplication and bounded
// result replay for one unary command.
type IdempotencyRule struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Namespace            string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MetadataKey          string                 `protobuf:"bytes,2,opt,name=metadata_key,json=metadataKey,proto3" json:"metadata_key,omitempty"`
	ProcessingTtlSeconds int64                  `protobuf:"varint,3,opt,name=processing_ttl_seconds,json=processingTtlSeconds,proto3" json:"processing_ttl_seconds,omitempty"`
	ResultTtlSeconds     int64                  `protobuf:"varint,4,opt,name=result_ttl_seconds,json=resultTtlSeconds,proto3" json:"result_ttl_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IdempotencyRule) Reset() {
	*x = IdempotencyRule{}
	mi := &file_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyRule) ProtoMessage() {}

func (x *IdempotencyRule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyRule.ProtoReflect.Descriptor instead.
func (*IdempotencyRule) Descriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *IdempotencyRule) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IdempotencyRule) GetMetadataKey() string {
	if x != nil {
		return x.MetadataKey
	}
	return ""
}

func (x *IdempotencyRule) GetProcessingTtlSeconds() int64 {
	if x != nil {
		return x.ProcessingTtlSeconds
	}
	return 0
}

func (x *IdempotencyRule) GetResultTtlSeconds() int64 {
	if x != nil {
		return x.ResultTtlSeconds
	}
	return 0
}

// ContinuationRule enables one unary method as a durable continuable call.
type ContinuationRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MachineVersion   string                 `protobuf:"bytes,1,opt,name=machine_version,json=machineVersion,proto3" json:"machine_version,omitempty"`
	InlineBudgetMs   int64                  `protobuf:"varint,2,opt,name=inline_budget_ms,json=inlineBudgetMs,proto3" json:"inline_budget_ms,omitempty"`
	RetentionSeconds int64                  `protobuf:"varint,3,opt,name=retention_seconds,json=retentionSeconds,proto3" json:"retention_seconds,omitempty"`
	MaxPayloadBytes  int64                  `protobuf:"varint,4,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContinuationRule) Reset() {
	*x = ContinuationRule{}
	mi := &file_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinuationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinuationRule) ProtoMessage() {}

func (x *ContinuationRule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinuationRule.ProtoReflect.Descriptor instead.
func (*ContinuationRule) Descriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *ContinuationRule) GetMachineVersion() string {
	if x != nil {
		return x.MachineVersion
	}
	return ""
}

func (x *ContinuationRule) GetInlineBudgetMs() int64 {
	if x != nil {
		return x.InlineBudgetMs
	}
	return 0
}

func (x *ContinuationRule) GetRetentionSeconds() int64 {
	if x != nil {
		return x.RetentionSeconds
	}
	return 0
}

func (x *ContinuationRule) GetMaxPayloadBytes() int64 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

// ProjectionRule declares one top-level message as a replicated projection.
type ProjectionRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	KeyFields     []string               `protobuf:"bytes,2,rep,name=key_fields,json=keyFields,proto3" json:"key_fields,omitempty"`
	SchemaMajor   uint32                 `protobuf:"varint,3,opt,name=schema_major,json=schemaMajor,proto3" json:"schema_major,omitempty"`
	Migrations    []*ProjectionMigration `protobuf:"bytes,4,rep,name=migrations,proto3" json:"migrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectionRule) Reset() {
	*x = ProjectionRule{}
	mi := &file_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionRule) ProtoMessage() {}

func (x *ProjectionRule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionRule.ProtoReflect.Descriptor instead.
func (*ProjectionRule) Descriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectionRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectionRule) GetKeyFields() []string {
	if x != nil {
		return x.KeyFields
	}
	return nil
}

func (x *ProjectionRule) GetSchemaMajor() uint32 {
	if x != nil {
		return x.SchemaMajor
	}
	return 0
}

func (x *ProjectionRule) GetMigrations() []*ProjectionMigration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

// ProjectionFieldMigration explicitly maps, defaults, or drops one field.
type ProjectionFieldMigration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreviousField string                 `protobuf:"bytes,1,opt,name=previous_field,json=previousField,proto3" json:"previous_field,omitempty"`
	CurrentField  string                 `protobuf:"bytes,2,opt,name=current_field,json=currentField,proto3" json:"current_field,omitempty"`
	DefaultValue  *string                `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	DropPolicy    ProjectionDropPolicy   `protobuf:"varint,4,opt,name=drop_policy,json=dropPolicy,proto3,enum=keelith.v1.ProjectionDropPolicy" json:"drop_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectionFieldMigration) Reset() {
	*x = ProjectionFieldMigration{}
	mi := &file_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionFieldMigration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionFieldMigration) ProtoMessage() {}

func (x *ProjectionFieldMigration) ProtoReflect() protoreflect.Message {
	mi := &file_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionFieldMigration.ProtoReflect.Descriptor instead.
func (*ProjectionFieldMigration) Descriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectionFieldMigration) GetPreviousField() string {
	if x != nil {
		return x.PreviousField
	}
	return ""
}

func (x *ProjectionFieldMigration) GetCurrentField() string {
	if x != nil {
		return x.CurrentField
	}
	return ""
}

func (x *ProjectionFieldMigration) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *ProjectionFieldMigration) GetDropPolicy() ProjectionDropPolicy {
	if x != nil {
		return x.DropPolicy
	}
	return ProjectionDropPolicy_PROJECTION_DROP_POLICY_UNSPECIFIED
}

// ProjectionMigration declares one historical concrete protobuf message that
// can be directly upcast to the current projection message.
type ProjectionMigration struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	PreviousFingerprint string                      `protobuf:"bytes,1,opt,name=previous_fingerprint,json=previousFingerprint,proto3" json:"previous_fingerprint,omitempty"`
	PreviousMessage     string                      `protobuf:"bytes,2,opt,name=previous_message,json=previousMessage,proto3" json:"previous_message,omitempty"`
	PreviousSchemaMajor uint32                      `protobuf:"varint,3,opt,name=previous_schema_major,json=previousSchemaMajor,proto3" json:"previous_schema_major,omitempty"`
	Fields              []*ProjectionFieldMigration `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	PreviousKeyFields   []string                    `protobuf:"bytes,5,rep,name=previous_key_fields,json=previousKeyFields,proto3" json:"previous_key_fields,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProjectionMigration) Reset() {
	*x = ProjectionMigration{}
	mi := &file_v1_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionMigration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionMigration) ProtoMessage() {}

func (x *ProjectionMigration) ProtoReflect() protoreflect.Message {
	mi := &file_v1_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionMigration.ProtoReflect.Descriptor instead.
func (*ProjectionMigration) Descriptor() ([]byte, []int) {
	return file_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectionMigration) GetPreviousFingerprint() string {
	if x != nil {
		return x.PreviousFingerprint
	}
	return ""
}

func (x *ProjectionMigration) GetPreviousMessage() string {
	if x != nil {
		return x.PreviousMessage
	}
	return ""
}

func (x *ProjectionMigration) GetPreviousSchemaMajor() uint32 {
	if x != nil {
		return x.PreviousSchemaMajor
	}
	return 0
}

func (x *ProjectionMigration) GetFields() []*ProjectionFieldMigration {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ProjectionMigration) GetPreviousKeyFields() []string {
	if x != nil {
		return x.PreviousKeyFields
	}
	return nil
}

var file_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51002,
		Name:          "keelith.v1.error_reason",
		Tag:           "bytes,51002,opt,name=error_reason",
		Filename:      "v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]*ServiceDependency)(nil),
		Field:         51004,
		Name:          "keelith.v1.dependency",
		Tag:           "bytes,51004,rep,name=dependency",
		Filename:      "v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*IdempotencyRule)(nil),
		Field:         51006,
		Name:          "keelith.v1.idempotency",
		Tag:           "bytes,51006,opt,name=idempotency",
		Filename:      "v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ContinuationRule)(nil),
		Field:         51007,
		Name:          "keelith.v1.continuation",
		Tag:           "bytes,51007,opt,name=continuation",
		Filename:      "v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ProjectionRule)(nil),
		Field:         51008,
		Name:          "keelith.v1.projection",
		Tag:           "bytes,51008,opt,name=projection",
		Filename:      "v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         51005,
		Name:          "keelith.v1.error_code",
		Tag:           "varint,51005,opt,name=error_code",
		Filename:      "v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string error_reason = 51002;
	E_ErrorReason = &file_v1_annotations_proto_extTypes[0]
	// repeated keelith.v1.ServiceDependency dependency = 51004;
	E_Dependency = &file_v1_annotations_proto_extTypes[1]
	// optional keelith.v1.IdempotencyRule idempotency = 51006;
	E_Idempotency = &file_v1_annotations_proto_extTypes[2]
	// optional keelith.v1.ContinuationRule continuation = 51007;
	E_Continuation = &file_v1_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional keelith.v1.ProjectionRule projection = 51008;
	E_Projection = &file_v1_annotations_proto_extTypes[4]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// error_code maps one stable enum reason to an HTTP-compatible application
	// code. protoc-gen-go-keelith generates constructors only for annotated,
	// non-zero enum values.
	//
	// optional int32 error_code = 51005;
	E_ErrorCode = &file_v1_annotations_proto_extTypes[5]
)

var File_v1_annotations_proto protoreflect.FileDescriptor

const file_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x14v1/annotations.proto\x12\n" +
	"keelith.v1\x1a google/protobuf/descriptor.proto\"\xa3\x01\n" +
	"\x11ServiceDependency\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12>\n" +
	"\abinding\x18\x04 \x01(\x0e2$.keelith.v1.ServiceDependencyBindingR\abinding\"\xb6\x01\n" +
	"\x0fIdempotencyRule\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fmetadata_key\x18\x02 \x01(\tR\vmetadataKey\x124\n" +
	"\x16processing_ttl_seconds\x18\x03 \x01(\x03R\x14processingTtlSeconds\x12,\n" +
	"\x12result_ttl_seconds\x18\x04 \x01(\x03R\x10resultTtlSeconds\"\xbe\x01\n" +
	"\x10ContinuationRule\x12'\n" +
	"\x0fmachine_version\x18\x01 \x01(\tR\x0emachineVersion\x12(\n" +
	"\x10inline_budget_ms\x18\x02 \x01(\x03R\x0einlineBudgetMs\x12+\n" +
	"\x11retention_seconds\x18\x03 \x01(\x03R\x10retentionSeconds\x12*\n" +
	"\x11max_payload_bytes\x18\x04 \x01(\x03R\x0fmaxPayloadBytes\"\xa3\x01\n" +
	"\x0eProjectionRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"key_fields\x18\x02 \x03(\tR\tkeyFields\x12!\n" +
	"\fschema_major\x18\x03 \x01(\rR\vschemaMajor\x12?\n" +
	"\n" +
	"migrations\x18\x04 \x03(\v2\x1f.keelith.v1.ProjectionMigrationR\n" +
	"migrations\"\xe5\x01\n" +
	"\x18ProjectionFieldMigration\x12%\n" +
	"\x0eprevious_field\x18\x01 \x01(\tR\rpreviousField\x12#\n" +
	"\rcurrent_field\x18\x02 \x01(\tR\fcurrentField\x12(\n" +
	"\rdefault_value\x18\x03 \x01(\tH\x00R\fdefaultValue\x88\x01\x01\x12A\n" +
	"\vdrop_policy\x18\x04 \x01(\x0e2 .keelith.v1.ProjectionDropPolicyR\n" +
	"dropPolicyB\x10\n" +
	"\x0e_default_value\"\x95\x02\n" +
	"\x13ProjectionMigration\x121\n" +
	"\x14previous_fingerprint\x18\x01 \x01(\tR\x13previousFingerprint\x12)\n" +
	"\x10previous_message\x18\x02 \x01(\tR\x0fpreviousMessage\x122\n" +
	"\x15previous_schema_major\x18\x03 \x01(\rR\x13previousSchemaMajor\x12<\n" +
	"\x06fields\x18\x04 \x03(\v2$.keelith.v1.ProjectionFieldMigrationR\x06fields\x12.\n" +
	"\x13previous_key_fields\x18\x05 \x03(\tR\x11previousKeyFields*\xb8\x01\n" +
	"\x18ServiceDependencyBinding\x12*\n" +
	"&SERVICE_DEPENDENCY_BINDING_UNSPECIFIED\x10\x00\x12%\n" +
	"!SERVICE_DEPENDENCY_BINDING_REMOTE\x10\x01\x12#\n" +
	"\x1fSERVICE_DEPENDENCY_BINDING_AUTO\x10\x02\x12$\n" +
	" SERVICE_DEPENDENCY_BINDING_LOCAL\x10\x03*`\n" +
	"\x14ProjectionDropPolicy\x12&\n" +
	"\"PROJECTION_DROP_POLICY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPROJECTION_DROP_POLICY_ALLOW\x10\x01:C\n" +
	"\ferror_reason\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x01(\tR\verrorReason:_\n" +
	"\n" +
	"dependency\x12\x1e.google.protobuf.MethodOptions\x18\xbc\x8e\x03 \x03(\v2\x1d.keelith.v1.ServiceDependencyR\n" +
	"dependency:_\n" +
	"\vidempotency\x12\x1e.google.protobuf.MethodOptions\x18\xbe\x8e\x03 \x01(\v2\x1b.keelith.v1.IdempotencyRuleR\vidempotency:b\n" +
	"\fcontinuation\x12\x1e.google.protobuf.MethodOptions\x18\xbf\x8e\x03 \x01(\v2\x1c.keelith.v1.ContinuationRuleR\fcontinuation:]\n" +
	"\n" +
	"projection\x12\x1f.google.protobuf.MessageOptions\x18\xc0\x8e\x03 \x01(\v2\x1a.keelith.v1.ProjectionRuleR\n" +
	"projection:B\n" +
	"\n" +
	"error_code\x12!.google.protobuf.EnumValueOptions\x18\xbd\x8e\x03 \x01(\x05R\terrorCodeB,Z*github.com/keelab/keelith/api/v1;keelithv1b\x06proto3"

var (
	file_v1_annotations_proto_rawDescOnce sync.Once
	file_v1_annotations_proto_rawDescData []byte
)

func file_v1_annotations_proto_rawDescGZIP() []byte {
	file_v1_annotations_proto_rawDescOnce.Do(func() {
		file_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_annotations_proto_rawDesc), len(file_v1_annotations_proto_rawDesc)))
	})
	return file_v1_annotations_proto_rawDescData
}

var file_v1_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_annotations_proto_goTypes = []any{
	(ServiceDependencyBinding)(0),         // 0: keelith.v1.ServiceDependencyBinding
	(ProjectionDropPolicy)(0),             // 1: keelith.v1.ProjectionDropPolicy
	(*ServiceDependency)(nil),             // 2: keelith.v1.ServiceDependency
	(*IdempotencyRule)(nil),               // 3: keelith.v1.IdempotencyRule
	(*ContinuationRule)(nil),              // 4: keelith.v1.ContinuationRule
	(*ProjectionRule)(nil),                // 5: keelith.v1.ProjectionRule
	(*ProjectionFieldMigration)(nil),      // 6: keelith.v1.ProjectionFieldMigration
	(*ProjectionMigration)(nil),           // 7: keelith.v1.ProjectionMigration
	(*descriptorpb.MethodOptions)(nil),    // 8: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil),   // 9: google.protobuf.MessageOptions
	(*descriptorpb.EnumValueOptions)(nil), // 10: google.protobuf.EnumValueOptions
}
var file_v1_annotations_proto_depIdxs = []int32{
	0,  // 0: keelith.v1.ServiceDependency.binding:type_name -> keelith.v1.ServiceDependencyBinding
	7,  // 1: keelith.v1.ProjectionRule.migrations:type_name -> keelith.v1.ProjectionMigration
	1,  // 2: keelith.v1.ProjectionFieldMigration.drop_policy:type_name -> keelith.v1.ProjectionDropPolicy
	6,  // 3: keelith.v1.ProjectionMigration.fields:type_name -> keelith.v1.ProjectionFieldMigration
	8,  // 4: keelith.v1.error_reason:extendee -> google.protobuf.MethodOptions
	8,  // 5: keelith.v1.dependency:extendee -> google.protobuf.MethodOptions
	8,  // 6: keelith.v1.idempotency:extendee -> google.protobuf.MethodOptions
	8,  // 7: keelith.v1.continuation:extendee -> google.protobuf.MethodOptions
	9,  // 8: keelith.v1.projection:extendee -> google.protobuf.MessageOptions
	10, // 9: keelith.v1.error_code:extendee -> google.protobuf.EnumValueOptions
	2,  // 10: keelith.v1.dependency:type_name -> keelith.v1.ServiceDependency
	3,  // 11: keelith.v1.idempotency:type_name -> keelith.v1.IdempotencyRule
	4,  // 12: keelith.v1.continuation:type_name -> keelith.v1.ContinuationRule
	5,  // 13: keelith.v1.projection:type_name -> keelith.v1.ProjectionRule
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	10, // [10:14] is the sub-list for extension type_name
	4,  // [4:10] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_annotations_proto_init() }
func file_v1_annotations_proto_init() {
	if File_v1_annotations_proto != nil {
		return
	}
	file_v1_annotations_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_annotations_proto_rawDesc), len(file_v1_annotations_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_v1_annotations_proto_goTypes,
		DependencyIndexes: file_v1_annotations_proto_depIdxs,
		EnumInfos:         file_v1_annotations_proto_enumTypes,
		MessageInfos:      file_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_v1_annotations_proto_extTypes,
	}.Build()
	File_v1_annotations_proto = out.File
	file_v1_annotations_proto_goTypes = nil
	file_v1_annotations_proto_depIdxs = nil
}
