// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/errors.proto

package keelithv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED       ErrorReason = 0
	ErrorReason_ERROR_REASON_VALIDATION_FAILED ErrorReason = 1
	ErrorReason_ERROR_REASON_NOT_FOUND         ErrorReason = 2
	ErrorReason_ERROR_REASON_CONFLICT          ErrorReason = 3
	ErrorReason_ERROR_REASON_INTERNAL          ErrorReason = 4
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "ERROR_REASON_VALIDATION_FAILED",
		2: "ERROR_REASON_NOT_FOUND",
		3: "ERROR_REASON_CONFLICT",
		4: "ERROR_REASON_INTERNAL",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":       0,
		"ERROR_REASON_VALIDATION_FAILED": 1,
		"ERROR_REASON_NOT_FOUND":         2,
		"ERROR_REASON_CONFLICT":          3,
		"ERROR_REASON_INTERNAL":          4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_v1_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_v1_errors_proto protoreflect.FileDescriptor

const file_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/errors.proto\x12\n" +
	"keelith.v1\x1a\x14v1/annotations.proto*\xbd\x01\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12)\n" +
	"\x1eERROR_REASON_VALIDATION_FAILED\x10\x01\x1a\x05\xe8\xf3\x18\x90\x03\x12!\n" +
	"\x16ERROR_REASON_NOT_FOUND\x10\x02\x1a\x05\xe8\xf3\x18\x94\x03\x12 \n" +
	"\x15ERROR_REASON_CONFLICT\x10\x03\x1a\x05\xe8\xf3\x18\x99\x03\x12 \n" +
	"\x15ERROR_REASON_INTERNAL\x10\x04\x1a\x05\xe8\xf3\x18\xf4\x03B,Z*github.com/keelab/keelith/api/v1;keelithv1b\x06proto3"

var (
	file_v1_errors_proto_rawDescOnce sync.Once
	file_v1_errors_proto_rawDescData []byte
)

func file_v1_errors_proto_rawDescGZIP() []byte {
	file_v1_errors_proto_rawDescOnce.Do(func() {
		file_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_errors_proto_rawDesc), len(file_v1_errors_proto_rawDesc)))
	})
	return file_v1_errors_proto_rawDescData
}

var file_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_errors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: keelith.v1.ErrorReason
}
var file_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_errors_proto_init() }
func file_v1_errors_proto_init() {
	if File_v1_errors_proto != nil {
		return
	}
	file_v1_annotations_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_errors_proto_rawDesc), len(file_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_errors_proto_goTypes,
		DependencyIndexes: file_v1_errors_proto_depIdxs,
		EnumInfos:         file_v1_errors_proto_enumTypes,
	}.Build()
	File_v1_errors_proto = out.File
	file_v1_errors_proto_goTypes = nil
	file_v1_errors_proto_depIdxs = nil
}
