// Code generated by protoc-gen-go-keelith. DO NOT EDIT.
// source: v1/errors.proto

package keelithv1

import (
	errors "github.com/keelab/keelith/errors"
)

// FrameworkValidationFailedReason is the stable machine reason declared by the Proto enum.
const FrameworkValidationFailedReason = "ERROR_REASON_VALIDATION_FAILED"

// FrameworkValidationFailedCode is the stable transport-neutral application code.
const FrameworkValidationFailedCode int32 = 400

// ErrFrameworkValidationFailed is the immutable identity sentinel for this error.
var ErrFrameworkValidationFailed = errors.New(FrameworkValidationFailedCode, FrameworkValidationFailedReason, "")

// NewFrameworkValidationFailed constructs this declared application error.
func NewFrameworkValidationFailed(message string, options ...errors.Option) *errors.Error {
	return errors.New(FrameworkValidationFailedCode, FrameworkValidationFailedReason, message, options...)
}

// WrapFrameworkValidationFailed preserves a private cause while exposing this declared identity.
func WrapFrameworkValidationFailed(cause error, message string, options ...errors.Option) *errors.Error {
	return errors.Wrap(cause, FrameworkValidationFailedCode, FrameworkValidationFailedReason, message, options...)
}

// FrameworkNotFoundReason is the stable machine reason declared by the Proto enum.
const FrameworkNotFoundReason = "ERROR_REASON_NOT_FOUND"

// FrameworkNotFoundCode is the stable transport-neutral application code.
const FrameworkNotFoundCode int32 = 404

// ErrFrameworkNotFound is the immutable identity sentinel for this error.
var ErrFrameworkNotFound = errors.New(FrameworkNotFoundCode, FrameworkNotFoundReason, "")

// NewFrameworkNotFound constructs this declared application error.
func NewFrameworkNotFound(message string, options ...errors.Option) *errors.Error {
	return errors.New(FrameworkNotFoundCode, FrameworkNotFoundReason, message, options...)
}

// WrapFrameworkNotFound preserves a private cause while exposing this declared identity.
func WrapFrameworkNotFound(cause error, message string, options ...errors.Option) *errors.Error {
	return errors.Wrap(cause, FrameworkNotFoundCode, FrameworkNotFoundReason, message, options...)
}

// FrameworkConflictReason is the stable machine reason declared by the Proto enum.
const FrameworkConflictReason = "ERROR_REASON_CONFLICT"

// FrameworkConflictCode is the stable transport-neutral application code.
const FrameworkConflictCode int32 = 409

// ErrFrameworkConflict is the immutable identity sentinel for this error.
var ErrFrameworkConflict = errors.New(FrameworkConflictCode, FrameworkConflictReason, "")

// NewFrameworkConflict constructs this declared application error.
func NewFrameworkConflict(message string, options ...errors.Option) *errors.Error {
	return errors.New(FrameworkConflictCode, FrameworkConflictReason, message, options...)
}

// WrapFrameworkConflict preserves a private cause while exposing this declared identity.
func WrapFrameworkConflict(cause error, message string, options ...errors.Option) *errors.Error {
	return errors.Wrap(cause, FrameworkConflictCode, FrameworkConflictReason, message, options...)
}

// FrameworkInternalReason is the stable machine reason declared by the Proto enum.
const FrameworkInternalReason = "ERROR_REASON_INTERNAL"

// FrameworkInternalCode is the stable transport-neutral application code.
const FrameworkInternalCode int32 = 500

// ErrFrameworkInternal is the immutable identity sentinel for this error.
var ErrFrameworkInternal = errors.New(FrameworkInternalCode, FrameworkInternalReason, "")

// NewFrameworkInternal constructs this declared application error.
func NewFrameworkInternal(message string, options ...errors.Option) *errors.Error {
	return errors.New(FrameworkInternalCode, FrameworkInternalReason, message, options...)
}

// WrapFrameworkInternal preserves a private cause while exposing this declared identity.
func WrapFrameworkInternal(cause error, message string, options ...errors.Option) *errors.Error {
	return errors.Wrap(cause, FrameworkInternalCode, FrameworkInternalReason, message, options...)
}
