// Package kitexfacade generates governance-safe facades around Kitex clients.
package kitexfacade

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"path"
	"sort"
	"strconv"
	"strings"
)

const (
	// GeneratedHeader identifies files owned by the Kitex facade generator.
	GeneratedHeader = "// Code generated by keelith generate kitex-facade. DO NOT EDIT.\n"

	kitexCallOptionPath       = "github.com/cloudwego/kitex/client/callopt"
	kitexStreamCallOptionPath = "github.com/cloudwego/kitex/client/callopt/streamcall"
	keelithKitexProfilePath   = "anniext.cn/keelith/keelith/x/transport/kitex"
)

// Result describes one generated Kitex client facade.
type Result struct {
	Package    string
	Interfaces []string
	Symbols    []string
	Content    []byte
}

type clientInterface struct {
	rawName     string
	safeName    string
	wrapperName string
	bindingName string
	constructor string
	methods     []clientMethod
}

type clientMethod struct {
	name            string
	signature       *ast.FuncType
	arguments       []string
	contextArgument string
	hasResults      bool
}

type sourceImport struct {
	alias    string
	path     string
	explicit bool
}

// Generate converts a standard Kitex client.go source into a Keelith-managed
// facade. Every Client or StreamClient method must end in Kitex call options;
// unknown interface shapes fail closed.
func Generate(filename string, source []byte) (Result, error) {
	if !isKitexGeneratedSource(source) {
		return Result{}, fmt.Errorf(
			"kitex facade: %s is not a Kitex-generated client source",
			filename,
		)
	}
	files := token.NewFileSet()
	parsed, err := parser.ParseFile(
		files,
		filename,
		source,
		parser.SkipObjectResolution,
	)
	if err != nil {
		return Result{}, fmt.Errorf("kitex facade: parse %s: %w", filename, err)
	}
	imports, err := parseImports(parsed)
	if err != nil {
		return Result{}, fmt.Errorf("kitex facade: %s: %w", filename, err)
	}
	clients, usedAliases, err := parseClientInterfaces(parsed, imports)
	if err != nil {
		return Result{}, fmt.Errorf("kitex facade: %s: %w", filename, err)
	}
	if len(clients) == 0 {
		return Result{}, fmt.Errorf(
			"kitex facade: %s does not declare Client or StreamClient",
			filename,
		)
	}
	content, err := render(
		parsed.Name.Name,
		clients,
		imports,
		usedAliases,
	)
	if err != nil {
		return Result{}, fmt.Errorf("kitex facade: render %s: %w", filename, err)
	}
	interfaces := make([]string, 0, len(clients))
	symbols := make([]string, 0, len(clients)*5)
	for _, client := range clients {
		interfaces = append(interfaces, client.safeName)
		symbols = append(
			symbols,
			client.safeName,
			client.wrapperName,
			client.bindingName,
			client.constructor,
		)
	}
	return Result{
		Package:    parsed.Name.Name,
		Interfaces: interfaces,
		Symbols:    symbols,
		Content:    content,
	}, nil
}

func isKitexGeneratedSource(source []byte) bool {
	line := source
	if index := bytes.IndexByte(line, '\n'); index >= 0 {
		line = line[:index]
	}
	return bytes.HasPrefix(line, []byte("// Code generated by Kitex ")) &&
		bytes.HasSuffix(line, []byte(". DO NOT EDIT."))
}

func parseImports(file *ast.File) (map[string]sourceImport, error) {
	imports := make(map[string]sourceImport, len(file.Imports))
	for _, spec := range file.Imports {
		importPath, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			return nil, fmt.Errorf("invalid import %s", spec.Path.Value)
		}
		alias := path.Base(importPath)
		explicit := spec.Name != nil
		if explicit {
			alias = spec.Name.Name
		}
		if alias == "." || alias == "_" {
			return nil, fmt.Errorf(
				"dot and blank imports are not supported in Kitex client sources",
			)
		}
		if previous, exists := imports[alias]; exists &&
			previous.path != importPath {
			return nil, fmt.Errorf("duplicate import alias %q", alias)
		}
		imports[alias] = sourceImport{
			alias:    alias,
			path:     importPath,
			explicit: explicit,
		}
	}
	return imports, nil
}

func parseClientInterfaces(
	file *ast.File,
	imports map[string]sourceImport,
) ([]clientInterface, map[string]struct{}, error) {
	wanted := map[string]clientInterface{
		"Client": {
			rawName:     "Client",
			safeName:    "KeelithClient",
			wrapperName: "keelithClient",
			bindingName: "KeelithClientBinding",
			constructor: "NewKeelithClient",
		},
		"StreamClient": {
			rawName:     "StreamClient",
			safeName:    "KeelithStreamClient",
			wrapperName: "keelithStreamClient",
			bindingName: "KeelithStreamClientBinding",
			constructor: "NewKeelithStreamClient",
		},
	}
	found := make(map[string]clientInterface, len(wanted))
	usedAliases := make(map[string]struct{})
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}
		for _, rawSpec := range general.Specs {
			spec, ok := rawSpec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			client, selected := wanted[spec.Name.Name]
			if !selected {
				continue
			}
			if _, duplicate := found[spec.Name.Name]; duplicate {
				return nil, nil, fmt.Errorf(
					"client interface %s is declared more than once",
					spec.Name.Name,
				)
			}
			interfaceType, ok := spec.Type.(*ast.InterfaceType)
			if !ok {
				return nil, nil, fmt.Errorf(
					"%s is not an interface",
					spec.Name.Name,
				)
			}
			methods, err := parseMethods(
				spec.Name.Name,
				interfaceType,
				imports,
				usedAliases,
			)
			if err != nil {
				return nil, nil, err
			}
			client.methods = methods
			found[spec.Name.Name] = client
		}
	}
	clients := make([]clientInterface, 0, len(found))
	for _, name := range []string{"Client", "StreamClient"} {
		if client, ok := found[name]; ok {
			clients = append(clients, client)
		}
	}
	return clients, usedAliases, nil
}

func parseMethods(
	interfaceName string,
	interfaceType *ast.InterfaceType,
	imports map[string]sourceImport,
	usedAliases map[string]struct{},
) ([]clientMethod, error) {
	if interfaceType.Methods == nil || len(interfaceType.Methods.List) == 0 {
		return nil, fmt.Errorf("%s has no methods", interfaceName)
	}
	methods := make([]clientMethod, 0, len(interfaceType.Methods.List))
	seen := make(map[string]struct{}, len(interfaceType.Methods.List))
	for _, field := range interfaceType.Methods.List {
		if len(field.Names) != 1 {
			return nil, fmt.Errorf(
				"%s contains an embedded or unnamed member",
				interfaceName,
			)
		}
		methodName := field.Names[0].Name
		if _, duplicate := seen[methodName]; duplicate {
			return nil, fmt.Errorf(
				"%s method %s is declared more than once",
				interfaceName,
				methodName,
			)
		}
		seen[methodName] = struct{}{}
		function, ok := field.Type.(*ast.FuncType)
		if !ok {
			return nil, fmt.Errorf(
				"%s.%s is not a method",
				interfaceName,
				methodName,
			)
		}
		signature, arguments, contextArgument, err := safeSignature(
			interfaceName,
			methodName,
			function,
			imports,
		)
		if err != nil {
			return nil, err
		}
		collectImportAliases(signature.Params, usedAliases)
		collectImportAliases(signature.Results, usedAliases)
		methods = append(methods, clientMethod{
			name:            methodName,
			signature:       signature,
			arguments:       arguments,
			contextArgument: contextArgument,
			hasResults: signature.Results != nil &&
				len(signature.Results.List) > 0,
		})
	}
	return methods, nil
}

func safeSignature(
	interfaceName string,
	methodName string,
	function *ast.FuncType,
	imports map[string]sourceImport,
) (*ast.FuncType, []string, string, error) {
	if function.Params == nil || len(function.Params.List) == 0 {
		return nil, nil, "", fmt.Errorf(
			"%s.%s does not end in Kitex call options",
			interfaceName,
			methodName,
		)
	}
	parameters := append([]*ast.Field(nil), function.Params.List...)
	last := parameters[len(parameters)-1]
	ellipsis, ok := last.Type.(*ast.Ellipsis)
	if !ok || !isKitexCallOption(ellipsis.Elt, imports) {
		return nil, nil, "", fmt.Errorf(
			"%s.%s does not end in supported Kitex call options",
			interfaceName,
			methodName,
		)
	}
	if len(last.Names) != 1 {
		return nil, nil, "", fmt.Errorf(
			"%s.%s has ambiguous call options",
			interfaceName,
			methodName,
		)
	}
	parameters = parameters[:len(parameters)-1]
	if len(parameters) == 0 ||
		len(parameters[0].Names) != 1 ||
		!isContextType(parameters[0].Type, imports) {
		return nil, nil, "", fmt.Errorf(
			"%s.%s does not start with one context.Context parameter",
			interfaceName,
			methodName,
		)
	}
	contextArgument := parameters[0].Names[0].Name
	arguments := make([]string, 0, len(parameters))
	for _, parameter := range parameters {
		if _, variadic := parameter.Type.(*ast.Ellipsis); variadic {
			return nil, nil, "", fmt.Errorf(
				"%s.%s has an unsupported variadic business parameter",
				interfaceName,
				methodName,
			)
		}
		if len(parameter.Names) == 0 {
			return nil, nil, "", fmt.Errorf(
				"%s.%s has an unnamed business parameter",
				interfaceName,
				methodName,
			)
		}
		for _, name := range parameter.Names {
			if name.Name == "_" {
				return nil, nil, "", fmt.Errorf(
					"%s.%s has a blank business parameter",
					interfaceName,
					methodName,
				)
			}
			arguments = append(arguments, name.Name)
		}
	}
	return &ast.FuncType{
		Params:  &ast.FieldList{List: parameters},
		Results: function.Results,
	}, arguments, contextArgument, nil
}

func isKitexCallOption(
	expression ast.Expr,
	imports map[string]sourceImport,
) bool {
	selector, ok := expression.(*ast.SelectorExpr)
	if !ok || selector.Sel.Name != "Option" {
		return false
	}
	identifier, ok := selector.X.(*ast.Ident)
	if !ok {
		return false
	}
	imported, ok := imports[identifier.Name]
	if !ok {
		return false
	}
	return imported.path == kitexCallOptionPath ||
		imported.path == kitexStreamCallOptionPath
}

func isContextType(
	expression ast.Expr,
	imports map[string]sourceImport,
) bool {
	selector, ok := expression.(*ast.SelectorExpr)
	if !ok || selector.Sel.Name != "Context" {
		return false
	}
	identifier, ok := selector.X.(*ast.Ident)
	if !ok {
		return false
	}
	imported, ok := imports[identifier.Name]
	return ok && imported.path == "context"
}

func collectImportAliases(
	fields *ast.FieldList,
	used map[string]struct{},
) {
	if fields == nil {
		return
	}
	ast.Inspect(fields, func(node ast.Node) bool {
		selector, ok := node.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		if identifier, ok := selector.X.(*ast.Ident); ok {
			used[identifier.Name] = struct{}{}
		}
		return true
	})
}

func render(
	packageName string,
	clients []clientInterface,
	imports map[string]sourceImport,
	usedAliases map[string]struct{},
) ([]byte, error) {
	occupied := make(map[string]struct{}, len(usedAliases)+12)
	for alias := range usedAliases {
		occupied[alias] = struct{}{}
	}
	for _, client := range clients {
		occupied[client.rawName] = struct{}{}
		occupied[client.safeName] = struct{}{}
		occupied[client.wrapperName] = struct{}{}
		occupied[client.bindingName] = struct{}{}
		occupied[client.constructor] = struct{}{}
	}
	errorsAlias := uniqueIdentifier("keelitherrors", occupied)
	reflectAlias := uniqueIdentifier("keelithreflect", occupied)
	syncAlias := uniqueIdentifier("keelithsync", occupied)
	profileAlias := uniqueIdentifier("keelithkitex", occupied)

	selectedImports := make([]sourceImport, 0, len(usedAliases)+4)
	for alias := range usedAliases {
		imported, ok := imports[alias]
		if !ok {
			return nil, fmt.Errorf(
				"signature references unknown import alias %q",
				alias,
			)
		}
		if imported.path == kitexCallOptionPath ||
			imported.path == kitexStreamCallOptionPath {
			return nil, fmt.Errorf(
				"call-option import %q remains in safe signature",
				imported.path,
			)
		}
		selectedImports = append(selectedImports, imported)
	}
	selectedImports = append(
		selectedImports,
		sourceImport{alias: errorsAlias, path: "errors", explicit: true},
		sourceImport{alias: reflectAlias, path: "reflect", explicit: true},
		sourceImport{alias: syncAlias, path: "sync", explicit: true},
		sourceImport{
			alias:    profileAlias,
			path:     keelithKitexProfilePath,
			explicit: true,
		},
	)
	sort.Slice(selectedImports, func(first, second int) bool {
		firstStandard := isStandardImport(selectedImports[first].path)
		secondStandard := isStandardImport(selectedImports[second].path)
		if firstStandard != secondStandard {
			return firstStandard
		}
		if selectedImports[first].path == selectedImports[second].path {
			return selectedImports[first].alias < selectedImports[second].alias
		}
		return selectedImports[first].path < selectedImports[second].path
	})

	var output bytes.Buffer
	output.WriteString(GeneratedHeader)
	output.WriteString("\npackage ")
	output.WriteString(packageName)
	output.WriteString("\n\nimport (\n")
	for index, imported := range selectedImports {
		if index > 0 &&
			isStandardImport(selectedImports[index-1].path) !=
				isStandardImport(imported.path) {
			output.WriteByte('\n')
		}
		output.WriteByte('\t')
		if imported.explicit {
			output.WriteString(imported.alias)
			output.WriteByte(' ')
		}
		output.WriteString(strconv.Quote(imported.path))
		output.WriteByte('\n')
	}
	output.WriteString(")\n\n")
	for _, client := range clients {
		if err := renderClient(
			&output,
			client,
			errorsAlias,
			reflectAlias,
			syncAlias,
			profileAlias,
		); err != nil {
			return nil, err
		}
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func renderClient(
	output *bytes.Buffer,
	client clientInterface,
	errorsAlias string,
	reflectAlias string,
	syncAlias string,
	profileAlias string,
) error {
	output.WriteString("// ")
	output.WriteString(client.safeName)
	output.WriteString(
		" exposes generated Kitex calls without per-call native governance options.\n",
	)
	output.WriteString("type ")
	output.WriteString(client.safeName)
	output.WriteString(" interface {\n")
	for _, method := range client.methods {
		output.WriteByte('\t')
		output.WriteString(method.name)
		if err := printFunctionSignature(
			output,
			method.signature,
		); err != nil {
			return err
		}
		output.WriteByte('\n')
	}
	output.WriteString("}\n\n")

	output.WriteString("type ")
	output.WriteString(client.wrapperName)
	output.WriteString(" struct {\n\traw ")
	output.WriteString(client.rawName)
	output.WriteString("\n}\n\n")

	output.WriteString("// ")
	output.WriteString(client.bindingName)
	output.WriteString(
		" owns one managed Kitex client and exposes only its safe facade.\n",
	)
	output.WriteString("type ")
	output.WriteString(client.bindingName)
	output.WriteString(" struct {\n\tclient ")
	output.WriteString(client.safeName)
	output.WriteString("\n\tclose func() error\n\tonce ")
	output.WriteString(syncAlias)
	output.WriteString(".Once\n\terr error\n}\n\n")

	output.WriteString("// ")
	output.WriteString(client.constructor)
	output.WriteString(
		" constructs, audits, and hides the raw generated Kitex client.\n",
	)
	output.WriteString("func ")
	output.WriteString(client.constructor)
	output.WriteString("(suite *")
	output.WriteString(profileAlias)
	output.WriteString(".ClientSuite, factory ")
	output.WriteString(profileAlias)
	output.WriteString(".ManagedClientFactory[")
	output.WriteString(client.rawName)
	output.WriteString("]) (*")
	output.WriteString(client.bindingName)
	output.WriteString(", error) {\n")
	output.WriteString("\traw, err := ")
	output.WriteString(profileAlias)
	output.WriteString(".NewManagedClient(suite, factory)\n")
	output.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	output.WriteString("\tif raw == nil || (")
	output.WriteString(reflectAlias)
	output.WriteString(".ValueOf(raw).Kind() == ")
	output.WriteString(reflectAlias)
	output.WriteString(".Pointer && ")
	output.WriteString(reflectAlias)
	output.WriteString(".ValueOf(raw).IsNil()) {\n\t\treturn nil, ")
	output.WriteString(errorsAlias)
	output.WriteString(
		".New(\"keelith generated Kitex facade: client is nil\")\n\t}\n",
	)
	output.WriteString(
		"\tcloser, ok := any(raw).(interface{ Close() error })\n",
	)
	output.WriteString("\tif !ok {\n\t\treturn nil, ")
	output.WriteString(errorsAlias)
	output.WriteString(
		".New(\"keelith generated Kitex facade: client is not closable\")\n\t}\n",
	)
	output.WriteString("\treturn &")
	output.WriteString(client.bindingName)
	output.WriteString("{\n\t\tclient: &")
	output.WriteString(client.wrapperName)
	output.WriteString("{raw: raw},\n\t\tclose: closer.Close,\n\t}, nil\n}\n\n")

	output.WriteString("// Client returns the call-option-free client facade.\n")
	output.WriteString("func (binding *")
	output.WriteString(client.bindingName)
	output.WriteString(") Client() ")
	output.WriteString(client.safeName)
	output.WriteString(" {\n\tif binding == nil {\n\t\treturn nil\n\t}\n")
	output.WriteString("\treturn binding.client\n}\n\n")

	output.WriteString("// Close releases the managed Kitex client exactly once.\n")
	output.WriteString("func (binding *")
	output.WriteString(client.bindingName)
	output.WriteString(") Close() error {\n\tif binding == nil {\n\t\treturn nil\n\t}\n")
	output.WriteString(
		"\tbinding.once.Do(func() { binding.err = binding.close() })\n",
	)
	output.WriteString("\treturn binding.err\n}\n\n")

	for _, method := range client.methods {
		receiver := uniqueReceiver(method.arguments)
		output.WriteString("func (")
		output.WriteString(receiver)
		output.WriteString(" *")
		output.WriteString(client.wrapperName)
		output.WriteString(") ")
		output.WriteString(method.name)
		if err := printFunctionSignature(
			output,
			method.signature,
		); err != nil {
			return err
		}
		output.WriteString(" {\n\t")
		if method.hasResults {
			output.WriteString("return ")
		}
		arguments := append([]string(nil), method.arguments...)
		arguments[0] = profileAlias +
			".WithoutNativeCallOptions(" +
			method.contextArgument +
			")"
		output.WriteString(receiver)
		output.WriteString(".raw.")
		output.WriteString(method.name)
		output.WriteByte('(')
		output.WriteString(strings.Join(arguments, ", "))
		output.WriteString(")\n}\n\n")
	}
	return nil
}

func printFunctionSignature(
	output *bytes.Buffer,
	function *ast.FuncType,
) error {
	var signature bytes.Buffer
	if err := printer.Fprint(
		&signature,
		token.NewFileSet(),
		function,
	); err != nil {
		return fmt.Errorf("print method signature: %w", err)
	}
	rendered := signature.String()
	if !strings.HasPrefix(rendered, "func") {
		return fmt.Errorf("print method signature: missing func prefix")
	}
	output.WriteString(strings.TrimPrefix(rendered, "func"))
	return nil
}

func isStandardImport(importPath string) bool {
	first, _, _ := strings.Cut(importPath, "/")
	return !strings.Contains(first, ".")
}

func uniqueIdentifier(base string, occupied map[string]struct{}) string {
	candidate := base
	for suffix := 2; ; suffix++ {
		if _, used := occupied[candidate]; !used {
			occupied[candidate] = struct{}{}
			return candidate
		}
		candidate = fmt.Sprintf("%s%d", base, suffix)
	}
}

func uniqueReceiver(arguments []string) string {
	occupied := make(map[string]struct{}, len(arguments))
	for _, argument := range arguments {
		occupied[argument] = struct{}{}
	}
	return uniqueIdentifier("keelithFacade", occupied)
}
