package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/keelab/keelith/internal/generator/data"
)

const dataGeneratedHeader = "// Code generated by keelith data. DO NOT EDIT.\n"

type dataOptions struct {
	path      string
	schema    string
	packageID string
	output    string
	format    string
	check     bool
}

type dataResult struct {
	Schema string `json:"schema"`
	Output string `json:"output"`
	Status string `json:"status"`
}

func executeGenerateData(
	ctx context.Context,
	options dataOptions,
	stdout io.Writer,
	stderr io.Writer,
) int {
	project, err := existingProjectRoot(options.path)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "keelith generate data: %v\n", err)
		return 1
	}
	schemaPath, err := safeProjectFile(project, options.schema, false)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "keelith generate data: %v\n", err)
		return 1
	}
	outputPath, err := safeProjectFile(project, options.output, true)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "keelith generate data: %v\n", err)
		return 1
	}
	if cause := context.Cause(ctx); cause != nil {
		_, _ = fmt.Fprintf(stderr, "keelith generate data: %v\n", cause)
		return 1
	}
	schema, err := os.ReadFile(schemaPath)
	if err != nil {
		_, _ = fmt.Fprintf(
			stderr,
			"keelith generate data: read schema: %v\n",
			err,
		)
		return 1
	}
	generated, err := data.Generate(options.packageID, schema)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "keelith generate data: %v\n", err)
		return 1
	}
	before, exists, err := readOptional(outputPath)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "keelith generate data: %v\n", err)
		return 1
	}
	if exists && !bytes.HasPrefix(before, []byte(dataGeneratedHeader)) {
		_, _ = fmt.Fprintf(
			stderr,
			"keelith generate data: refusing to overwrite handwritten file %s\n",
			options.output,
		)
		return 1
	}
	result := dataResult{
		Schema: filepath.ToSlash(options.schema),
		Output: filepath.ToSlash(options.output),
		Status: "unchanged",
	}
	changed := !exists || !bytes.Equal(before, generated)
	if changed {
		result.Status = "created"
		if exists {
			result.Status = "updated"
		}
		if options.check {
			result.Status = "drifted"
		} else {
			if cause := context.Cause(ctx); cause != nil {
				_, _ = fmt.Fprintf(stderr, "keelith generate data: %v\n", cause)
				return 1
			}
			if err := atomicWriteFile(outputPath, generated, 0o644); err != nil {
				_, _ = fmt.Fprintf(
					stderr,
					"keelith generate data: write output: %v\n",
					err,
				)
				return 1
			}
		}
	}
	if options.format == "json" {
		if err := json.NewEncoder(stdout).Encode(result); err != nil {
			_, _ = fmt.Fprintf(
				stderr,
				"keelith generate data: encode result: %v\n",
				err,
			)
			return 1
		}
	} else {
		_, _ = fmt.Fprintf(
			stdout,
			"%s data model %s\n",
			result.Status,
			result.Output,
		)
	}
	if options.check && changed {
		return 1
	}
	return 0
}

func existingProjectRoot(path string) (string, error) {
	root, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve project: %w", err)
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return "", fmt.Errorf("resolve project symlinks: %w", err)
	}
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		return "", errors.New("project is not a directory")
	}
	return root, nil
}

func safeProjectFile(
	root string,
	relative string,
	allowMissing bool,
) (string, error) {
	normalized := filepath.ToSlash(filepath.Clean(filepath.FromSlash(relative)))
	if normalized != filepath.ToSlash(relative) {
		return "", fmt.Errorf("project file %q is not canonical", relative)
	}
	path, err := managedPath(root, relative)
	if err != nil {
		return "", err
	}
	clean := filepath.Clean(filepath.FromSlash(relative))
	parts := strings.Split(clean, string(filepath.Separator))
	current := root
	for index, part := range parts {
		current = filepath.Join(current, part)
		info, statErr := os.Lstat(current)
		if errors.Is(statErr, os.ErrNotExist) {
			if allowMissing {
				return path, nil
			}
			return "", fmt.Errorf("project file %q does not exist", relative)
		}
		if statErr != nil {
			return "", fmt.Errorf("inspect project file %q: %w", relative, statErr)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("project file %q traverses a symlink", relative)
		}
		if index < len(parts)-1 && !info.IsDir() {
			return "", fmt.Errorf(
				"project file %q has a non-directory parent",
				relative,
			)
		}
		if index == len(parts)-1 && info.IsDir() {
			return "", fmt.Errorf("project file %q is a directory", relative)
		}
	}
	return path, nil
}
