// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuation/v1/protocol.proto

package continuationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallStatus is the durable continuation lifecycle state.
type CallStatus int32

const (
	CallStatus_CALL_STATUS_UNSPECIFIED      CallStatus = 0
	CallStatus_CALL_STATUS_ACCEPTED         CallStatus = 1
	CallStatus_CALL_STATUS_RUNNING          CallStatus = 2
	CallStatus_CALL_STATUS_WAITING          CallStatus = 3
	CallStatus_CALL_STATUS_SUSPENDED        CallStatus = 4
	CallStatus_CALL_STATUS_CANCEL_REQUESTED CallStatus = 5
	CallStatus_CALL_STATUS_COMPLETED        CallStatus = 6
	CallStatus_CALL_STATUS_FAILED           CallStatus = 7
	CallStatus_CALL_STATUS_CANCELED         CallStatus = 8
	CallStatus_CALL_STATUS_EXPIRED          CallStatus = 9
)

// Enum value maps for CallStatus.
var (
	CallStatus_name = map[int32]string{
		0: "CALL_STATUS_UNSPECIFIED",
		1: "CALL_STATUS_ACCEPTED",
		2: "CALL_STATUS_RUNNING",
		3: "CALL_STATUS_WAITING",
		4: "CALL_STATUS_SUSPENDED",
		5: "CALL_STATUS_CANCEL_REQUESTED",
		6: "CALL_STATUS_COMPLETED",
		7: "CALL_STATUS_FAILED",
		8: "CALL_STATUS_CANCELED",
		9: "CALL_STATUS_EXPIRED",
	}
	CallStatus_value = map[string]int32{
		"CALL_STATUS_UNSPECIFIED":      0,
		"CALL_STATUS_ACCEPTED":         1,
		"CALL_STATUS_RUNNING":          2,
		"CALL_STATUS_WAITING":          3,
		"CALL_STATUS_SUSPENDED":        4,
		"CALL_STATUS_CANCEL_REQUESTED": 5,
		"CALL_STATUS_COMPLETED":        6,
		"CALL_STATUS_FAILED":           7,
		"CALL_STATUS_CANCELED":         8,
		"CALL_STATUS_EXPIRED":          9,
	}
)

func (x CallStatus) Enum() *CallStatus {
	p := new(CallStatus)
	*p = x
	return p
}

func (x CallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_continuation_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (CallStatus) Type() protoreflect.EnumType {
	return &file_continuation_v1_protocol_proto_enumTypes[0]
}

func (x CallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallStatus.Descriptor instead.
func (CallStatus) EnumDescriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{0}
}

// FrameKind identifies one ordered durable observation.
type FrameKind int32

const (
	FrameKind_FRAME_KIND_UNSPECIFIED      FrameKind = 0
	FrameKind_FRAME_KIND_ACCEPTED         FrameKind = 1
	FrameKind_FRAME_KIND_EVENT            FrameKind = 2
	FrameKind_FRAME_KIND_WAITING          FrameKind = 3
	FrameKind_FRAME_KIND_SIGNAL           FrameKind = 4
	FrameKind_FRAME_KIND_SUSPENDED        FrameKind = 5
	FrameKind_FRAME_KIND_CANCEL_REQUESTED FrameKind = 6
	FrameKind_FRAME_KIND_COMPLETED        FrameKind = 7
	FrameKind_FRAME_KIND_FAILED           FrameKind = 8
	FrameKind_FRAME_KIND_CANCELED         FrameKind = 9
	FrameKind_FRAME_KIND_EXPIRED          FrameKind = 10
	FrameKind_FRAME_KIND_WORKFLOW_CHILD   FrameKind = 11
)

// Enum value maps for FrameKind.
var (
	FrameKind_name = map[int32]string{
		0:  "FRAME_KIND_UNSPECIFIED",
		1:  "FRAME_KIND_ACCEPTED",
		2:  "FRAME_KIND_EVENT",
		3:  "FRAME_KIND_WAITING",
		4:  "FRAME_KIND_SIGNAL",
		5:  "FRAME_KIND_SUSPENDED",
		6:  "FRAME_KIND_CANCEL_REQUESTED",
		7:  "FRAME_KIND_COMPLETED",
		8:  "FRAME_KIND_FAILED",
		9:  "FRAME_KIND_CANCELED",
		10: "FRAME_KIND_EXPIRED",
		11: "FRAME_KIND_WORKFLOW_CHILD",
	}
	FrameKind_value = map[string]int32{
		"FRAME_KIND_UNSPECIFIED":      0,
		"FRAME_KIND_ACCEPTED":         1,
		"FRAME_KIND_EVENT":            2,
		"FRAME_KIND_WAITING":          3,
		"FRAME_KIND_SIGNAL":           4,
		"FRAME_KIND_SUSPENDED":        5,
		"FRAME_KIND_CANCEL_REQUESTED": 6,
		"FRAME_KIND_COMPLETED":        7,
		"FRAME_KIND_FAILED":           8,
		"FRAME_KIND_CANCELED":         9,
		"FRAME_KIND_EXPIRED":          10,
		"FRAME_KIND_WORKFLOW_CHILD":   11,
	}
)

func (x FrameKind) Enum() *FrameKind {
	p := new(FrameKind)
	*p = x
	return p
}

func (x FrameKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameKind) Descriptor() protoreflect.EnumDescriptor {
	return file_continuation_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (FrameKind) Type() protoreflect.EnumType {
	return &file_continuation_v1_protocol_proto_enumTypes[1]
}

func (x FrameKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameKind.Descriptor instead.
func (FrameKind) EnumDescriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{1}
}

type WorkflowNodeKind int32

const (
	WorkflowNodeKind_WORKFLOW_NODE_KIND_UNSPECIFIED WorkflowNodeKind = 0
	WorkflowNodeKind_WORKFLOW_NODE_KIND_MACHINE     WorkflowNodeKind = 1
	WorkflowNodeKind_WORKFLOW_NODE_KIND_TIMER       WorkflowNodeKind = 2
	WorkflowNodeKind_WORKFLOW_NODE_KIND_CHILD       WorkflowNodeKind = 3
	WorkflowNodeKind_WORKFLOW_NODE_KIND_JOIN        WorkflowNodeKind = 4
)

// Enum value maps for WorkflowNodeKind.
var (
	WorkflowNodeKind_name = map[int32]string{
		0: "WORKFLOW_NODE_KIND_UNSPECIFIED",
		1: "WORKFLOW_NODE_KIND_MACHINE",
		2: "WORKFLOW_NODE_KIND_TIMER",
		3: "WORKFLOW_NODE_KIND_CHILD",
		4: "WORKFLOW_NODE_KIND_JOIN",
	}
	WorkflowNodeKind_value = map[string]int32{
		"WORKFLOW_NODE_KIND_UNSPECIFIED": 0,
		"WORKFLOW_NODE_KIND_MACHINE":     1,
		"WORKFLOW_NODE_KIND_TIMER":       2,
		"WORKFLOW_NODE_KIND_CHILD":       3,
		"WORKFLOW_NODE_KIND_JOIN":        4,
	}
)

func (x WorkflowNodeKind) Enum() *WorkflowNodeKind {
	p := new(WorkflowNodeKind)
	*p = x
	return p
}

func (x WorkflowNodeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowNodeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_continuation_v1_protocol_proto_enumTypes[2].Descriptor()
}

func (WorkflowNodeKind) Type() protoreflect.EnumType {
	return &file_continuation_v1_protocol_proto_enumTypes[2]
}

func (x WorkflowNodeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowNodeKind.Descriptor instead.
func (WorkflowNodeKind) EnumDescriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{2}
}

type WorkflowNodeStatus int32

const (
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_UNSPECIFIED WorkflowNodeStatus = 0
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_PENDING     WorkflowNodeStatus = 1
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_RUNNING     WorkflowNodeStatus = 2
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_WAITING     WorkflowNodeStatus = 3
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_SUCCEEDED   WorkflowNodeStatus = 4
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_FAILED      WorkflowNodeStatus = 5
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_SKIPPED     WorkflowNodeStatus = 6
)

// Enum value maps for WorkflowNodeStatus.
var (
	WorkflowNodeStatus_name = map[int32]string{
		0: "WORKFLOW_NODE_STATUS_UNSPECIFIED",
		1: "WORKFLOW_NODE_STATUS_PENDING",
		2: "WORKFLOW_NODE_STATUS_RUNNING",
		3: "WORKFLOW_NODE_STATUS_WAITING",
		4: "WORKFLOW_NODE_STATUS_SUCCEEDED",
		5: "WORKFLOW_NODE_STATUS_FAILED",
		6: "WORKFLOW_NODE_STATUS_SKIPPED",
	}
	WorkflowNodeStatus_value = map[string]int32{
		"WORKFLOW_NODE_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_NODE_STATUS_PENDING":     1,
		"WORKFLOW_NODE_STATUS_RUNNING":     2,
		"WORKFLOW_NODE_STATUS_WAITING":     3,
		"WORKFLOW_NODE_STATUS_SUCCEEDED":   4,
		"WORKFLOW_NODE_STATUS_FAILED":      5,
		"WORKFLOW_NODE_STATUS_SKIPPED":     6,
	}
)

func (x WorkflowNodeStatus) Enum() *WorkflowNodeStatus {
	p := new(WorkflowNodeStatus)
	*p = x
	return p
}

func (x WorkflowNodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowNodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_continuation_v1_protocol_proto_enumTypes[3].Descriptor()
}

func (WorkflowNodeStatus) Type() protoreflect.EnumType {
	return &file_continuation_v1_protocol_proto_enumTypes[3]
}

func (x WorkflowNodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowNodeStatus.Descriptor instead.
func (WorkflowNodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{3}
}

// FailureKind is the stable machine-readable failure class attached to gRPC
// status details. It never contains call identities, payloads, or raw errors.
type FailureKind int32

const (
	FailureKind_FAILURE_KIND_UNSPECIFIED     FailureKind = 0
	FailureKind_FAILURE_KIND_GAP             FailureKind = 1
	FailureKind_FAILURE_KIND_CURSOR          FailureKind = 2
	FailureKind_FAILURE_KIND_LEASE           FailureKind = 3
	FailureKind_FAILURE_KIND_SCHEMA          FailureKind = 4
	FailureKind_FAILURE_KIND_AUTHORIZATION   FailureKind = 5
	FailureKind_FAILURE_KIND_TERMINAL        FailureKind = 6
	FailureKind_FAILURE_KIND_CONFLICT        FailureKind = 7
	FailureKind_FAILURE_KIND_NOT_FOUND       FailureKind = 8
	FailureKind_FAILURE_KIND_INVALID_REQUEST FailureKind = 9
	FailureKind_FAILURE_KIND_UNAVAILABLE     FailureKind = 10
	FailureKind_FAILURE_KIND_TIMER           FailureKind = 11
)

// Enum value maps for FailureKind.
var (
	FailureKind_name = map[int32]string{
		0:  "FAILURE_KIND_UNSPECIFIED",
		1:  "FAILURE_KIND_GAP",
		2:  "FAILURE_KIND_CURSOR",
		3:  "FAILURE_KIND_LEASE",
		4:  "FAILURE_KIND_SCHEMA",
		5:  "FAILURE_KIND_AUTHORIZATION",
		6:  "FAILURE_KIND_TERMINAL",
		7:  "FAILURE_KIND_CONFLICT",
		8:  "FAILURE_KIND_NOT_FOUND",
		9:  "FAILURE_KIND_INVALID_REQUEST",
		10: "FAILURE_KIND_UNAVAILABLE",
		11: "FAILURE_KIND_TIMER",
	}
	FailureKind_value = map[string]int32{
		"FAILURE_KIND_UNSPECIFIED":     0,
		"FAILURE_KIND_GAP":             1,
		"FAILURE_KIND_CURSOR":          2,
		"FAILURE_KIND_LEASE":           3,
		"FAILURE_KIND_SCHEMA":          4,
		"FAILURE_KIND_AUTHORIZATION":   5,
		"FAILURE_KIND_TERMINAL":        6,
		"FAILURE_KIND_CONFLICT":        7,
		"FAILURE_KIND_NOT_FOUND":       8,
		"FAILURE_KIND_INVALID_REQUEST": 9,
		"FAILURE_KIND_UNAVAILABLE":     10,
		"FAILURE_KIND_TIMER":           11,
	}
)

func (x FailureKind) Enum() *FailureKind {
	p := new(FailureKind)
	*p = x
	return p
}

func (x FailureKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureKind) Descriptor() protoreflect.EnumDescriptor {
	return file_continuation_v1_protocol_proto_enumTypes[4].Descriptor()
}

func (FailureKind) Type() protoreflect.EnumType {
	return &file_continuation_v1_protocol_proto_enumTypes[4]
}

func (x FailureKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureKind.Descriptor instead.
func (FailureKind) EnumDescriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{4}
}

// FailureDetail is attached to non-OK statuses for deterministic recovery.
type FailureDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              FailureKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=keelith.continuation.v1.FailureKind" json:"kind,omitempty"`
	Retryable         bool                   `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RequestedSequence uint64                 `protobuf:"varint,3,opt,name=requested_sequence,json=requestedSequence,proto3" json:"requested_sequence,omitempty"`
	CurrentSequence   uint64                 `protobuf:"varint,4,opt,name=current_sequence,json=currentSequence,proto3" json:"current_sequence,omitempty"`
	FloorSequence     uint64                 `protobuf:"varint,5,opt,name=floor_sequence,json=floorSequence,proto3" json:"floor_sequence,omitempty"`
	StableReason      string                 `protobuf:"bytes,6,opt,name=stable_reason,json=stableReason,proto3" json:"stable_reason,omitempty"`
	ReadyAt           string                 `protobuf:"bytes,7,opt,name=ready_at,json=readyAt,proto3" json:"ready_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FailureDetail) Reset() {
	*x = FailureDetail{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureDetail) ProtoMessage() {}

func (x *FailureDetail) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureDetail.ProtoReflect.Descriptor instead.
func (*FailureDetail) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *FailureDetail) GetKind() FailureKind {
	if x != nil {
		return x.Kind
	}
	return FailureKind_FAILURE_KIND_UNSPECIFIED
}

func (x *FailureDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *FailureDetail) GetRequestedSequence() uint64 {
	if x != nil {
		return x.RequestedSequence
	}
	return 0
}

func (x *FailureDetail) GetCurrentSequence() uint64 {
	if x != nil {
		return x.CurrentSequence
	}
	return 0
}

func (x *FailureDetail) GetFloorSequence() uint64 {
	if x != nil {
		return x.FloorSequence
	}
	return 0
}

func (x *FailureDetail) GetStableReason() string {
	if x != nil {
		return x.StableReason
	}
	return ""
}

func (x *FailureDetail) GetReadyAt() string {
	if x != nil {
		return x.ReadyAt
	}
	return ""
}

// StartRequest creates one issuer-qualified durable call resource.
type StartRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CallId    string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Operation string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Input     []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// workflow_version selects an exact immutable workflow definition. Empty
	// preserves ordinary continuation Start behavior.
	WorkflowVersion string `protobuf:"bytes,4,opt,name=workflow_version,json=workflowVersion,proto3" json:"workflow_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *StartRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StartRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StartRequest) GetWorkflowVersion() string {
	if x != nil {
		return x.WorkflowVersion
	}
	return ""
}

// PollRequest reads one live page after an exclusive sequence.
type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	After         uint64                 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *PollRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *PollRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *PollRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// AttachRequest follows live pages after an exclusive sequence.
type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	After         uint64                 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *AttachRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *AttachRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *AttachRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SignalRequest submits one idempotent signal payload.
type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *SignalRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SignalRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SignalRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CancelRequest submits one idempotent cancellation command.
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CancelRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// HistoryRequest reads one separately authorized historical page.
type GetHistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallId          string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	After           uint64                 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit           uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludePayload  bool                   `protobuf:"varint,4,opt,name=include_payload,json=includePayload,proto3" json:"include_payload,omitempty"`
	MaxPayloadBytes uint32                 `protobuf:"varint,5,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetHistoryRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHistoryRequest) GetIncludePayload() bool {
	if x != nil {
		return x.IncludePayload
	}
	return false
}

func (x *GetHistoryRequest) GetMaxPayloadBytes() uint32 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

// Snapshot is the payload-free durable call state at one revision.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Status        CallStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=keelith.continuation.v1.CallStatus" json:"status,omitempty"`
	Revision      uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Fence         uint64                 `protobuf:"varint,5,opt,name=fence,proto3" json:"fence,omitempty"`
	Sequence      uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	FrameFloor    uint64                 `protobuf:"varint,7,opt,name=frame_floor,json=frameFloor,proto3" json:"frame_floor,omitempty"`
	Terminal      bool                   `protobuf:"varint,8,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ReadyAt       string                 `protobuf:"bytes,9,opt,name=ready_at,json=readyAt,proto3" json:"ready_at,omitempty"`
	Workflow      *Workflow              `protobuf:"bytes,10,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Snapshot) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Snapshot) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Snapshot) GetStatus() CallStatus {
	if x != nil {
		return x.Status
	}
	return CallStatus_CALL_STATUS_UNSPECIFIED
}

func (x *Snapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *Snapshot) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Snapshot) GetFrameFloor() uint64 {
	if x != nil {
		return x.FrameFloor
	}
	return 0
}

func (x *Snapshot) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *Snapshot) GetReadyAt() string {
	if x != nil {
		return x.ReadyAt
	}
	return ""
}

func (x *Snapshot) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Nodes         []*WorkflowNode        `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *Workflow) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Workflow) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Workflow) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Workflow) GetNodes() []*WorkflowNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type WorkflowNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          WorkflowNodeKind       `protobuf:"varint,2,opt,name=kind,proto3,enum=keelith.continuation.v1.WorkflowNodeKind" json:"kind,omitempty"`
	Status        WorkflowNodeStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=keelith.continuation.v1.WorkflowNodeStatus" json:"status,omitempty"`
	Attempt       uint32                 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ChildCallId   string                 `protobuf:"bytes,5,opt,name=child_call_id,json=childCallId,proto3" json:"child_call_id,omitempty"`
	ReadyAt       string                 `protobuf:"bytes,6,opt,name=ready_at,json=readyAt,proto3" json:"ready_at,omitempty"`
	FailureClass  string                 `protobuf:"bytes,7,opt,name=failure_class,json=failureClass,proto3" json:"failure_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowNode) Reset() {
	*x = WorkflowNode{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowNode) ProtoMessage() {}

func (x *WorkflowNode) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowNode.ProtoReflect.Descriptor instead.
func (*WorkflowNode) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowNode) GetKind() WorkflowNodeKind {
	if x != nil {
		return x.Kind
	}
	return WorkflowNodeKind_WORKFLOW_NODE_KIND_UNSPECIFIED
}

func (x *WorkflowNode) GetStatus() WorkflowNodeStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowNodeStatus_WORKFLOW_NODE_STATUS_UNSPECIFIED
}

func (x *WorkflowNode) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *WorkflowNode) GetChildCallId() string {
	if x != nil {
		return x.ChildCallId
	}
	return ""
}

func (x *WorkflowNode) GetReadyAt() string {
	if x != nil {
		return x.ReadyAt
	}
	return ""
}

func (x *WorkflowNode) GetFailureClass() string {
	if x != nil {
		return x.FailureClass
	}
	return ""
}

// Frame is one immutable, monotonically sequenced observation.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Kind          FrameKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=keelith.continuation.v1.FrameKind" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *Frame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Frame) GetKind() FrameKind {
	if x != nil {
		return x.Kind
	}
	return FrameKind_FRAME_KIND_UNSPECIFIED
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Page is one bounded cursor window and its current payload-free snapshot.
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Frames        []*Frame               `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	NextSequence  uint64                 `protobuf:"varint,3,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	FrameFloor    uint64                 `protobuf:"varint,4,opt,name=frame_floor,json=frameFloor,proto3" json:"frame_floor,omitempty"`
	Terminal      bool                   `protobuf:"varint,5,opt,name=terminal,proto3" json:"terminal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *Page) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Page) GetFrames() []*Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *Page) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *Page) GetFrameFloor() uint64 {
	if x != nil {
		return x.FrameFloor
	}
	return 0
}

func (x *Page) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

// StartResponse returns the durable snapshot and optional terminal output.
type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TerminalFrame *Frame                 `protobuf:"bytes,2,opt,name=terminal_frame,json=terminalFrame,proto3" json:"terminal_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *StartResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *StartResponse) GetTerminalFrame() *Frame {
	if x != nil {
		return x.TerminalFrame
	}
	return nil
}

// PollResponse contains one bounded live page.
type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *PollResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// AttachResponse contains one bounded live page. Servers may split an
// underlying page further to honor the configured per-message byte budget.
type AttachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *AttachResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// SignalResponse returns the snapshot after Signal commits.
type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *SignalResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// CancelResponse returns the snapshot after Cancel commits.
type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *CancelResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// GetHistoryResponse contains one bounded historical page.
type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_continuation_v1_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuation_v1_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_continuation_v1_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *GetHistoryResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_continuation_v1_protocol_proto protoreflect.FileDescriptor

const file_continuation_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1econtinuation/v1/protocol.proto\x12\x17keelith.continuation.v1\"\xa8\x02\n" +
	"\rFailureDetail\x128\n" +
	"\x04kind\x18\x01 \x01(\x0e2$.keelith.continuation.v1.FailureKindR\x04kind\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\x12-\n" +
	"\x12requested_sequence\x18\x03 \x01(\x04R\x11requestedSequence\x12)\n" +
	"\x10current_sequence\x18\x04 \x01(\x04R\x0fcurrentSequence\x12%\n" +
	"\x0efloor_sequence\x18\x05 \x01(\x04R\rfloorSequence\x12#\n" +
	"\rstable_reason\x18\x06 \x01(\tR\fstableReason\x12\x19\n" +
	"\bready_at\x18\a \x01(\tR\areadyAt\"\x86\x01\n" +
	"\fStartRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12)\n" +
	"\x10workflow_version\x18\x04 \x01(\tR\x0fworkflowVersion\"R\n" +
	"\vPollRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"T\n" +
	"\rAttachRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"a\n" +
	"\rSignalRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"G\n" +
	"\rCancelRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\"\xad\x01\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12'\n" +
	"\x0finclude_payload\x18\x04 \x01(\bR\x0eincludePayload\x12*\n" +
	"\x11max_payload_bytes\x18\x05 \x01(\rR\x0fmaxPayloadBytes\"\xe3\x02\n" +
	"\bSnapshot\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.keelith.continuation.v1.CallStatusR\x06status\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x14\n" +
	"\x05fence\x18\x05 \x01(\x04R\x05fence\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x12\x1f\n" +
	"\vframe_floor\x18\a \x01(\x04R\n" +
	"frameFloor\x12\x1a\n" +
	"\bterminal\x18\b \x01(\bR\bterminal\x12\x19\n" +
	"\bready_at\x18\t \x01(\tR\areadyAt\x12=\n" +
	"\bworkflow\x18\n" +
	" \x01(\v2!.keelith.continuation.v1.WorkflowR\bworkflow\"\xa2\x01\n" +
	"\bWorkflow\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12;\n" +
	"\x05nodes\x18\x04 \x03(\v2%.keelith.continuation.v1.WorkflowNodeR\x05nodes\"\xa0\x02\n" +
	"\fWorkflowNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x04kind\x18\x02 \x01(\x0e2).keelith.continuation.v1.WorkflowNodeKindR\x04kind\x12C\n" +
	"\x06status\x18\x03 \x01(\x0e2+.keelith.continuation.v1.WorkflowNodeStatusR\x06status\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\x12\"\n" +
	"\rchild_call_id\x18\x05 \x01(\tR\vchildCallId\x12\x19\n" +
	"\bready_at\x18\x06 \x01(\tR\areadyAt\x12#\n" +
	"\rfailure_class\x18\a \x01(\tR\ffailureClass\"u\n" +
	"\x05Frame\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x126\n" +
	"\x04kind\x18\x02 \x01(\x0e2\".keelith.continuation.v1.FrameKindR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xdf\x01\n" +
	"\x04Page\x12=\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.keelith.continuation.v1.SnapshotR\bsnapshot\x126\n" +
	"\x06frames\x18\x02 \x03(\v2\x1e.keelith.continuation.v1.FrameR\x06frames\x12#\n" +
	"\rnext_sequence\x18\x03 \x01(\x04R\fnextSequence\x12\x1f\n" +
	"\vframe_floor\x18\x04 \x01(\x04R\n" +
	"frameFloor\x12\x1a\n" +
	"\bterminal\x18\x05 \x01(\bR\bterminal\"\x95\x01\n" +
	"\rStartResponse\x12=\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.keelith.continuation.v1.SnapshotR\bsnapshot\x12E\n" +
	"\x0eterminal_frame\x18\x02 \x01(\v2\x1e.keelith.continuation.v1.FrameR\rterminalFrame\"A\n" +
	"\fPollResponse\x121\n" +
	"\x04page\x18\x01 \x01(\v2\x1d.keelith.continuation.v1.PageR\x04page\"C\n" +
	"\x0eAttachResponse\x121\n" +
	"\x04page\x18\x01 \x01(\v2\x1d.keelith.continuation.v1.PageR\x04page\"O\n" +
	"\x0eSignalResponse\x12=\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.keelith.continuation.v1.SnapshotR\bsnapshot\"O\n" +
	"\x0eCancelResponse\x12=\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.keelith.continuation.v1.SnapshotR\bsnapshot\"G\n" +
	"\x12GetHistoryResponse\x121\n" +
	"\x04page\x18\x01 \x01(\v2\x1d.keelith.continuation.v1.PageR\x04page*\x98\x02\n" +
	"\n" +
	"CallStatus\x12\x1b\n" +
	"\x17CALL_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CALL_STATUS_ACCEPTED\x10\x01\x12\x17\n" +
	"\x13CALL_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13CALL_STATUS_WAITING\x10\x03\x12\x19\n" +
	"\x15CALL_STATUS_SUSPENDED\x10\x04\x12 \n" +
	"\x1cCALL_STATUS_CANCEL_REQUESTED\x10\x05\x12\x19\n" +
	"\x15CALL_STATUS_COMPLETED\x10\x06\x12\x16\n" +
	"\x12CALL_STATUS_FAILED\x10\a\x12\x18\n" +
	"\x14CALL_STATUS_CANCELED\x10\b\x12\x17\n" +
	"\x13CALL_STATUS_EXPIRED\x10\t*\xc1\x02\n" +
	"\tFrameKind\x12\x1a\n" +
	"\x16FRAME_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FRAME_KIND_ACCEPTED\x10\x01\x12\x14\n" +
	"\x10FRAME_KIND_EVENT\x10\x02\x12\x16\n" +
	"\x12FRAME_KIND_WAITING\x10\x03\x12\x15\n" +
	"\x11FRAME_KIND_SIGNAL\x10\x04\x12\x18\n" +
	"\x14FRAME_KIND_SUSPENDED\x10\x05\x12\x1f\n" +
	"\x1bFRAME_KIND_CANCEL_REQUESTED\x10\x06\x12\x18\n" +
	"\x14FRAME_KIND_COMPLETED\x10\a\x12\x15\n" +
	"\x11FRAME_KIND_FAILED\x10\b\x12\x17\n" +
	"\x13FRAME_KIND_CANCELED\x10\t\x12\x16\n" +
	"\x12FRAME_KIND_EXPIRED\x10\n" +
	"\x12\x1d\n" +
	"\x19FRAME_KIND_WORKFLOW_CHILD\x10\v*\xaf\x01\n" +
	"\x10WorkflowNodeKind\x12\"\n" +
	"\x1eWORKFLOW_NODE_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aWORKFLOW_NODE_KIND_MACHINE\x10\x01\x12\x1c\n" +
	"\x18WORKFLOW_NODE_KIND_TIMER\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_NODE_KIND_CHILD\x10\x03\x12\x1b\n" +
	"\x17WORKFLOW_NODE_KIND_JOIN\x10\x04*\x87\x02\n" +
	"\x12WorkflowNodeStatus\x12$\n" +
	" WORKFLOW_NODE_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cWORKFLOW_NODE_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cWORKFLOW_NODE_STATUS_RUNNING\x10\x02\x12 \n" +
	"\x1cWORKFLOW_NODE_STATUS_WAITING\x10\x03\x12\"\n" +
	"\x1eWORKFLOW_NODE_STATUS_SUCCEEDED\x10\x04\x12\x1f\n" +
	"\x1bWORKFLOW_NODE_STATUS_FAILED\x10\x05\x12 \n" +
	"\x1cWORKFLOW_NODE_STATUS_SKIPPED\x10\x06*\xd5\x02\n" +
	"\vFailureKind\x12\x1c\n" +
	"\x18FAILURE_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FAILURE_KIND_GAP\x10\x01\x12\x17\n" +
	"\x13FAILURE_KIND_CURSOR\x10\x02\x12\x16\n" +
	"\x12FAILURE_KIND_LEASE\x10\x03\x12\x17\n" +
	"\x13FAILURE_KIND_SCHEMA\x10\x04\x12\x1e\n" +
	"\x1aFAILURE_KIND_AUTHORIZATION\x10\x05\x12\x19\n" +
	"\x15FAILURE_KIND_TERMINAL\x10\x06\x12\x19\n" +
	"\x15FAILURE_KIND_CONFLICT\x10\a\x12\x1a\n" +
	"\x16FAILURE_KIND_NOT_FOUND\x10\b\x12 \n" +
	"\x1cFAILURE_KIND_INVALID_REQUEST\x10\t\x12\x1c\n" +
	"\x18FAILURE_KIND_UNAVAILABLE\x10\n" +
	"\x12\x16\n" +
	"\x12FAILURE_KIND_TIMER\x10\v2\xbc\x04\n" +
	"\x13ContinuationService\x12V\n" +
	"\x05Start\x12%.keelith.continuation.v1.StartRequest\x1a&.keelith.continuation.v1.StartResponse\x12S\n" +
	"\x04Poll\x12$.keelith.continuation.v1.PollRequest\x1a%.keelith.continuation.v1.PollResponse\x12[\n" +
	"\x06Attach\x12&.keelith.continuation.v1.AttachRequest\x1a'.keelith.continuation.v1.AttachResponse0\x01\x12Y\n" +
	"\x06Signal\x12&.keelith.continuation.v1.SignalRequest\x1a'.keelith.continuation.v1.SignalResponse\x12Y\n" +
	"\x06Cancel\x12&.keelith.continuation.v1.CancelRequest\x1a'.keelith.continuation.v1.CancelResponse\x12e\n" +
	"\n" +
	"GetHistory\x12*.keelith.continuation.v1.GetHistoryRequest\x1a+.keelith.continuation.v1.GetHistoryResponseB>Z<github.com/keelab/keelith/api/continuation/v1;continuationv1b\x06proto3"

var (
	file_continuation_v1_protocol_proto_rawDescOnce sync.Once
	file_continuation_v1_protocol_proto_rawDescData []byte
)

func file_continuation_v1_protocol_proto_rawDescGZIP() []byte {
	file_continuation_v1_protocol_proto_rawDescOnce.Do(func() {
		file_continuation_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuation_v1_protocol_proto_rawDesc), len(file_continuation_v1_protocol_proto_rawDesc)))
	})
	return file_continuation_v1_protocol_proto_rawDescData
}

var file_continuation_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_continuation_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_continuation_v1_protocol_proto_goTypes = []any{
	(CallStatus)(0),            // 0: keelith.continuation.v1.CallStatus
	(FrameKind)(0),             // 1: keelith.continuation.v1.FrameKind
	(WorkflowNodeKind)(0),      // 2: keelith.continuation.v1.WorkflowNodeKind
	(WorkflowNodeStatus)(0),    // 3: keelith.continuation.v1.WorkflowNodeStatus
	(FailureKind)(0),           // 4: keelith.continuation.v1.FailureKind
	(*FailureDetail)(nil),      // 5: keelith.continuation.v1.FailureDetail
	(*StartRequest)(nil),       // 6: keelith.continuation.v1.StartRequest
	(*PollRequest)(nil),        // 7: keelith.continuation.v1.PollRequest
	(*AttachRequest)(nil),      // 8: keelith.continuation.v1.AttachRequest
	(*SignalRequest)(nil),      // 9: keelith.continuation.v1.SignalRequest
	(*CancelRequest)(nil),      // 10: keelith.continuation.v1.CancelRequest
	(*GetHistoryRequest)(nil),  // 11: keelith.continuation.v1.GetHistoryRequest
	(*Snapshot)(nil),           // 12: keelith.continuation.v1.Snapshot
	(*Workflow)(nil),           // 13: keelith.continuation.v1.Workflow
	(*WorkflowNode)(nil),       // 14: keelith.continuation.v1.WorkflowNode
	(*Frame)(nil),              // 15: keelith.continuation.v1.Frame
	(*Page)(nil),               // 16: keelith.continuation.v1.Page
	(*StartResponse)(nil),      // 17: keelith.continuation.v1.StartResponse
	(*PollResponse)(nil),       // 18: keelith.continuation.v1.PollResponse
	(*AttachResponse)(nil),     // 19: keelith.continuation.v1.AttachResponse
	(*SignalResponse)(nil),     // 20: keelith.continuation.v1.SignalResponse
	(*CancelResponse)(nil),     // 21: keelith.continuation.v1.CancelResponse
	(*GetHistoryResponse)(nil), // 22: keelith.continuation.v1.GetHistoryResponse
}
var file_continuation_v1_protocol_proto_depIdxs = []int32{
	4,  // 0: keelith.continuation.v1.FailureDetail.kind:type_name -> keelith.continuation.v1.FailureKind
	0,  // 1: keelith.continuation.v1.Snapshot.status:type_name -> keelith.continuation.v1.CallStatus
	13, // 2: keelith.continuation.v1.Snapshot.workflow:type_name -> keelith.continuation.v1.Workflow
	14, // 3: keelith.continuation.v1.Workflow.nodes:type_name -> keelith.continuation.v1.WorkflowNode
	2,  // 4: keelith.continuation.v1.WorkflowNode.kind:type_name -> keelith.continuation.v1.WorkflowNodeKind
	3,  // 5: keelith.continuation.v1.WorkflowNode.status:type_name -> keelith.continuation.v1.WorkflowNodeStatus
	1,  // 6: keelith.continuation.v1.Frame.kind:type_name -> keelith.continuation.v1.FrameKind
	12, // 7: keelith.continuation.v1.Page.snapshot:type_name -> keelith.continuation.v1.Snapshot
	15, // 8: keelith.continuation.v1.Page.frames:type_name -> keelith.continuation.v1.Frame
	12, // 9: keelith.continuation.v1.StartResponse.snapshot:type_name -> keelith.continuation.v1.Snapshot
	15, // 10: keelith.continuation.v1.StartResponse.terminal_frame:type_name -> keelith.continuation.v1.Frame
	16, // 11: keelith.continuation.v1.PollResponse.page:type_name -> keelith.continuation.v1.Page
	16, // 12: keelith.continuation.v1.AttachResponse.page:type_name -> keelith.continuation.v1.Page
	12, // 13: keelith.continuation.v1.SignalResponse.snapshot:type_name -> keelith.continuation.v1.Snapshot
	12, // 14: keelith.continuation.v1.CancelResponse.snapshot:type_name -> keelith.continuation.v1.Snapshot
	16, // 15: keelith.continuation.v1.GetHistoryResponse.page:type_name -> keelith.continuation.v1.Page
	6,  // 16: keelith.continuation.v1.ContinuationService.Start:input_type -> keelith.continuation.v1.StartRequest
	7,  // 17: keelith.continuation.v1.ContinuationService.Poll:input_type -> keelith.continuation.v1.PollRequest
	8,  // 18: keelith.continuation.v1.ContinuationService.Attach:input_type -> keelith.continuation.v1.AttachRequest
	9,  // 19: keelith.continuation.v1.ContinuationService.Signal:input_type -> keelith.continuation.v1.SignalRequest
	10, // 20: keelith.continuation.v1.ContinuationService.Cancel:input_type -> keelith.continuation.v1.CancelRequest
	11, // 21: keelith.continuation.v1.ContinuationService.GetHistory:input_type -> keelith.continuation.v1.GetHistoryRequest
	17, // 22: keelith.continuation.v1.ContinuationService.Start:output_type -> keelith.continuation.v1.StartResponse
	18, // 23: keelith.continuation.v1.ContinuationService.Poll:output_type -> keelith.continuation.v1.PollResponse
	19, // 24: keelith.continuation.v1.ContinuationService.Attach:output_type -> keelith.continuation.v1.AttachResponse
	20, // 25: keelith.continuation.v1.ContinuationService.Signal:output_type -> keelith.continuation.v1.SignalResponse
	21, // 26: keelith.continuation.v1.ContinuationService.Cancel:output_type -> keelith.continuation.v1.CancelResponse
	22, // 27: keelith.continuation.v1.ContinuationService.GetHistory:output_type -> keelith.continuation.v1.GetHistoryResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_continuation_v1_protocol_proto_init() }
func file_continuation_v1_protocol_proto_init() {
	if File_continuation_v1_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuation_v1_protocol_proto_rawDesc), len(file_continuation_v1_protocol_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_continuation_v1_protocol_proto_goTypes,
		DependencyIndexes: file_continuation_v1_protocol_proto_depIdxs,
		EnumInfos:         file_continuation_v1_protocol_proto_enumTypes,
		MessageInfos:      file_continuation_v1_protocol_proto_msgTypes,
	}.Build()
	File_continuation_v1_protocol_proto = out.File
	file_continuation_v1_protocol_proto_goTypes = nil
	file_continuation_v1_protocol_proto_depIdxs = nil
}
