// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: continuation/v1/protocol.proto

package continuationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContinuationService_Start_FullMethodName      = "/keelith.continuation.v1.ContinuationService/Start"
	ContinuationService_Poll_FullMethodName       = "/keelith.continuation.v1.ContinuationService/Poll"
	ContinuationService_Attach_FullMethodName     = "/keelith.continuation.v1.ContinuationService/Attach"
	ContinuationService_Signal_FullMethodName     = "/keelith.continuation.v1.ContinuationService/Signal"
	ContinuationService_Cancel_FullMethodName     = "/keelith.continuation.v1.ContinuationService/Cancel"
	ContinuationService_GetHistory_FullMethodName = "/keelith.continuation.v1.ContinuationService/GetHistory"
)

// ContinuationServiceClient is the client API for ContinuationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContinuationService exposes authenticated, bounded durable calls over gRPC.
type ContinuationServiceClient interface {
	// Start durably creates a call before attempting bounded inline execution.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Poll returns one bounded page after an exclusive frame cursor.
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
	// Attach follows ordered pages until the call terminates or the client leaves.
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachResponse], error)
	// Signal submits one idempotent external command.
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	// Cancel requests cooperative cancellation with an idempotent command.
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// GetHistory reads a separately authorized bounded historical page.
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
}

type continuationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContinuationServiceClient(cc grpc.ClientConnInterface) ContinuationServiceClient {
	return &continuationServiceClient{cc}
}

func (c *continuationServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, ContinuationService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *continuationServiceClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, ContinuationService_Poll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *continuationServiceClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContinuationService_ServiceDesc.Streams[0], ContinuationService_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachRequest, AttachResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContinuationService_AttachClient = grpc.ServerStreamingClient[AttachResponse]

func (c *continuationServiceClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, ContinuationService_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *continuationServiceClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, ContinuationService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *continuationServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, ContinuationService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContinuationServiceServer is the server API for ContinuationService service.
// All implementations must embed UnimplementedContinuationServiceServer
// for forward compatibility.
//
// ContinuationService exposes authenticated, bounded durable calls over gRPC.
type ContinuationServiceServer interface {
	// Start durably creates a call before attempting bounded inline execution.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Poll returns one bounded page after an exclusive frame cursor.
	Poll(context.Context, *PollRequest) (*PollResponse, error)
	// Attach follows ordered pages until the call terminates or the client leaves.
	Attach(*AttachRequest, grpc.ServerStreamingServer[AttachResponse]) error
	// Signal submits one idempotent external command.
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	// Cancel requests cooperative cancellation with an idempotent command.
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// GetHistory reads a separately authorized bounded historical page.
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	mustEmbedUnimplementedContinuationServiceServer()
}

// UnimplementedContinuationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContinuationServiceServer struct{}

func (UnimplementedContinuationServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedContinuationServiceServer) Poll(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedContinuationServiceServer) Attach(*AttachRequest, grpc.ServerStreamingServer[AttachResponse]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedContinuationServiceServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedContinuationServiceServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedContinuationServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedContinuationServiceServer) mustEmbedUnimplementedContinuationServiceServer() {}
func (UnimplementedContinuationServiceServer) testEmbeddedByValue()                             {}

// UnsafeContinuationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContinuationServiceServer will
// result in compilation errors.
type UnsafeContinuationServiceServer interface {
	mustEmbedUnimplementedContinuationServiceServer()
}

func RegisterContinuationServiceServer(s grpc.ServiceRegistrar, srv ContinuationServiceServer) {
	// If the following call panics, it indicates UnimplementedContinuationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContinuationService_ServiceDesc, srv)
}

func _ContinuationService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContinuationServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContinuationService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContinuationServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContinuationService_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContinuationServiceServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContinuationService_Poll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContinuationServiceServer).Poll(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContinuationService_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttachRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContinuationServiceServer).Attach(m, &grpc.GenericServerStream[AttachRequest, AttachResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContinuationService_AttachServer = grpc.ServerStreamingServer[AttachResponse]

func _ContinuationService_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContinuationServiceServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContinuationService_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContinuationServiceServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContinuationService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContinuationServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContinuationService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContinuationServiceServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContinuationService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContinuationServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContinuationService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContinuationServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContinuationService_ServiceDesc is the grpc.ServiceDesc for ContinuationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContinuationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keelith.continuation.v1.ContinuationService",
	HandlerType: (*ContinuationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _ContinuationService_Start_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _ContinuationService_Poll_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _ContinuationService_Signal_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _ContinuationService_Cancel_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _ContinuationService_GetHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _ContinuationService_Attach_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "continuation/v1/protocol.proto",
}
