// Code generated by protoc-gen-go-keelith. DO NOT EDIT.
// source: continuation/v1/protocol.proto

package continuationv1

import (
	context "context"
	fmt "fmt"
	errors "github.com/keelab/keelith/errors"
	idempotency "github.com/keelab/keelith/governance/idempotency"
	service "github.com/keelab/keelith/service"
	http "github.com/keelab/keelith/transport/http"
	grpc "google.golang.org/grpc"
)

const ContinuationServiceKeelithGeneratorProtocol = "v20"

// ContinuationServiceKeelithServer is the transport-neutral implementation contract.
type ContinuationServiceKeelithServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Poll(context.Context, *PollRequest) (*PollResponse, error)
	Attach(*AttachRequest, ContinuationService_AttachKeelithServer) error
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
}

type ContinuationService_AttachKeelithServer interface {
	Context() context.Context
	Send(*AttachResponse) error
}
type continuationServiceAttachServer struct {
	grpc.ServerStream
}

func (stream *continuationServiceAttachServer) Send(message *AttachResponse) error {
	return stream.SendMsg(message)
}

// UnimplementedContinuationServiceKeelithServer provides forward-compatible defaults for application implementations.
type UnimplementedContinuationServiceKeelithServer struct{}

func (*UnimplementedContinuationServiceKeelithServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, errors.New(501, "UNIMPLEMENTED", "keelith.continuation.v1.ContinuationService.Start is not implemented")
}

func (*UnimplementedContinuationServiceKeelithServer) Poll(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, errors.New(501, "UNIMPLEMENTED", "keelith.continuation.v1.ContinuationService.Poll is not implemented")
}

func (*UnimplementedContinuationServiceKeelithServer) Attach(*AttachRequest, ContinuationService_AttachKeelithServer) error {
	return errors.New(501, "UNIMPLEMENTED", "keelith.continuation.v1.ContinuationService.Attach is not implemented")
}

func (*UnimplementedContinuationServiceKeelithServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, errors.New(501, "UNIMPLEMENTED", "keelith.continuation.v1.ContinuationService.Signal is not implemented")
}

func (*UnimplementedContinuationServiceKeelithServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, errors.New(501, "UNIMPLEMENTED", "keelith.continuation.v1.ContinuationService.Cancel is not implemented")
}

func (*UnimplementedContinuationServiceKeelithServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, errors.New(501, "UNIMPLEMENTED", "keelith.continuation.v1.ContinuationService.GetHistory is not implemented")
}

var _ ContinuationServiceKeelithServer = (*UnimplementedContinuationServiceKeelithServer)(nil)

// ContinuationServiceKeelithClient is the typed gRPC client contract.
type ContinuationServiceKeelithClient interface {
	Start(context.Context, *StartRequest, ...grpc.CallOption) (*StartResponse, error)
	Poll(context.Context, *PollRequest, ...grpc.CallOption) (*PollResponse, error)
	Attach(context.Context, *AttachRequest, ...grpc.CallOption) (ContinuationService_AttachKeelithClient, error)
	Signal(context.Context, *SignalRequest, ...grpc.CallOption) (*SignalResponse, error)
	Cancel(context.Context, *CancelRequest, ...grpc.CallOption) (*CancelResponse, error)
	GetHistory(context.Context, *GetHistoryRequest, ...grpc.CallOption) (*GetHistoryResponse, error)
}

type continuationServiceGRPCClient struct {
	connection grpc.ClientConnInterface
}

func NewContinuationServiceGRPCClient(connection grpc.ClientConnInterface) ContinuationServiceKeelithClient {
	return &continuationServiceGRPCClient{connection: connection}
}

func (client *continuationServiceGRPCClient) Start(ctx context.Context, input *StartRequest, options ...grpc.CallOption) (*StartResponse, error) {
	output := new(StartResponse)
	if err := client.connection.Invoke(ctx, "/keelith.continuation.v1.ContinuationService/Start", input, output, options...); err != nil {
		return nil, err
	}
	return output, nil
}

func (client *continuationServiceGRPCClient) Poll(ctx context.Context, input *PollRequest, options ...grpc.CallOption) (*PollResponse, error) {
	output := new(PollResponse)
	if err := client.connection.Invoke(ctx, "/keelith.continuation.v1.ContinuationService/Poll", input, output, options...); err != nil {
		return nil, err
	}
	return output, nil
}

func (client *continuationServiceGRPCClient) Attach(ctx context.Context,
	input *AttachRequest,
	options ...grpc.CallOption) (ContinuationService_AttachKeelithClient, error) {
	stream, err := client.connection.NewStream(ctx, &ContinuationServiceKeelithGRPCServiceDesc.Streams[0], "/keelith.continuation.v1.ContinuationService/Attach", options...)
	if err != nil {
		return nil, err
	}
	result := &continuationServiceAttachClient{ClientStream: stream}
	if err := result.SendMsg(input); err != nil {
		return nil, err
	}
	if err := result.CloseSend(); err != nil {
		return nil, err
	}
	return result, nil
}

func (client *continuationServiceGRPCClient) Signal(ctx context.Context, input *SignalRequest, options ...grpc.CallOption) (*SignalResponse, error) {
	output := new(SignalResponse)
	if err := client.connection.Invoke(ctx, "/keelith.continuation.v1.ContinuationService/Signal", input, output, options...); err != nil {
		return nil, err
	}
	return output, nil
}

func (client *continuationServiceGRPCClient) Cancel(ctx context.Context, input *CancelRequest, options ...grpc.CallOption) (*CancelResponse, error) {
	output := new(CancelResponse)
	if err := client.connection.Invoke(ctx, "/keelith.continuation.v1.ContinuationService/Cancel", input, output, options...); err != nil {
		return nil, err
	}
	return output, nil
}

func (client *continuationServiceGRPCClient) GetHistory(ctx context.Context, input *GetHistoryRequest, options ...grpc.CallOption) (*GetHistoryResponse, error) {
	output := new(GetHistoryResponse)
	if err := client.connection.Invoke(ctx, "/keelith.continuation.v1.ContinuationService/GetHistory", input, output, options...); err != nil {
		return nil, err
	}
	return output, nil
}

// ContinuationServiceGRPCDependency exposes the connection required by a lifecycle-managed dependency.
type ContinuationServiceGRPCDependency interface {
	Service() string
	ClientConn() grpc.ClientConnInterface
}

// NewContinuationServiceManagedGRPCClient binds the generated typed client to a lifecycle-managed dependency.
func NewContinuationServiceManagedGRPCClient(dependency ContinuationServiceGRPCDependency) (ContinuationServiceKeelithClient, error) {
	if dependency == nil {
		return nil, fmt.Errorf("keelith generated gRPC client: managed dependency is nil")
	}
	if dependency.Service() != "keelith.continuation.v1.ContinuationService" {
		return nil, fmt.Errorf("keelith generated gRPC client: dependency service %q does not match %q", dependency.Service(), "keelith.continuation.v1.ContinuationService")
	}
	return NewContinuationServiceGRPCClient(dependency.ClientConn()), nil
}

// RegisterContinuationServiceHTTP binds annotated unary and server-streaming methods to a Keelith router.
func RegisterContinuationServiceHTTP(router *http.Router, service ContinuationServiceKeelithServer) error {
	if router == nil || service == nil {
		return fmt.Errorf("keelith generated HTTP: router or service is nil")
	}
	return nil
}

type ContinuationService_AttachKeelithClient interface {
	grpc.ClientStream
	Recv() (*AttachResponse, error)
}
type continuationServiceAttachClient struct {
	grpc.ClientStream
}

func (stream *continuationServiceAttachClient) Recv() (*AttachResponse, error) {
	message := new(AttachResponse)
	if err := stream.RecvMsg(message); err != nil {
		return nil, err
	}
	return message, nil
}

// RegisterContinuationServiceGRPC registers the generated adapter with grpc-go.
func RegisterContinuationServiceGRPC(registrar grpc.ServiceRegistrar, service ContinuationServiceKeelithServer) {
	registrar.RegisterService(&ContinuationServiceKeelithGRPCServiceDesc, service)
}

func continuationServiceStartGRPCHandler(service any, ctx context.Context, decode func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	input := new(StartRequest)
	if err := decode(input); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return service.(ContinuationServiceKeelithServer).Start(ctx, input)
	}
	info := &grpc.UnaryServerInfo{Server: service, FullMethod: "/keelith.continuation.v1.ContinuationService/Start"}
	handler := func(ctx context.Context, request any) (any, error) {
		return service.(ContinuationServiceKeelithServer).Start(ctx, request.(*StartRequest))
	}
	return interceptor(ctx, input, info, handler)
}

func continuationServicePollGRPCHandler(service any, ctx context.Context, decode func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	input := new(PollRequest)
	if err := decode(input); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return service.(ContinuationServiceKeelithServer).Poll(ctx, input)
	}
	info := &grpc.UnaryServerInfo{Server: service, FullMethod: "/keelith.continuation.v1.ContinuationService/Poll"}
	handler := func(ctx context.Context, request any) (any, error) {
		return service.(ContinuationServiceKeelithServer).Poll(ctx, request.(*PollRequest))
	}
	return interceptor(ctx, input, info, handler)
}

func continuationServiceAttachGRPCStreamHandler(service any, stream grpc.ServerStream) error {
	input := new(AttachRequest)
	if err := stream.RecvMsg(input); err != nil {
		return err
	}
	return service.(ContinuationServiceKeelithServer).Attach(input, &continuationServiceAttachServer{ServerStream: stream})
}

func continuationServiceSignalGRPCHandler(service any, ctx context.Context, decode func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	input := new(SignalRequest)
	if err := decode(input); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return service.(ContinuationServiceKeelithServer).Signal(ctx, input)
	}
	info := &grpc.UnaryServerInfo{Server: service, FullMethod: "/keelith.continuation.v1.ContinuationService/Signal"}
	handler := func(ctx context.Context, request any) (any, error) {
		return service.(ContinuationServiceKeelithServer).Signal(ctx, request.(*SignalRequest))
	}
	return interceptor(ctx, input, info, handler)
}

func continuationServiceCancelGRPCHandler(service any, ctx context.Context, decode func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	input := new(CancelRequest)
	if err := decode(input); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return service.(ContinuationServiceKeelithServer).Cancel(ctx, input)
	}
	info := &grpc.UnaryServerInfo{Server: service, FullMethod: "/keelith.continuation.v1.ContinuationService/Cancel"}
	handler := func(ctx context.Context, request any) (any, error) {
		return service.(ContinuationServiceKeelithServer).Cancel(ctx, request.(*CancelRequest))
	}
	return interceptor(ctx, input, info, handler)
}

func continuationServiceGetHistoryGRPCHandler(service any, ctx context.Context, decode func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	input := new(GetHistoryRequest)
	if err := decode(input); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return service.(ContinuationServiceKeelithServer).GetHistory(ctx, input)
	}
	info := &grpc.UnaryServerInfo{Server: service, FullMethod: "/keelith.continuation.v1.ContinuationService/GetHistory"}
	handler := func(ctx context.Context, request any) (any, error) {
		return service.(ContinuationServiceKeelithServer).GetHistory(ctx, request.(*GetHistoryRequest))
	}
	return interceptor(ctx, input, info, handler)
}

var ContinuationServiceKeelithGRPCServiceDesc = grpc.ServiceDesc{
	ServiceName: "keelith.continuation.v1.ContinuationService",
	HandlerType: (*ContinuationServiceKeelithServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    continuationServiceStartGRPCHandler,
		},
		{
			MethodName: "Poll",
			Handler:    continuationServicePollGRPCHandler,
		},
		{
			MethodName: "Signal",
			Handler:    continuationServiceSignalGRPCHandler,
		},
		{
			MethodName: "Cancel",
			Handler:    continuationServiceCancelGRPCHandler,
		},
		{
			MethodName: "GetHistory",
			Handler:    continuationServiceGetHistoryGRPCHandler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       continuationServiceAttachGRPCStreamHandler,
			ServerStreams: true,
			ClientStreams: false,
		},
	},
	Metadata: "continuation/v1/protocol.proto",
}

// BindContinuationService creates one immutable HTTP/gRPC binding for this generated service.
func BindContinuationService(implementation ContinuationServiceKeelithServer, options ...service.BindingOption) service.Binding {
	return service.NewBinding(service.BindingSpec{
		Name:           "keelith.continuation.v1.ContinuationService",
		Implementation: implementation,
		RegisterGRPC: func(registrar grpc.ServiceRegistrar) error {
			RegisterContinuationServiceGRPC(registrar, implementation)
			return nil
		},
	}, options...)
}

// ContinuationServiceKeelithIdempotencyRegistrations returns generated exact unary rules for every declared transport.
func ContinuationServiceKeelithIdempotencyRegistrations() ([]idempotency.Registration, error) {
	return nil, nil
}
