// Package data generates optional Go data models from SQL DDL.
package data

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

var createTablePattern = regexp.MustCompile(
	"(?is)^\\s*CREATE\\s+TABLE\\s+" +
		"(?:IF\\s+NOT\\s+EXISTS\\s+)?" +
		"((?:`[^`]+`\\.)?(?:`[^`]+`|[A-Za-z_][A-Za-z0-9_]*))" +
		"\\s*\\((.*)\\)\\s*(?:[^)]*)$",
)

// Table is the database-neutral subset used by the optional data profile.
type Table struct {
	Name    string
	Columns []Column
}

// Column describes one scalar SQL column.
type Column struct {
	Name     string
	SQLType  string
	Nullable bool
}

// Parse extracts deterministic table and column metadata from CREATE TABLE DDL.
func Parse(input []byte) ([]Table, error) {
	statements, err := splitSQL(string(input), ';')
	if err != nil {
		return nil, err
	}
	tables := make([]Table, 0)
	seenTables := make(map[string]struct{})
	for _, statement := range statements {
		statement = stripLineComments(statement)
		if strings.TrimSpace(statement) == "" {
			continue
		}
		match := createTablePattern.FindStringSubmatch(statement)
		if len(match) == 0 {
			continue
		}
		name := unquoteIdentifier(match[1])
		if dot := strings.LastIndex(name, "."); dot >= 0 {
			name = unquoteIdentifier(name[dot+1:])
		}
		if _, duplicate := seenTables[name]; duplicate {
			return nil, fmt.Errorf("data generator: duplicate table %q", name)
		}
		seenTables[name] = struct{}{}
		parts, err := splitSQL(match[2], ',')
		if err != nil {
			return nil, fmt.Errorf("data generator: table %s: %w", name, err)
		}
		table := Table{Name: name, Columns: make([]Column, 0, len(parts))}
		seenColumns := make(map[string]struct{})
		for _, part := range parts {
			column, ok, err := parseColumn(part)
			if err != nil {
				return nil, fmt.Errorf("data generator: table %s: %w", name, err)
			}
			if !ok {
				continue
			}
			if _, duplicate := seenColumns[column.Name]; duplicate {
				return nil, fmt.Errorf(
					"data generator: table %s: duplicate column %q",
					name,
					column.Name,
				)
			}
			seenColumns[column.Name] = struct{}{}
			table.Columns = append(table.Columns, column)
		}
		if len(table.Columns) == 0 {
			return nil, fmt.Errorf(
				"data generator: table %s has no supported columns",
				name,
			)
		}
		tables = append(tables, table)
	}
	if len(tables) == 0 {
		return nil, fmt.Errorf("data generator: no CREATE TABLE statements found")
	}
	sort.Slice(tables, func(first, second int) bool {
		return tables[first].Name < tables[second].Name
	})
	return tables, nil
}

// Generate renders formatted Go model declarations without database access.
func Generate(packageName string, input []byte) ([]byte, error) {
	if !token.IsIdentifier(packageName) || token.Lookup(packageName).IsKeyword() {
		return nil, fmt.Errorf(
			"data generator: invalid package name %q",
			packageName,
		)
	}
	tables, err := Parse(input)
	if err != nil {
		return nil, err
	}
	needsTime := false
	type renderedColumn struct {
		column Column
		goType string
	}
	rendered := make(map[string][]renderedColumn, len(tables))
	for _, table := range tables {
		columns := make([]renderedColumn, 0, len(table.Columns))
		for _, column := range table.Columns {
			goType, usesTime, err := mapSQLType(column)
			if err != nil {
				return nil, fmt.Errorf(
					"data generator: table %s column %s: %w",
					table.Name,
					column.Name,
					err,
				)
			}
			needsTime = needsTime || usesTime
			columns = append(columns, renderedColumn{
				column: column,
				goType: goType,
			})
		}
		rendered[table.Name] = columns
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by keelith data. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n", packageName)
	if needsTime {
		output.WriteString("\nimport \"time\"\n")
	}
	for _, table := range tables {
		fmt.Fprintf(&output, "\ntype %s struct {\n", exportedIdentifier(table.Name))
		for _, column := range rendered[table.Name] {
			fmt.Fprintf(
				&output,
				"\t%s %s `db:%q json:%q`\n",
				exportedIdentifier(column.column.Name),
				column.goType,
				column.column.Name,
				column.column.Name,
			)
		}
		output.WriteString("}\n")
		fmt.Fprintf(
			&output,
			"\nfunc (%s) TableName() string { return %q }\n",
			exportedIdentifier(table.Name),
			table.Name,
		)
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("data generator: format output: %w", err)
	}
	return formatted, nil
}

func parseColumn(value string) (Column, bool, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return Column{}, false, nil
	}
	upper := strings.ToUpper(value)
	for _, prefix := range []string{
		"PRIMARY ",
		"UNIQUE ",
		"KEY ",
		"INDEX ",
		"CONSTRAINT ",
		"FOREIGN ",
		"CHECK ",
	} {
		if strings.HasPrefix(upper, prefix) {
			return Column{}, false, nil
		}
	}
	name, rest, err := consumeIdentifier(value)
	if err != nil {
		return Column{}, false, err
	}
	sqlType, _, err := consumeType(rest)
	if err != nil {
		return Column{}, false, fmt.Errorf("column %s: %w", name, err)
	}
	return Column{
		Name:     name,
		SQLType:  sqlType,
		Nullable: !strings.Contains(strings.ToUpper(rest), "NOT NULL"),
	}, true, nil
}

func consumeIdentifier(value string) (string, string, error) {
	if strings.HasPrefix(value, "`") {
		end := strings.Index(value[1:], "`")
		if end < 0 {
			return "", "", fmt.Errorf("unterminated quoted identifier")
		}
		end++
		return value[1:end], strings.TrimSpace(value[end+1:]), nil
	}
	index := strings.IndexFunc(value, unicode.IsSpace)
	if index < 1 {
		return "", "", fmt.Errorf("column declaration %q has no type", value)
	}
	return value[:index], strings.TrimSpace(value[index:]), nil
}

func consumeType(value string) (string, string, error) {
	if value == "" {
		return "", "", fmt.Errorf("SQL type is empty")
	}
	depth := 0
	for index, character := range value {
		switch character {
		case '(':
			depth++
		case ')':
			if depth == 0 {
				return "", "", fmt.Errorf("unbalanced SQL type")
			}
			depth--
		default:
			if unicode.IsSpace(character) && depth == 0 {
				return value[:index], strings.TrimSpace(value[index:]), nil
			}
		}
	}
	if depth != 0 {
		return "", "", fmt.Errorf("unbalanced SQL type")
	}
	return value, "", nil
}

func mapSQLType(column Column) (string, bool, error) {
	sqlType := strings.ToLower(column.SQLType)
	base := sqlType
	if index := strings.IndexByte(base, '('); index >= 0 {
		base = base[:index]
	}
	var goType string
	usesTime := false
	switch base {
	case "tinyint":
		if strings.HasPrefix(sqlType, "tinyint(1)") {
			goType = "bool"
		} else {
			goType = "int64"
		}
	case "smallint", "mediumint", "int", "integer", "bigint":
		goType = "int64"
	case "float", "double", "decimal", "numeric", "real":
		goType = "float64"
	case "bool", "boolean", "bit":
		goType = "bool"
	case "char", "varchar", "text", "tinytext", "mediumtext", "longtext",
		"enum", "set", "uuid":
		goType = "string"
	case "binary", "varbinary", "blob", "tinyblob", "mediumblob", "longblob",
		"json":
		goType = "[]byte"
	case "date", "datetime", "timestamp", "time":
		goType = "time.Time"
		usesTime = true
	default:
		return "", false, fmt.Errorf("unsupported SQL type %q", column.SQLType)
	}
	if column.Nullable && goType != "[]byte" {
		goType = "*" + goType
	}
	return goType, usesTime, nil
}

func splitSQL(value string, separator rune) ([]string, error) {
	parts := make([]string, 0)
	start := 0
	depth := 0
	var quote rune
	escaped := false
	for index, character := range value {
		if quote != 0 {
			if escaped {
				escaped = false
				continue
			}
			if character == '\\' && quote != '`' {
				escaped = true
				continue
			}
			if character == quote {
				quote = 0
			}
			continue
		}
		switch character {
		case '\'', '"', '`':
			quote = character
		case '(':
			depth++
		case ')':
			depth--
			if depth < 0 {
				return nil, fmt.Errorf("data generator: unbalanced parentheses")
			}
		default:
			if character == separator && depth == 0 {
				parts = append(parts, value[start:index])
				start = index + len(string(character))
			}
		}
	}
	if quote != 0 {
		return nil, fmt.Errorf("data generator: unterminated SQL quote")
	}
	if depth != 0 {
		return nil, fmt.Errorf("data generator: unbalanced parentheses")
	}
	parts = append(parts, value[start:])
	return parts, nil
}

func stripLineComments(value string) string {
	lines := strings.Split(value, "\n")
	filtered := lines[:0]
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "--") ||
			strings.HasPrefix(trimmed, "#") {
			continue
		}
		filtered = append(filtered, line)
	}
	return strings.Join(filtered, "\n")
}

func unquoteIdentifier(value string) string {
	parts := strings.Split(value, ".")
	for index, part := range parts {
		parts[index] = strings.Trim(part, "`")
	}
	return strings.Join(parts, ".")
}

func exportedIdentifier(value string) string {
	var result strings.Builder
	upperNext := true
	for _, character := range value {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			upperNext = true
			continue
		}
		if upperNext {
			result.WriteRune(unicode.ToUpper(character))
			upperNext = false
		} else {
			result.WriteRune(character)
		}
	}
	if result.Len() == 0 {
		return "Model"
	}
	return result.String()
}
