package di

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
)

// BootstrapSpec describes a generated, executable typed graph entrypoint.
// Root and Module are Go expressions deliberately supplied by the application;
// Keelith never infers business constructors from package scanning.
type BootstrapSpec struct {
	Package  string
	Function string
	Root     string
	Module   string
	Imports  map[string]string
}

// GenerateBootstrapGo emits a typed Build wrapper. The wrapper is executable,
// checked by the Go compiler, and shares the exact runtime Module contract used
// by Validate and graph tooling.
func GenerateBootstrapGo(spec BootstrapSpec) ([]byte, error) {
	if !validIdentifier(spec.Package) || !validIdentifier(spec.Function) || spec.Root == "" || spec.Module == "" {
		return nil, fmt.Errorf("di: invalid bootstrap specification")
	}
	imports := make([]string, 0, len(spec.Imports)+2)
	imports = append(imports, "\"context\"", "\"github.com/keelab/keelith/di\"")
	aliases := make([]string, 0, len(spec.Imports))
	for alias := range spec.Imports {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	for _, alias := range aliases {
		if !validIdentifier(alias) || spec.Imports[alias] == "" {
			return nil, fmt.Errorf("di: invalid import %q", alias)
		}
		imports = append(imports, alias+" "+strconv.Quote(spec.Imports[alias]))
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by Keelith. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\nimport (\n", spec.Package)
	for _, item := range imports {
		fmt.Fprintf(&output, "\t%s\n", item)
	}
	output.WriteString(")\n\n")
	fmt.Fprintf(&output, "func %s(ctx context.Context) (*di.Graph, %s, error) {\n", spec.Function, spec.Root)
	fmt.Fprintf(&output, "\treturn di.Build[%s](ctx, %s)\n}\n", spec.Root, spec.Module)
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("di: format generated bootstrap: %w", err)
	}
	return formatted, nil
}
