package di

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// GenerateManifestGo emits a deterministic Go file embedding a validated DI
// manifest. The generated artifact is used for drift checks and offline graph
// diagnostics; executable constructor calls remain normal Go and can be
// generated by a project-specific frontend from the same manifest.
func GenerateManifestGo(packageName string, variableName string, description Description) ([]byte, error) {
	if !validIdentifier(packageName) || !validIdentifier(variableName) {
		return nil, fmt.Errorf("di: package and variable must be Go identifiers")
	}
	document, err := MarshalManifest(description)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by Keelith. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	if bytes.ContainsRune(document, '`') {
		fmt.Fprintf(&output, "const %s = %s\n", variableName, strconv.Quote(string(document)))
	} else {
		fmt.Fprintf(&output, "const %s = `\n%s\n`\n", variableName, document)
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("di: format generated manifest: %w", err)
	}
	return formatted, nil
}

func validIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, r := range value {
		if r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || index > 0 && r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return !strings.ContainsAny(value, " \t\r\n")
}
