package scaffold

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/keelab/keelith/contract"
)

const (
	maxBindingManifests = 256
	maxBindingBytes     = 4 * 1024 * 1024
	registrationHeader  = "// Code generated by keelith generate. DO NOT EDIT."
)

// SyncServicesResult describes application implementation and registration
// files synchronized from generated contract manifests.
type SyncServicesResult struct {
	Project      string
	Services     int
	Dependencies int
	Created      []string
	Updated      []string
	Unchanged    []string
}

// LoadWiringServices reads generated contract manifests for the wiring
// compiler without exposing the full contract schema.
func LoadWiringServices(ctx context.Context, project string) ([]WiringService, error) {
	if ctx == nil {
		return nil, fmt.Errorf("%w: context is nil", ErrInvalidInput)
	}
	root, err := resolveComponentProject(project)
	if err != nil {
		return nil, err
	}
	manifests, err := readBindingManifests(ctx, root)
	if err != nil {
		return nil, err
	}
	services := make([]WiringService, 0)
	seenServices := make(map[string]struct{})
	for _, manifest := range manifests {
		listeners := make(map[string]map[string]int)
		for _, listener := range manifest.Listeners {
			transports := listeners[listener.Service]
			if transports == nil {
				transports = make(map[string]int)
				listeners[listener.Service] = transports
			}
			transports[listener.Transport] += len(listener.Routes)
		}
		for _, service := range manifest.Services {
			if _, exists := seenServices[service.Name]; exists {
				return nil, fmt.Errorf("%w: duplicate service %q across generated manifests", ErrConflict, service.Name)
			}
			seenServices[service.Name] = struct{}{}
			transports := make([]string, 0)
			routes := 0
			for transport, count := range listeners[service.Name] {
				transports = append(transports, transport)
				routes += count
			}
			sort.Strings(transports)
			operations := make([]string, 0, len(service.Methods))
			for _, method := range service.Methods {
				operations = append(operations, method.Operation)
			}
			sort.Strings(operations)
			services = append(services, WiringService{Name: service.Name, Operations: operations, Transports: transports, HTTPRoutes: routes})
		}
	}
	sort.Slice(services, func(i, j int) bool { return services[i].Name < services[j].Name })
	return services, nil
}

type serviceBinding struct {
	fullName               string
	goName                 string
	apiImportPath          string
	apiPackage             string
	implementationPath     string
	implementationDir      string
	generateImplementation bool
	dependencyPath         string
	componentPath          string
	hasHTTP                bool
}

type dependencyBinding struct {
	service       string
	transport     string
	apiImportPath string
	apiPackage    string
	goName        string
	accessor      string
	componentName string
}

// SyncServices creates forward-compatible implementation roots for newly
// generated services and rewrites the tool-owned transport registration file.
//
// Application implementation roots are created once and never overwritten.
// The generated registration file is the only Go source this function updates.
func SyncServices(
	ctx context.Context,
	project string,
) (SyncServicesResult, error) {
	if ctx == nil {
		return SyncServicesResult{}, fmt.Errorf(
			"%w: context is nil",
			ErrInvalidInput,
		)
	}
	if cause := context.Cause(ctx); cause != nil {
		return SyncServicesResult{}, cause
	}
	root, err := filepath.Abs(strings.TrimSpace(project))
	if err != nil {
		return SyncServicesResult{}, fmt.Errorf(
			"%w: project path: %w",
			ErrInvalidInput,
			err,
		)
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return SyncServicesResult{}, fmt.Errorf(
			"%w: resolve project symlinks: %w",
			ErrInvalidInput,
			err,
		)
	}
	result := SyncServicesResult{Project: root}
	manifests, err := readBindingManifests(ctx, root)
	if err != nil {
		return SyncServicesResult{}, err
	}
	if len(manifests) == 0 {
		dependencyRelative := "internal/dependency/zz_keelith_clients.gen.go"
		dependencyPath, pathErr := safeAddOutputPath(
			root,
			dependencyRelative,
			true,
		)
		if pathErr != nil {
			return SyncServicesResult{}, pathErr
		}
		existingDependency, dependencyExists, readErr :=
			readManagedRegistration(dependencyPath, dependencyRelative)
		if readErr != nil {
			return SyncServicesResult{}, readErr
		}
		dependencySource, renderErr := renderDependencyClients(nil)
		if renderErr != nil {
			return SyncServicesResult{}, renderErr
		}
		managed, writeErr := writeManagedBindingOutputs([]managedBindingOutput{
			{
				path:     dependencyPath,
				relative: dependencyRelative,
				content:  dependencySource,
				before:   existingDependency,
				exists:   dependencyExists,
			},
		})
		if writeErr != nil {
			return SyncServicesResult{}, writeErr
		}
		result.Created = append(result.Created, managed.created...)
		result.Updated = append(result.Updated, managed.updated...)
		result.Unchanged = append(result.Unchanged, managed.unchanged...)
		return result, nil
	}
	if _, err := contract.NewCatalog(manifests...); err != nil {
		return SyncServicesResult{}, err
	}
	bindings, module, err := serviceBindings(root, manifests)
	if err != nil {
		return SyncServicesResult{}, err
	}
	dependencies, err := dependencyBindings(manifests)
	if err != nil {
		return SyncServicesResult{}, err
	}
	result.Services = len(bindings)
	result.Dependencies = len(dependencies)

	registrationRelative := "internal/service/zz_keelith_register.gen.go"
	registrationPath, err := safeAddOutputPath(
		root,
		registrationRelative,
		true,
	)
	if err != nil {
		return SyncServicesResult{}, err
	}
	existingRegistration, registrationExists, err := readManagedRegistration(
		registrationPath,
		registrationRelative,
	)
	if err != nil {
		return SyncServicesResult{}, err
	}
	registration, err := renderRegistration(module, bindings)
	if err != nil {
		return SyncServicesResult{}, err
	}
	dependencyRelative := "internal/dependency/zz_keelith_clients.gen.go"
	dependencyPath, err := safeAddOutputPath(
		root,
		dependencyRelative,
		true,
	)
	if err != nil {
		return SyncServicesResult{}, err
	}
	existingDependency, dependencyExists, err := readManagedRegistration(
		dependencyPath,
		dependencyRelative,
	)
	if err != nil {
		return SyncServicesResult{}, err
	}
	dependencySource, err := renderDependencyClients(dependencies)
	if err != nil {
		return SyncServicesResult{}, err
	}

	createdPaths := make([]string, 0, len(bindings))
	rollback := func(cause error) (SyncServicesResult, error) {
		rollbackErrors := make([]error, 0, len(createdPaths))
		for index := len(createdPaths) - 1; index >= 0; index-- {
			if removeErr := os.Remove(createdPaths[index]); removeErr != nil &&
				!errors.Is(removeErr, os.ErrNotExist) {
				rollbackErrors = append(rollbackErrors, removeErr)
			}
		}
		return SyncServicesResult{}, errors.Join(
			append([]error{cause}, rollbackErrors...)...,
		)
	}
	for _, binding := range bindings {
		if !binding.generateImplementation {
			continue
		}
		if cause := context.Cause(ctx); cause != nil {
			return rollback(cause)
		}
		relative := filepath.ToSlash(
			filepath.Join(binding.implementationDir, "service.go"),
		)
		output, pathErr := safeAddOutputPath(root, relative, true)
		if pathErr != nil {
			return rollback(pathErr)
		}
		if _, statErr := os.Stat(output); statErr == nil {
			result.Unchanged = append(result.Unchanged, relative)
			continue
		} else if !errors.Is(statErr, os.ErrNotExist) {
			return rollback(fmt.Errorf(
				"scaffold: inspect %s: %w",
				relative,
				statErr,
			))
		}
		content, renderErr := renderImplementation(binding)
		if renderErr != nil {
			return rollback(renderErr)
		}
		if mkdirErr := os.MkdirAll(filepath.Dir(output), 0o755); mkdirErr != nil {
			return rollback(fmt.Errorf(
				"scaffold: create %s directory: %w",
				relative,
				mkdirErr,
			))
		}
		if createErr := createExclusiveFile(output, content); createErr != nil {
			return rollback(fmt.Errorf(
				"%w: create %s: %w",
				ErrConflict,
				relative,
				createErr,
			))
		}
		createdPaths = append(createdPaths, output)
		result.Created = append(result.Created, relative)
	}
	managed, err := writeManagedBindingOutputs([]managedBindingOutput{
		{
			path:     dependencyPath,
			relative: dependencyRelative,
			content:  dependencySource,
			before:   existingDependency,
			exists:   dependencyExists,
		},
		{
			path:     registrationPath,
			relative: registrationRelative,
			content:  registration,
			before:   existingRegistration,
			exists:   registrationExists,
		},
	})
	if err != nil {
		return rollback(err)
	}
	result.Created = append(result.Created, managed.created...)
	result.Updated = append(result.Updated, managed.updated...)
	result.Unchanged = append(result.Unchanged, managed.unchanged...)
	sort.Strings(result.Created)
	sort.Strings(result.Updated)
	sort.Strings(result.Unchanged)
	return result, nil
}

func readBindingManifests(
	ctx context.Context,
	root string,
) ([]contract.Manifest, error) {
	apiRoot := filepath.Join(root, "api")
	info, err := os.Lstat(apiRoot)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	} else if err != nil {
		return nil, fmt.Errorf("scaffold: inspect api directory: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return nil, fmt.Errorf(
			"%w: api is not a regular directory",
			ErrConflict,
		)
	}
	manifests := make([]contract.Manifest, 0)
	err = filepath.WalkDir(apiRoot, func(
		filePath string,
		entry fs.DirEntry,
		walkErr error,
	) error {
		if walkErr != nil {
			return walkErr
		}
		if cause := context.Cause(ctx); cause != nil {
			return cause
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf(
				"%w: generated API tree contains symlink %s",
				ErrConflict,
				filePath,
			)
		}
		if entry.IsDir() ||
			!strings.HasSuffix(entry.Name(), ".keelith.manifest.json") {
			return nil
		}
		if len(manifests) >= maxBindingManifests {
			return fmt.Errorf(
				"%w: generated manifest count exceeds %d",
				ErrConflict,
				maxBindingManifests,
			)
		}
		payload, err := readBoundedFile(filePath, maxBindingBytes)
		if err != nil {
			return err
		}
		manifest, err := contract.Parse(payload)
		if err != nil {
			return fmt.Errorf("scaffold: parse %s: %w", filePath, err)
		}
		manifests = append(manifests, manifest)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("scaffold: scan generated manifests: %w", err)
	}
	return manifests, nil
}

func readBoundedFile(filePath string, maximum int64) ([]byte, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return nil, err
	}
	payload, readErr := io.ReadAll(io.LimitReader(file, maximum+1))
	closeErr := file.Close()
	if err := errors.Join(readErr, closeErr); err != nil {
		return nil, err
	}
	if int64(len(payload)) > maximum {
		return nil, fmt.Errorf(
			"%w: %s exceeds %d bytes",
			ErrConflict,
			filePath,
			maximum,
		)
	}
	return payload, nil
}

func serviceBindings(
	root string,
	manifests []contract.Manifest,
) ([]serviceBinding, string, error) {
	bindings := make([]serviceBinding, 0)
	module := ""
	for _, manifest := range manifests {
		if manifest.GoImportPath == "" || manifest.GoPackage == "" {
			return nil, "", fmt.Errorf(
				"%w: %s has no Go binding metadata; regenerate it",
				ErrConflict,
				manifest.Source,
			)
		}
		currentModule, err := moduleFromManifest(manifest)
		if err != nil {
			return nil, "", err
		}
		if module == "" {
			module = currentModule
		} else if module != currentModule {
			return nil, "", fmt.Errorf(
				"%w: generated manifests span modules %q and %q",
				ErrConflict,
				module,
				currentModule,
			)
		}
		for _, service := range manifest.Services {
			implementationPath := filepath.ToSlash(filepath.Join(
				"internal",
				"service",
				strings.ReplaceAll(manifest.Package, ".", "/"),
				snakeCase(service.GoName),
			))
			// A starter project may already have a hand-written implementation
			// (the service template's Echo implementation is one example). Keep
			// that implementation as the binding owner until a generated service
			// root exists. This lets the aggregate registry evolve without
			// replacing application code during the first `generate` run.
			implementationImport := module + "/" + implementationPath
			if service.Name == "echo.v1.EchoService" {
				generatedPath := filepath.Join(root, filepath.FromSlash(implementationPath), "service.go")
				legacyPath := filepath.Join(root, "internal", "echo", "service.go")
				if _, generatedErr := os.Stat(generatedPath); errors.Is(generatedErr, os.ErrNotExist) {
					if _, legacyErr := os.Stat(legacyPath); legacyErr == nil {
						implementationImport = module + "/internal/echo"
					}
				}
			}
			binding := serviceBinding{
				fullName:               service.Name,
				goName:                 service.GoName,
				apiImportPath:          manifest.GoImportPath,
				apiPackage:             manifest.GoPackage,
				implementationPath:     implementationImport,
				implementationDir:      implementationPath,
				generateImplementation: implementationImport == module+"/"+implementationPath,
				dependencyPath:         module + "/internal/dependency",
				componentPath:          module + "/internal/component",
			}
			for _, method := range service.Methods {
				if method.HTTP != nil {
					binding.hasHTTP = true
					break
				}
			}
			bindings = append(bindings, binding)
		}
	}
	sort.Slice(bindings, func(first, second int) bool {
		return bindings[first].fullName < bindings[second].fullName
	})
	for index := 1; index < len(bindings); index++ {
		if bindings[index-1].implementationDir ==
			bindings[index].implementationDir {
			return nil, "", fmt.Errorf(
				"%w: services %q and %q share implementation path %q",
				ErrConflict,
				bindings[index-1].fullName,
				bindings[index].fullName,
				bindings[index].implementationDir,
			)
		}
	}
	return bindings, module, nil
}

func dependencyBindings(
	manifests []contract.Manifest,
) ([]dependencyBinding, error) {
	byService := make(map[string]dependencyBinding)
	transportByService := make(map[string]string)
	for _, manifest := range manifests {
		for _, dependency := range manifest.Dependencies {
			if dependency.Kind != contract.DependencyDeclared {
				continue
			}
			if dependency.Transport != "grpc" &&
				dependency.Transport != "http" {
				return nil, fmt.Errorf(
					"%w: declared dependency %q uses unsupported transport %q",
					ErrConflict,
					dependency.Service,
					dependency.Transport,
				)
			}
			if transport, exists := transportByService[dependency.Service]; exists && transport != dependency.Transport {
				return nil, fmt.Errorf(
					"%w: declared dependency %q uses multiple transports %q and %q",
					ErrConflict,
					dependency.Service,
					transport,
					dependency.Transport,
				)
			}
			transportByService[dependency.Service] = dependency.Transport
			key := dependency.Transport + "\x00" + dependency.Service
			candidate := dependencyBinding{
				service:       dependency.Service,
				transport:     dependency.Transport,
				apiImportPath: dependency.GoImportPath,
				apiPackage:    dependency.GoPackage,
				goName:        dependency.GoName,
				accessor: exportDependencyAccessor(
					dependency.GoPackage,
					dependency.GoName,
				),
				componentName: "dependency." +
					dependency.Transport + "." +
					dependency.Service,
			}
			if !token.IsIdentifier(candidate.accessor) ||
				token.Lookup(candidate.accessor).IsKeyword() {
				return nil, fmt.Errorf(
					"%w: dependency %q produces invalid accessor %q",
					ErrConflict,
					dependency.Service,
					candidate.accessor,
				)
			}
			if existing, duplicate := byService[key]; duplicate {
				if existing.apiImportPath != candidate.apiImportPath ||
					existing.apiPackage != candidate.apiPackage ||
					existing.goName != candidate.goName {
					return nil, fmt.Errorf(
						"%w: dependency %q has conflicting Go bindings",
						ErrConflict,
						dependency.Service,
					)
				}
				continue
			}
			byService[key] = candidate
		}
	}
	result := make([]dependencyBinding, 0, len(byService))
	for _, binding := range byService {
		result = append(result, binding)
	}
	sort.Slice(result, func(first, second int) bool {
		if result[first].service == result[second].service {
			return result[first].transport < result[second].transport
		}
		return result[first].service < result[second].service
	})
	accessors := make(map[string]string, len(result))
	reservedAccessors := map[string]struct{}{
		"Components":              {},
		"ManagedDependencies":     {},
		"ManagedHTTPDependencies": {},
	}
	for _, binding := range result {
		if _, reserved := reservedAccessors[binding.accessor]; reserved {
			return nil, fmt.Errorf(
				"%w: dependency %q produces reserved accessor %q",
				ErrConflict,
				binding.service,
				binding.accessor,
			)
		}
		if owner, duplicate := accessors[binding.accessor]; duplicate {
			return nil, fmt.Errorf(
				"%w: dependencies %q and %q share accessor %q",
				ErrConflict,
				owner,
				binding.service,
				binding.accessor,
			)
		}
		accessors[binding.accessor] = binding.service
	}
	return result, nil
}

func exportDependencyAccessor(packageName, serviceName string) string {
	value := packageName + "_" + serviceName
	runes := []rune(value)
	if len(runes) == 0 {
		return ""
	}
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func moduleFromManifest(manifest contract.Manifest) (string, error) {
	// Older project generators place generated Go under gen/, while the core
	// module uses api/. Accept both layouts so `keelith generate` remains a
	// safe follow-up to either generated manifest format.
	sourceDirectory := path.Dir(manifest.Source)
	suffixes := []string{"/api", "/gen"}
	if sourceDirectory != "." {
		for index := range suffixes {
			suffixes[index] += "/" + sourceDirectory
		}
	}
	for _, suffix := range suffixes {
		if !strings.HasSuffix(manifest.GoImportPath, suffix) {
			continue
		}
		module := strings.TrimSuffix(manifest.GoImportPath, suffix)
		if err := validateModule(module); err != nil {
			return "", err
		}
		return module, nil
	}
	if manifest.GoImportPath != "" {
		return "", fmt.Errorf(
			"%w: Go import %q does not match source %q",
			ErrConflict,
			manifest.GoImportPath,
			manifest.Source,
		)
	}
	return "", fmt.Errorf(
		"%w: Go import path is empty for source %q",
		ErrConflict,
		manifest.Source,
	)
}

func renderDependencyClients(
	bindings []dependencyBinding,
) ([]byte, error) {
	hasGRPC := false
	hasHTTP := false
	for _, binding := range bindings {
		switch binding.transport {
		case "grpc":
			hasGRPC = true
		case "http":
			hasHTTP = true
		}
	}
	var source strings.Builder
	source.WriteString(registrationHeader)
	source.WriteString("\npackage dependency\n\nimport (\n")
	source.WriteString("\t\"fmt\"\n\n")
	source.WriteString(
		"\t\"github.com/keelab/keelith/app\"\n" +
			"\ttransportgrpc \"github.com/keelab/keelith/transport/grpc\"\n" +
			"\ttransporthttp \"github.com/keelab/keelith/transport/http\"\n",
	)
	for index, binding := range bindings {
		fmt.Fprintf(
			&source,
			"\tapi%d %q\n",
			index,
			binding.apiImportPath,
		)
	}
	source.WriteString(")\n\n")
	source.WriteString(
		"// Clients contains generated typed clients for declared outbound dependencies.\n",
	)
	source.WriteString("type Clients struct {\n")
	for index, binding := range bindings {
		clientSuffix := "KeelithClient"
		if binding.transport == "http" {
			clientSuffix = "KeelithHTTPClient"
		}
		fmt.Fprintf(
			&source,
			"\tclient%d api%d.%s%s\n",
			index,
			index,
			binding.goName,
			clientSuffix,
		)
	}
	source.WriteString("\tmanaged []*transportgrpc.ManagedDependency\n")
	source.WriteString("\tmanagedHTTP []*transporthttp.ManagedDependency\n")
	source.WriteString("\tcomponents []app.Component\n")
	source.WriteString("}\n\n")
	source.WriteString(
		"// NewClients creates lifecycle-managed clients from the contract manifest.\n",
	)
	source.WriteString(
		"func NewClients(grpcFactory *transportgrpc.ManagedDependencyFactory, httpFactories ...*transporthttp.ManagedDependencyFactory) (*Clients, error) {\n",
	)
	source.WriteString(
		"\tif len(httpFactories) > 1 {\n" +
			"\t\treturn nil, fmt.Errorf(\"dependency clients: at most one managed HTTP dependency factory is allowed\")\n" +
			"\t}\n",
	)
	if hasHTTP {
		source.WriteString(
			"\tvar httpFactory *transporthttp.ManagedDependencyFactory\n" +
				"\tif len(httpFactories) == 1 { httpFactory = httpFactories[0] }\n",
		)
	}
	if len(bindings) == 0 {
		source.WriteString("\treturn &Clients{}, nil\n")
	} else {
		if hasGRPC {
			source.WriteString(
				"\tif grpcFactory == nil {\n" +
					"\t\treturn nil, fmt.Errorf(\"dependency clients: managed gRPC dependency factory is nil\")\n" +
					"\t}\n",
			)
		}
		if hasHTTP {
			source.WriteString(
				"\tif httpFactory == nil {\n" +
					"\t\treturn nil, fmt.Errorf(\"dependency clients: managed HTTP dependency factory is nil\")\n" +
					"\t}\n",
			)
		}
		for index, binding := range bindings {
			factory := "grpcFactory"
			constructorSuffix := "ManagedGRPCClient"
			if binding.transport == "http" {
				factory = "httpFactory"
				constructorSuffix = "ManagedHTTPClient"
			}
			fmt.Fprintf(
				&source,
				"\tmanaged%d, err := %s.New(%q, %q)\n",
				index,
				factory,
				binding.componentName,
				binding.service,
			)
			fmt.Fprintf(
				&source,
				"\tif err != nil { return nil, fmt.Errorf(%q, err) }\n",
				"dependency clients: create "+binding.service+": %w",
			)
			fmt.Fprintf(
				&source,
				"\tclient%d, err := api%d.New%s%s(managed%d)\n",
				index,
				index,
				binding.goName,
				constructorSuffix,
				index,
			)
			fmt.Fprintf(
				&source,
				"\tif err != nil { return nil, fmt.Errorf(%q, err) }\n",
				"dependency clients: bind "+binding.service+": %w",
			)
		}
		source.WriteString("\treturn &Clients{\n")
		for index := range bindings {
			fmt.Fprintf(&source, "\t\tclient%d: client%d,\n", index, index)
		}
		source.WriteString("\t\tcomponents: []app.Component{\n")
		for index := range bindings {
			fmt.Fprintf(&source, "\t\t\tmanaged%d,\n", index)
		}
		source.WriteString("\t\t},\n")
		source.WriteString("\t\tmanaged: []*transportgrpc.ManagedDependency{\n")
		for index, binding := range bindings {
			if binding.transport == "grpc" {
				fmt.Fprintf(&source, "\t\t\tmanaged%d,\n", index)
			}
		}
		source.WriteString("\t\t},\n")
		source.WriteString("\t\tmanagedHTTP: []*transporthttp.ManagedDependency{\n")
		for index, binding := range bindings {
			if binding.transport == "http" {
				fmt.Fprintf(&source, "\t\t\tmanaged%d,\n", index)
			}
		}
		source.WriteString("\t\t},\n\t}, nil\n")
	}
	source.WriteString("}\n\n")
	source.WriteString(
		"// Components returns independent App component interfaces in stable order.\n",
	)
	source.WriteString("func (clients *Clients) Components() []app.Component {\n")
	source.WriteString(
		"\tif clients == nil { return nil }\n" +
			"\treturn append([]app.Component(nil), clients.components...)\n" +
			"}\n\n",
	)
	source.WriteString(
		"// ManagedDependencies returns an independent diagnostic component list.\n",
	)
	source.WriteString(
		"func (clients *Clients) ManagedDependencies() []*transportgrpc.ManagedDependency {\n" +
			"\tif clients == nil { return nil }\n" +
			"\treturn append([]*transportgrpc.ManagedDependency(nil), clients.managed...)\n" +
			"}\n\n",
	)
	source.WriteString(
		"// ManagedHTTPDependencies returns an independent HTTP diagnostic component list.\n",
	)
	source.WriteString(
		"func (clients *Clients) ManagedHTTPDependencies() []*transporthttp.ManagedDependency {\n" +
			"\tif clients == nil { return nil }\n" +
			"\treturn append([]*transporthttp.ManagedDependency(nil), clients.managedHTTP...)\n" +
			"}\n\n",
	)
	for index, binding := range bindings {
		clientSuffix := "KeelithClient"
		if binding.transport == "http" {
			clientSuffix = "KeelithHTTPClient"
		}
		fmt.Fprintf(
			&source,
			"// %s returns the typed %s dependency client.\n",
			binding.accessor,
			binding.service,
		)
		fmt.Fprintf(
			&source,
			"func (clients *Clients) %s() api%d.%s%s {\n",
			binding.accessor,
			index,
			binding.goName,
			clientSuffix,
		)
		fmt.Fprintf(
			&source,
			"\tif clients == nil { return nil }\n\treturn clients.client%d\n}\n\n",
			index,
		)
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf(
			"scaffold: format dependency clients: %w",
			err,
		)
	}
	return formatted, nil
}

func renderImplementation(binding serviceBinding) ([]byte, error) {
	source := fmt.Sprintf(`// Package serviceimpl contains the application implementation for %s.
package serviceimpl

import (
	%s %q
	kclient "github.com/keelab/keelith/client"
	"github.com/keelab/keelith/feature"
	appcomponent %q
	appdependency %q
)

// Service is the application-owned implementation root.
//
// Add methods to this type to override the generated unimplemented defaults.
type Service struct {
	%s.Unimplemented%sKeelithServer
	outbound *kclient.Outbound
	features *feature.Store
	components *appcomponent.Resources
	dependencies *appdependency.Clients
}

// New creates the service implementation.
func New() *Service {
	return &Service{}
}

// BindOutbound injects the shared client runtime before servers start.
func (service *Service) BindOutbound(outbound *kclient.Outbound) {
	service.outbound = outbound
}

// Outbound returns the shared client runtime for typed dependency clients.
func (service *Service) Outbound() *kclient.Outbound {
	return service.outbound
}

// BindFeatures injects the shared dynamic feature evaluator before servers start.
func (service *Service) BindFeatures(features *feature.Store) {
	service.features = features
}

// Features returns the shared dynamic feature evaluator.
func (service *Service) Features() *feature.Store {
	return service.features
}

// BindComponents injects generated application resources before servers start.
func (service *Service) BindComponents(components *appcomponent.Resources) {
	service.components = components
}

// Components returns generated application resources.
func (service *Service) Components() *appcomponent.Resources {
	return service.components
}

// BindDependencies injects generated typed clients before servers start.
func (service *Service) BindDependencies(dependencies *appdependency.Clients) {
	service.dependencies = dependencies
}

// Dependencies returns generated typed clients declared by contract methods.
func (service *Service) Dependencies() *appdependency.Clients {
	return service.dependencies
}
`,
		binding.fullName,
		binding.apiPackage,
		binding.apiImportPath,
		binding.componentPath,
		binding.dependencyPath,
		binding.apiPackage,
		binding.goName,
	)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf(
			"scaffold: format implementation for %s: %w",
			binding.fullName,
			err,
		)
	}
	return formatted, nil
}

func renderRegistration(
	module string,
	bindings []serviceBinding,
) ([]byte, error) {
	var source strings.Builder
	source.WriteString(registrationHeader)
	source.WriteString("\npackage service\n\nimport (\n\t\"fmt\"\n\n")
	for index, binding := range bindings {
		fmt.Fprintf(
			&source,
			"\tapi%d %q\n\timplementation%d %q\n",
			index,
			binding.apiImportPath,
			index,
			binding.implementationPath,
		)
	}
	fmt.Fprintf(
		&source,
		"\tappcomponent %q\n\tappdependency %q\n\tkclient %q\n\tfeature %q\n\tidempotency %q\n\tkeelithservice %q\n\ttransporthttp %q\n\t\"google.golang.org/grpc\"\n",
		module+"/internal/component",
		module+"/internal/dependency",
		"github.com/keelab/keelith/client",
		"github.com/keelab/keelith/feature",
		"github.com/keelab/keelith/governance/idempotency",
		"github.com/keelab/keelith/service",
		"github.com/keelab/keelith/transport/http",
	)
	source.WriteString(")\n\n")
	source.WriteString(
		"// RegisterTransports binds all generated service contracts to Keelith servers.\n",
	)
	source.WriteString(
		"func RegisterTransports(router *transporthttp.Router, registrar grpc.ServiceRegistrar, outbound *kclient.Outbound, components *appcomponent.Resources, dependencyClients ...*appdependency.Clients) error {\n",
	)
	source.WriteString(
		"\treturn registerTransports(router, registrar, outbound, components, nil, dependencyClients...)\n" +
			"}\n\n" +
			"// RegisterTransportsWithFeatures binds service contracts and injects the shared feature evaluator.\n" +
			"func RegisterTransportsWithFeatures(router *transporthttp.Router, registrar grpc.ServiceRegistrar, outbound *kclient.Outbound, components *appcomponent.Resources, features *feature.Store, dependencyClients ...*appdependency.Clients) error {\n" +
			"\treturn registerTransports(router, registrar, outbound, components, features, dependencyClients...)\n" +
			"}\n\n" +
			"func registerTransports(router *transporthttp.Router, registrar grpc.ServiceRegistrar, outbound *kclient.Outbound, components *appcomponent.Resources, features *feature.Store, dependencyClients ...*appdependency.Clients) error {\n",
	)
	source.WriteString(
		"\tif router == nil || registrar == nil || outbound == nil || components == nil {\n" +
			"\t\treturn fmt.Errorf(\"register transports: router, registrar, outbound runtime, or components are nil\")\n" +
			"\t}\n" +
			"\tif len(dependencyClients) > 1 {\n" +
			"\t\treturn fmt.Errorf(\"register transports: multiple dependency client sets\")\n" +
			"\t}\n" +
			"\tvar clients *appdependency.Clients\n" +
			"\tif len(dependencyClients) == 1 {\n" +
			"\t\tclients = dependencyClients[0]\n" +
			"} else {\n" +
			"\t\tvar err error\n" +
			"\t\tclients, err = appdependency.NewClients(nil)\n" +
			"\t\tif err != nil { return err }\n" +
			"\t}\n" +
			"\tif clients == nil { return fmt.Errorf(\"register transports: dependency clients are nil\") }\n",
	)
	for index, binding := range bindings {
		fmt.Fprintf(
			&source,
			"\tservice%d := implementation%d.New()\n",
			index,
			index,
		)
		fmt.Fprintf(
			&source,
			"\tif binder, ok := any(service%d).(interface{ BindOutbound(*kclient.Outbound) }); ok {\n"+
				"\t\tbinder.BindOutbound(outbound)\n"+
				"\t}\n",
			index,
		)
		fmt.Fprintf(
			&source,
			"\tif binder, ok := any(service%d).(interface{ BindFeatures(*feature.Store) }); ok {\n"+
				"\t\tbinder.BindFeatures(features)\n"+
				"\t}\n",
			index,
		)
		fmt.Fprintf(
			&source,
			"\tif binder, ok := any(service%d).(interface{ BindComponents(*appcomponent.Resources) }); ok {\n"+
				"\t\tbinder.BindComponents(components)\n"+
				"\t}\n",
			index,
		)
		fmt.Fprintf(
			&source,
			"\tif binder, ok := any(service%d).(interface{ BindDependencies(*appdependency.Clients) }); ok {\n"+
				"\t\tbinder.BindDependencies(clients)\n"+
				"\t}\n",
			index,
		)
		if binding.hasHTTP {
			fmt.Fprintf(
				&source,
				"\tif err := api%d.Register%sHTTP(router, service%d); err != nil {\n"+
					"\t\treturn fmt.Errorf(\"register %s HTTP: %%w\", err)\n"+
					"\t}\n",
				index,
				binding.goName,
				index,
				binding.fullName,
			)
		}
		fmt.Fprintf(
			&source,
			"\tapi%d.Register%sGRPC(registrar, service%d)\n",
			index,
			binding.goName,
			index,
		)
	}
	source.WriteString("\treturn nil\n}\n")
	source.WriteString(
		"\n// Bindings creates the complete static service binding set for this project.\n" +
			"// Implementations remain application-owned; no package-level registration is used.\n" +
			"func Bindings() []keelithservice.Binding {\n\treturn []keelithservice.Binding{\n",
	)
	for index, binding := range bindings {
		fmt.Fprintf(
			&source,
			"\t\tapi%d.Bind%s(implementation%d.New()),\n",
			index,
			binding.goName,
			index,
		)
	}
	source.WriteString("\t}\n}\n")
	source.WriteString(
		"\n// NewProfile builds the default profile from the generated bindings.\n" +
			"func NewProfile(name string) (*keelithservice.Profile, error) {\n" +
			"\treturn keelithservice.NewProfileFromBindings(name, Bindings()...)\n" +
			"}\n",
	)
	source.WriteString(
		"\n// IdempotencyRegistrations returns all generated unary request rules.\n" +
			"func IdempotencyRegistrations() ([]idempotency.Registration, error) {\n" +
			"\tregistrations := make([]idempotency.Registration, 0)\n",
	)
	for index, binding := range bindings {
		fmt.Fprintf(
			&source,
			"\tservice%dRegistrations, err := api%d.%sKeelithIdempotencyRegistrations()\n"+
				"\tif err != nil { return nil, fmt.Errorf(%q, err) }\n"+
				"\tregistrations = append(registrations, service%dRegistrations...)\n",
			index,
			index,
			binding.goName,
			"register idempotency for "+binding.fullName+": %w",
			index,
		)
	}
	source.WriteString("\treturn registrations, nil\n}\n")
	source.WriteString(
		"\n// ServiceNames returns the complete generated service contract names.\n",
	)
	source.WriteString("func ServiceNames() []string {\n\treturn []string{\n")
	for _, binding := range bindings {
		fmt.Fprintf(&source, "\t\t%q,\n", binding.fullName)
	}
	source.WriteString("\t}\n}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("scaffold: format service registration: %w", err)
	}
	if !strings.Contains(string(formatted), module+"/internal/") {
		return nil, fmt.Errorf(
			"%w: registration has no implementation in module %q",
			ErrConflict,
			module,
		)
	}
	return formatted, nil
}

type managedBindingOutput struct {
	path     string
	relative string
	content  []byte
	before   []byte
	exists   bool
	written  bool
}

type managedBindingResult struct {
	created   []string
	updated   []string
	unchanged []string
}

func writeManagedBindingOutputs(
	outputs []managedBindingOutput,
) (managedBindingResult, error) {
	var result managedBindingResult
	rollback := func(cause error) (managedBindingResult, error) {
		failures := []error{cause}
		for index := len(outputs) - 1; index >= 0; index-- {
			output := outputs[index]
			if !output.written {
				continue
			}
			var err error
			if output.exists {
				err = atomicReplaceAddFile(output.path, output.before)
			} else {
				err = os.Remove(output.path)
				if errors.Is(err, os.ErrNotExist) {
					err = nil
				}
			}
			if err != nil {
				failures = append(
					failures,
					fmt.Errorf(
						"restore %s: %w",
						output.relative,
						err,
					),
				)
			}
		}
		return managedBindingResult{}, errors.Join(failures...)
	}
	for index := range outputs {
		output := &outputs[index]
		if output.exists && bytes.Equal(output.before, output.content) {
			result.unchanged = append(result.unchanged, output.relative)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(output.path), 0o755); err != nil {
			return rollback(fmt.Errorf(
				"scaffold: create %s directory: %w",
				output.relative,
				err,
			))
		}
		if output.exists {
			if err := atomicReplaceAddFile(output.path, output.content); err != nil {
				return rollback(fmt.Errorf(
					"scaffold: update %s: %w",
					output.relative,
					err,
				))
			}
			output.written = true
			result.updated = append(result.updated, output.relative)
			continue
		}
		if err := createExclusiveFile(output.path, output.content); err != nil {
			return rollback(fmt.Errorf(
				"%w: create %s: %w",
				ErrConflict,
				output.relative,
				err,
			))
		}
		output.written = true
		result.created = append(result.created, output.relative)
	}
	return result, nil
}

func readManagedRegistration(
	filePath string,
	relative string,
) ([]byte, bool, error) {
	content, err := os.ReadFile(filePath)
	switch {
	case err == nil:
		if !bytes.HasPrefix(content, []byte(registrationHeader+"\n")) {
			return nil, false, fmt.Errorf(
				"%w: %s is not managed by Keelith",
				ErrConflict,
				relative,
			)
		}
		return content, true, nil
	case errors.Is(err, os.ErrNotExist):
		return nil, false, nil
	default:
		return nil, false, fmt.Errorf(
			"scaffold: read %s: %w",
			relative,
			err,
		)
	}
}
