package scaffold

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"sort"
	"strings"

	"github.com/keelab/keelith/di"
)

const builtinWiringSchema = "keelith.project/v1"

// WiringSpec describes the business facts needed by the built-in wiring compiler.
// It deliberately excludes generated expressions and compiler implementation details.
type WiringSpec struct {
	Schema     string            `json:"schema"`
	Module     string            `json:"module"`
	Name       string            `json:"name"`
	Template   string            `json:"template"`
	Roots      []RootSpec        `json:"roots,omitempty"`
	Providers  []ProviderSpec    `json:"providers,omitempty"`
	Components []WiringComponent `json:"-"`
	Services   []WiringService   `json:"-"`
}

// RootSpec names an application entrypoint that consumes the shared graph.
// Kind is descriptive (for example http or worker); Provider is an optional
// constructor symbol registered through the same provider declaration model.
type RootSpec struct {
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Provider string `json:"provider,omitempty"`
}

// WiringService is a stable service-manifest projection consumed by the
// compiler; it is discovered from generated contract manifests.
type WiringService struct {
	Name       string
	Operations []string
	Transports []string
	HTTPRoutes int
}

// WiringComponent is discovered from a component manifest and never persisted
// in the project declaration. It is fed into the compiler as an input fact.

// ProviderSpec identifies a user-owned constructor without embedding generated
// Go expressions or compiler state in the project declaration.
type ProviderSpec struct {
	Constructor string   `json:"constructor"`
	Name        string   `json:"name,omitempty"`
	As          string   `json:"as,omitempty"`
	Group       string   `json:"group,omitempty"`
	Scope       string   `json:"scope,omitempty"`
	Inputs      []string `json:"inputs,omitempty"`
}

// WiringArtifacts contains deterministic files generated by the built-in compiler.
type WiringArtifacts struct {
	ManifestPath    string
	ApplicationPath string
	Manifest        []byte
	Application     []byte
}

// ResolvedProvider is the compiler's validated constructor projection used by
// the static application generator.
type ResolvedProvider struct {
	Constructor      string
	ImportPath       string
	PackageName      string
	Name             string
	InputTypes       []string
	InputExpressions []string
	OutputType       string
	OutputKey        string
	BindingName      string
	Group            string
	Scope            string
	ReturnsError     bool
	ReturnsCleanup   bool
	Outputs          []ResolvedOutput
}

// ResolvedOutput describes one field binding of a di.Out provider.
type ResolvedOutput struct {
	Field string
	Type  string
	Name  string
	Group string
	Key   string
}

// NewWiringSpec creates the project declaration emitted by service templates.
func NewWiringSpec(module, name, template string) (WiringSpec, error) {
	if strings.TrimSpace(module) == "" || strings.TrimSpace(module) != module {
		return WiringSpec{}, fmt.Errorf("scaffold: wiring module is invalid")
	}
	if strings.TrimSpace(name) == "" || strings.TrimSpace(name) != name {
		return WiringSpec{}, fmt.Errorf("scaffold: wiring name is invalid")
	}
	if !supportedProjectTemplate(template) || template == "minimal" {
		return WiringSpec{}, fmt.Errorf("scaffold: wiring template %q is invalid", template)
	}
	return WiringSpec{
		Schema: builtinWiringSchema, Module: module, Name: name, Template: template,
	}, nil
}

func validateProviderSpecs(providers []ProviderSpec) error {
	seen := make(map[string]struct{}, len(providers))
	for index, provider := range providers {
		constructor := strings.TrimSpace(provider.Constructor)
		if constructor == "" || constructor != provider.Constructor {
			return fmt.Errorf("scaffold: provider %d constructor is invalid", index)
		}
		if _, duplicate := seen[constructor]; duplicate {
			return fmt.Errorf("scaffold: provider %q is duplicated", constructor)
		}
		seen[constructor] = struct{}{}
		for field, value := range map[string]string{
			"name":  provider.Name,
			"as":    provider.As,
			"group": provider.Group,
			"scope": provider.Scope,
		} {
			if strings.TrimSpace(value) != value {
				return fmt.Errorf("scaffold: provider %q %s is not normalized", constructor, field)
			}
		}
		for inputIndex, input := range provider.Inputs {
			if strings.TrimSpace(input) != input || input == "" {
				return fmt.Errorf("scaffold: provider %q input %d is invalid", constructor, inputIndex)
			}
		}
		if provider.Scope != "" && provider.Scope != "application" && provider.Scope != "transient" {
			return fmt.Errorf("scaffold: provider %q has invalid scope %q", constructor, provider.Scope)
		}
	}
	return nil
}

func validateRootSpecs(roots []RootSpec) error {
	seen := make(map[string]struct{}, len(roots))
	functionNames := make(map[string]string, len(roots))
	for index, root := range roots {
		if strings.TrimSpace(root.Name) == "" || strings.TrimSpace(root.Name) != root.Name {
			return fmt.Errorf("scaffold: root %d name is invalid", index)
		}
		if strings.TrimSpace(root.Kind) == "" || strings.TrimSpace(root.Kind) != root.Kind {
			return fmt.Errorf("scaffold: root %q kind is invalid", root.Name)
		}
		if _, exists := seen[root.Name]; exists {
			return fmt.Errorf("scaffold: root %q is duplicated", root.Name)
		}
		seen[root.Name] = struct{}{}
		functionName := "New" + exportedRootName(root.Name) + "Root"
		if previous, exists := functionNames[functionName]; exists {
			return fmt.Errorf("scaffold: roots %q and %q produce duplicate function %q", previous, root.Name, functionName)
		}
		functionNames[functionName] = root.Name
		if strings.TrimSpace(root.Provider) != root.Provider {
			return fmt.Errorf("scaffold: root %q provider is not normalized", root.Name)
		}
	}
	return nil
}

func validateRootProviders(roots []RootSpec, providers []ProviderSpec) error {
	registered := make(map[string]struct{}, len(providers))
	for _, provider := range providers {
		registered[provider.Constructor] = struct{}{}
	}
	for _, root := range roots {
		if root.Provider == "" {
			continue
		}
		if _, exists := registered[root.Provider]; !exists {
			return fmt.Errorf("scaffold: root %q references unregistered provider %q", root.Name, root.Provider)
		}
	}
	return nil
}

// ParseWiringSpec strictly parses a project declaration for the built-in compiler.
func ParseWiringSpec(document []byte) (WiringSpec, error) {
	decoder := json.NewDecoder(bytes.NewReader(document))
	decoder.DisallowUnknownFields()
	var spec WiringSpec
	if err := decoder.Decode(&spec); err != nil {
		return WiringSpec{}, fmt.Errorf("scaffold: parse wiring project: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err != nil {
		if !errors.Is(err, io.EOF) {
			return WiringSpec{}, fmt.Errorf("scaffold: parse wiring project: %w", err)
		}
	} else {
		return WiringSpec{}, fmt.Errorf("scaffold: wiring project contains multiple JSON values")
	}
	if spec.Schema != builtinWiringSchema {
		return WiringSpec{}, fmt.Errorf("scaffold: unsupported wiring project schema %q", spec.Schema)
	}
	validated, err := NewWiringSpec(spec.Module, spec.Name, spec.Template)
	if err != nil {
		return WiringSpec{}, err
	}
	validated.Providers = append([]ProviderSpec(nil), spec.Providers...)
	validated.Roots = append([]RootSpec(nil), spec.Roots...)
	if err := validateRootSpecs(validated.Roots); err != nil {
		return WiringSpec{}, err
	}
	if err := validateProviderSpecs(validated.Providers); err != nil {
		return WiringSpec{}, err
	}
	if err := validateRootProviders(validated.Roots, validated.Providers); err != nil {
		return WiringSpec{}, err
	}
	return validated, nil
}

// MarshalWiringSpec emits the canonical project declaration.
func MarshalWiringSpec(spec WiringSpec) ([]byte, error) {
	validated, err := NewWiringSpec(spec.Module, spec.Name, spec.Template)
	if err != nil {
		return nil, err
	}
	validated.Providers = append([]ProviderSpec(nil), spec.Providers...)
	validated.Roots = append([]RootSpec(nil), spec.Roots...)
	if err := validateRootSpecs(validated.Roots); err != nil {
		return nil, err
	}
	if err := validateProviderSpecs(validated.Providers); err != nil {
		return nil, err
	}
	if err := validateRootProviders(validated.Roots, validated.Providers); err != nil {
		return nil, err
	}
	return json.MarshalIndent(validated, "", "  ")
}

// BuiltinWiringArtifacts generates the application entrypoint and DI manifest.
// It performs no user constructor calls and does not access external systems.
func BuiltinWiringArtifacts(spec WiringSpec) (WiringArtifacts, error) {
	return BuiltinWiringArtifactsWithProviders(spec, nil)
}

// BuiltinWiringArtifactsWithProviders generates artifacts from validated
// constructors without invoking any provider or contacting external systems.
func BuiltinWiringArtifactsWithProviders(spec WiringSpec, providers []ResolvedProvider) (WiringArtifacts, error) {
	validated, err := NewWiringSpec(spec.Module, spec.Name, spec.Template)
	if err != nil {
		return WiringArtifacts{}, err
	}
	validated.Components = append([]WiringComponent(nil), spec.Components...)
	validated.Roots = append([]RootSpec(nil), spec.Roots...)
	validated.Services = append([]WiringService(nil), spec.Services...)
	description := di.Description{Root: "*service.Profile", Generator: "keelith wiring"}
	hasProfileProvider := false
	for _, provider := range providers {
		if provider.OutputType == "*service.Profile" {
			hasProfileProvider = true
			break
		}
	}
	if !hasProfileProvider {
		description.Providers = append(description.Providers, di.ProviderDescription{
			ID: validated.Module + ":builtin/profile", Module: validated.Module,
			Type: "*service.Profile", Scope: "application", State: "registered",
		})
	}
	profileID := validated.Module + ":builtin/profile"
	if hasProfileProvider {
		for _, provider := range providers {
			if provider.OutputType == "*service.Profile" {
				profileID = validated.Module + ":provider/" + provider.Constructor
				break
			}
		}
	}
	for _, component := range validated.Components {
		description.Components = append(description.Components, di.ComponentDescription{Name: component.Name, Kind: component.Kind})
	}
	for _, root := range validated.Roots {
		description.Roots = append(description.Roots, di.RootDescription{Name: root.Name, Kind: root.Kind, Provider: root.Provider})
	}
	for _, service := range validated.Services {
		description.Services = append(description.Services, di.ServiceDescription{Name: service.Name, Operations: append([]string(nil), service.Operations...), Transports: append([]string(nil), service.Transports...), HTTPRoutes: service.HTTPRoutes})
		description.Providers = append(description.Providers, di.ProviderDescription{
			ID:     validated.Module + ":service/" + service.Name,
			Module: validated.Module, Type: "service.Binding", Name: service.Name,
			Scope: "application", State: "registered",
		})
		description.Edges = append(description.Edges, di.EdgeDescription{
			From: profileID, To: validated.Module + ":service/" + service.Name, Type: "service.Binding",
		})
	}
	providerIDs := make(map[string]string, len(providers))
	for _, provider := range providers {
		id := validated.Module + ":provider/" + provider.Constructor
		if len(provider.Outputs) > 0 {
			for _, output := range provider.Outputs {
				outputID := id + "/" + output.Field
				item := di.ProviderDescription{ID: outputID, Module: validated.Module, Type: output.Type, Name: output.Name, Group: output.Group, Scope: providerScope(provider), State: "registered"}
				item.Dependencies = append(item.Dependencies, provider.InputTypes...)
				description.Providers = append(description.Providers, item)
				for _, input := range provider.InputTypes {
					if dependencyID := providerIDs[input]; dependencyID != "" {
						description.Edges = append(description.Edges, di.EdgeDescription{From: outputID, To: dependencyID, Type: input})
					}
				}
				providerIDs[output.Key] = outputID
			}
			continue
		}
		key := provider.OutputKey
		if key == "" {
			key = provider.OutputType
		}
		providerIDs[key] = id
		item := di.ProviderDescription{
			ID: id, Module: validated.Module, Type: provider.OutputType,
			Name: provider.BindingName, Group: provider.Group, Scope: providerScope(provider),
			State: "registered",
		}
		for _, input := range provider.InputTypes {
			item.Dependencies = append(item.Dependencies, input)
			if dependencyID := providerIDs[input]; dependencyID != "" {
				description.Edges = append(description.Edges, di.EdgeDescription{From: id, To: dependencyID, Type: input})
			}
		}
		description.Providers = append(description.Providers, item)
	}
	manifest, err := di.MarshalManifest(description)
	if err != nil {
		return WiringArtifacts{}, fmt.Errorf("scaffold: marshal wiring manifest: %w", err)
	}
	manifest = append(manifest, '\n')
	application, err := renderBuiltinApplication(validated, providers)
	if err != nil {
		return WiringArtifacts{}, err
	}
	return WiringArtifacts{
		ManifestPath:    "dependency-graph.json",
		ApplicationPath: "internal/keelithgen/application.keelith.gen.go",
		Manifest:        manifest,
		Application:     application,
	}, nil
}

func providerScope(provider ResolvedProvider) string {
	if provider.Scope == "" {
		return "application"
	}
	return provider.Scope
}

func generatedValueName(provider ResolvedProvider, index int) string {
	name := provider.Name
	if name == "" {
		name = "provider"
	}
	if index == 0 {
		return name + "Value"
	}
	return fmt.Sprintf("%sValue%d", name, index+1)
}

func renderBuiltinApplication(spec WiringSpec, providers []ResolvedProvider) ([]byte, error) {
	var source strings.Builder
	source.WriteString("// Code generated by Keelith. DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package keelithgen\n\nimport (\n")
	source.WriteString("\t\"context\"\n\t\"fmt\"\n\n")
	usesGeneratedProfile := true
	for _, provider := range providers {
		if provider.OutputType == "*service.Profile" {
			usesGeneratedProfile = false
			break
		}
	}
	usesComponents := len(spec.Components) > 0
	fmt.Fprintf(&source, "\tkeelith %q\n", "github.com/keelab/keelith")
	if usesGeneratedProfile {
		fmt.Fprintf(&source, "\tservicegen %q\n", spec.Module+"/internal/service")
	}
	imports := make(map[string]string)
	if !usesGeneratedProfile {
		for _, provider := range providers {
			if provider.OutputType == "*service.Profile" {
				imports["github.com/keelab/keelith/service"] = "service"
				break
			}
		}
	}
	for _, provider := range providers {
		if provider.ImportPath != spec.Module+"/internal/service" || !usesGeneratedProfile {
			imports[provider.ImportPath] = provider.PackageName
		}
	}
	componentPath := spec.Module + "/internal/component"
	if usesComponents {
		imports[componentPath] = "componentgen"
	}
	paths := make([]string, 0, len(imports))
	for importPath := range imports {
		paths = append(paths, importPath)
	}
	sort.Strings(paths)
	aliases := make(map[string]string, len(paths))
	usedAliases := make(map[string]struct{}, len(paths)+2)
	usedAliases["keelith"] = struct{}{}
	if usesGeneratedProfile {
		usedAliases["servicegen"] = struct{}{}
	}
	if usesComponents {
		usedAliases["componentgen"] = struct{}{}
	}
	for _, importPath := range paths {
		alias := imports[importPath]
		base := alias
		for suffix := 2; ; suffix++ {
			if _, exists := usedAliases[alias]; !exists {
				break
			}
			alias = fmt.Sprintf("%s%d", base, suffix)
		}
		usedAliases[alias] = struct{}{}
		aliases[importPath] = alias
		fmt.Fprintf(&source, "\t%s %q\n", alias, importPath)
	}
	source.WriteString(")\n\n")
	source.WriteString("// NewApplication builds the generated service application.\n")
	source.WriteString("func NewApplication(ctx context.Context, extra ...keelith.Option) (*keelith.Application, error) {\n")
	source.WriteString("\treturn newApplication(ctx, \"\", extra...)\n}\n\n")
	source.WriteString("func newApplication(ctx context.Context, rootName string, extra ...keelith.Option) (application *keelith.Application, err error) {\n")
	values := make(map[string]string, len(providers))
	groupValues := make(map[string][]string)
	components := make([]string, 0)
	servers := make([]string, 0)
	serverRoots := make(map[string][]string)
	profileValue := ""
	cleanupType := "func(context.Context) error"
	fmt.Fprintf(&source, "\tcleanups := make([]%s, 0)\n", cleanupType)
	for _, provider := range providers {
		if provider.ReturnsError {
			source.WriteString("\tvar providerErr error\n")
			break
		}
	}
	for providerIndex, provider := range providers {
		valueName := generatedValueName(provider, providerIndex)
		valueType := generatedTypeName(provider.OutputType, aliases, providers)
		if valueType == "" {
			valueType = "any"
		}
		fmt.Fprintf(&source, "\tvar %s %s\n", valueName, valueType)
		if provider.ReturnsCleanup {
			cleanupName := provider.Name + "Cleanup"
			if providerIndex > 0 {
				cleanupName = fmt.Sprintf("%sCleanup%d", provider.Name, providerIndex+1)
			}
			fmt.Fprintf(&source, "\tvar %s %s\n", cleanupName, cleanupType)
		}
	}
	source.WriteString("\tdefer func() {\n\t\tif err == nil { return }\n\t\tfor index := len(cleanups) - 1; index >= 0; index-- { _ = cleanups[index](context.WithoutCancel(ctx)) }\n\t}()\n")
	for providerIndex, provider := range providers {
		valueName := generatedValueName(provider, providerIndex)
		cleanupName := provider.Name + "Cleanup"
		if providerIndex > 0 {
			cleanupName = fmt.Sprintf("%sCleanup%d", provider.Name, providerIndex+1)
		}
		allowedRoots := providerRootNames(spec.Roots, providers, provider)
		filteredByRoot := false
		if hasRootProviders(spec.Roots) && provider.OutputType != "*service.Profile" {
			// An explicitly selected root owns only its transitive provider
			// closure. Providers that are not reachable from any declared root
			// must not be constructed as a side effect of starting that root.
			// Keep the default profile shared by every root so service bindings
			// and application lifecycle remain available to all entrypoints.
			if len(allowedRoots) == 0 {
				fmt.Fprintf(&source, "\tif rootName != \"\" { goto keelithProvider%dDone }\n", providerIndex)
				filteredByRoot = true
			} else {
				conditions := make([]string, 0, len(allowedRoots))
				for _, root := range allowedRoots {
					conditions = append(conditions, fmt.Sprintf("rootName == %q", root))
				}
				fmt.Fprintf(&source, "\tif rootName != \"\" && !(%s) { goto keelithProvider%dDone }\n", strings.Join(conditions, " || "), providerIndex)
				filteredByRoot = true
			}
		}
		argumentCount := len(provider.InputTypes)
		if len(provider.InputExpressions) > argumentCount {
			argumentCount = len(provider.InputExpressions)
		}
		args := make([]string, argumentCount)
		for i, input := range provider.InputTypes {
			if i < len(provider.InputExpressions) && provider.InputExpressions[i] != "" {
				args[i] = provider.InputExpressions[i]
				continue
			}
			value, ok := values[input]
			if !ok && strings.HasPrefix(input, "[]") {
				items := groupValues[input]
				if len(items) > 0 {
					baseType := strings.TrimPrefix(input, "[]")
					if marker := strings.Index(baseType, "[group="); marker >= 0 {
						baseType = baseType[:marker]
					}
					value = "[]" + baseType + "{" + strings.Join(items, ", ") + "}"
					ok = true
				}
			}
			if !ok {
				return nil, fmt.Errorf("scaffold: provider %s requires unresolved type %s", provider.Constructor, input)
			}
			args[i] = value
		}
		for i, expression := range provider.InputExpressions {
			if i < len(args) && args[i] == "" {
				args[i] = expression
			}
		}
		packageAlias := provider.PackageName
		if alias, ok := aliases[provider.ImportPath]; ok {
			packageAlias = alias
		}
		call := fmt.Sprintf("%s.%s(%s)", packageAlias, provider.Name, strings.Join(args, ", "))
		if len(provider.Outputs) > 0 {
			//nolint:gocritic // the return-shape branches mirror the supported constructor forms.
			if provider.ReturnsCleanup {
				if provider.ReturnsError {
					fmt.Fprintf(&source, "\t%s, %s, providerErr = %s\n", valueName, cleanupName, call)
				} else {
					fmt.Fprintf(&source, "\t%s, %s = %s\n", valueName, cleanupName, call)
				}
				if provider.ReturnsError {
					fmt.Fprintf(&source, "\tif providerErr != nil {\n\t\treturn nil, fmt.Errorf(\"build provider %s: %%w\", providerErr)\n\t}\n", provider.Constructor)
				}
				fmt.Fprintf(&source, "\tcleanups = append(cleanups, %s)\n", cleanupName)
			} else if provider.ReturnsError {
				fmt.Fprintf(&source, "\t%s, providerErr = %s\n", valueName, call)
				fmt.Fprintf(&source, "\tif providerErr != nil {\n\t\treturn nil, fmt.Errorf(\"build provider %s: %%w\", providerErr)\n\t}\n", provider.Constructor)
			} else {
				fmt.Fprintf(&source, "\t%s = %s\n", valueName, call)
			}
			for _, output := range provider.Outputs {
				fieldValue := valueName + "." + output.Field
				fmt.Fprintf(&source, "\t_ = %s\n", fieldValue)
				values[output.Key] = fieldValue
				if output.Type == "*service.Profile" {
					profileValue = fieldValue
				}
				if output.Group != "" {
					groupKey := "[]" + output.Type + "[group=" + output.Group + "]"
					groupValues[groupKey] = append(groupValues[groupKey], fieldValue)
				}
				if strings.HasSuffix(output.Type, "app.Component") {
					components = append(components, fieldValue)
				}
				if strings.HasSuffix(output.Type, "/server.Server") {
					servers = append(servers, fieldValue)
					serverRoots[fieldValue] = rootsForProvider(spec.Roots, provider.Constructor)
				}
			}
			if filteredByRoot {
				fmt.Fprintf(&source, "keelithProvider%dDone:\n", providerIndex)
			}
			continue
		}
		//nolint:gocritic // the return-shape branches mirror the supported constructor forms.
		if provider.ReturnsCleanup {
			if provider.ReturnsError {
				fmt.Fprintf(&source, "\t%s, %s, providerErr = %s\n", valueName, cleanupName, call)
				source.WriteString("\tif providerErr != nil {\n")
				fmt.Fprintf(&source, "\t\treturn nil, fmt.Errorf(\"build provider %s: %%w\", providerErr)\n", provider.Constructor)
				source.WriteString("\t}\n")
				fmt.Fprintf(&source, "\tcleanups = append(cleanups, %s)\n", cleanupName)
			} else {
				fmt.Fprintf(&source, "\t%s, %s = %s\n", valueName, cleanupName, call)
				fmt.Fprintf(&source, "\tcleanups = append(cleanups, %s)\n", cleanupName)
			}
		} else if provider.ReturnsError {
			fmt.Fprintf(&source, "\t%s, providerErr = %s\n", valueName, call)
			source.WriteString("\tif providerErr != nil {\n")
			fmt.Fprintf(&source, "\t\treturn nil, fmt.Errorf(\"build provider %s: %%w\", providerErr)\n", provider.Constructor)
			source.WriteString("\t}\n")
		} else {
			fmt.Fprintf(&source, "\t%s = %s\n", valueName, call)
		}
		fmt.Fprintf(&source, "\t_ = %s\n", valueName)
		key := provider.OutputKey
		if key == "" {
			key = provider.OutputType
		}
		values[key] = valueName
		if provider.OutputType == "*service.Profile" {
			profileValue = valueName
		}
		if provider.Group != "" {
			groupValues["[]"+provider.OutputType+"[group="+provider.Group+"]"] = append(groupValues["[]"+provider.OutputType+"[group="+provider.Group+"]"], valueName)
		}
		if strings.HasSuffix(provider.OutputType, "app.Component") {
			components = append(components, valueName)
		}
		if strings.HasSuffix(provider.OutputType, "/server.Server") {
			servers = append(servers, valueName)
			serverRoots[valueName] = rootsForProvider(spec.Roots, provider.Constructor)
		}
		if filteredByRoot {
			fmt.Fprintf(&source, "keelithProvider%dDone:\n", providerIndex)
		}
	}
	if profileValue != "" {
		fmt.Fprintf(&source, "\tprofile := %s\n", profileValue)
	} else {
		fmt.Fprintf(&source, "\tprofile, err := servicegen.NewProfile(%q)\n", spec.Name)
		source.WriteString("\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"build service profile: %w\", err)\n\t}\n")
	}
	source.WriteString("\toptions := []keelith.Option{\n")
	fmt.Fprintf(&source, "\t\tkeelith.WithName(%q),\n", spec.Name)
	source.WriteString("\t\tkeelith.WithDefaultHTTP(\"127.0.0.1:8080\"),\n")
	source.WriteString("\t\tkeelith.WithDefaultGRPC(\"127.0.0.1:8081\"),\n")
	source.WriteString("\t\tkeelith.WithProfile(profile),\n\t}\n")
	for _, component := range components {
		fmt.Fprintf(&source, "\toptions = append(options, keelith.WithComponent(%s))\n", component)
	}
	for _, server := range servers {
		roots := serverRoots[server]
		if len(roots) == 0 {
			fmt.Fprintf(&source, "\toptions = append(options, keelith.WithServer(%s))\n", server)
			continue
		}
		conditions := make([]string, 0, len(roots))
		for _, root := range roots {
			conditions = append(conditions, fmt.Sprintf("rootName == %q", root))
		}
		fmt.Fprintf(&source, "\tif rootName == \"\" || %s { options = append(options, keelith.WithServer(%s)) }\n", strings.Join(conditions, " || "), server)
	}
	source.WriteString("\tif len(cleanups) > 0 {\n\t\toptions = append(options, keelith.WithCleanup(cleanups...))\n\t\tcleanups = nil\n\t}\n")
	source.WriteString("\toptions = append(options, extra...)\n")
	source.WriteString("\tapplication, err = keelith.New(options...)\n")
	source.WriteString("\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"build application: %w\", err)\n\t}\n")
	source.WriteString("\treturn application, nil\n}\n")
	if usesComponents {
		componentAlias := aliases[componentPath]
		source.WriteString("\n// NewApplicationWithComponents builds the application and transfers component resources to its lifecycle.\n")
		fmt.Fprintf(&source, "func NewApplicationWithComponents(ctx context.Context, dependencies %s.Dependencies, extra ...keelith.Option) (*keelith.Application, error) {\n", componentAlias)
		fmt.Fprintf(&source, "\tbindings, err := %s.NewBindings()\n", componentAlias)
		source.WriteString("\tif err != nil { return nil, fmt.Errorf(\"build component bindings: %w\", err) }\n")
		fmt.Fprintf(&source, "\tresources, err := %s.Build(ctx, bindings, dependencies)\n", componentAlias)
		source.WriteString("\tif err != nil { return nil, fmt.Errorf(\"build component resources: %w\", err) }\n")
		source.WriteString("\toptions := make([]keelith.Option, 0, len(extra)+len(resources.AppComponents())+len(resources.AppServers())+1)\n")
		source.WriteString("\toptions = append(options, keelith.WithCleanup(resources.Shutdown))\n")
		source.WriteString("\tfor _, component := range resources.AppComponents() { options = append(options, keelith.WithComponent(component)) }\n")
		source.WriteString("\tfor _, server := range resources.AppServers() { options = append(options, keelith.WithServer(server)) }\n")
		source.WriteString("\toptions = append(options, extra...)\n")
		source.WriteString("\tapplication, err := NewApplication(ctx, options...)\n")
		source.WriteString("\tif err != nil { return nil, fmt.Errorf(\"build application with components: %w\", err) }\n")
		source.WriteString("\treturn application, nil\n}\n")
	}
	for _, root := range spec.Roots {
		functionName := "New" + exportedRootName(root.Name) + "Root"
		fmt.Fprintf(&source, "\n// %s is the generated entrypoint for the %s root.\n", functionName, root.Name)
		fmt.Fprintf(&source, "func %s(ctx context.Context, extra ...keelith.Option) (*keelith.Application, error) {\n", functionName)
		source.WriteString("\trootOptions := make([]keelith.Option, 0, 2)\n")
		switch root.Kind {
		case "worker", "job", "scheduler":
			source.WriteString("\trootOptions = append(rootOptions, keelith.WithoutDefaultHTTP(), keelith.WithoutDefaultGRPC())\n")
		case "http":
			source.WriteString("\trootOptions = append(rootOptions, keelith.WithoutDefaultGRPC())\n")
		case "grpc":
			source.WriteString("\trootOptions = append(rootOptions, keelith.WithoutDefaultHTTP())\n")
		}
		source.WriteString("\trootOptions = append(rootOptions, extra...)\n")
		fmt.Fprintf(&source, "\treturn newApplication(ctx, %q, rootOptions...)\n}\n", root.Name)
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("scaffold: format generated application: %w", err)
	}
	return formatted, nil
}

func rootsForProvider(roots []RootSpec, constructor string) []string {
	result := make([]string, 0)
	for _, root := range roots {
		if root.Provider == constructor {
			result = append(result, root.Name)
		}
	}
	return result
}

func hasRootProviders(roots []RootSpec) bool {
	for _, root := range roots {
		if root.Provider != "" {
			return true
		}
	}
	return false
}

func providerRootNames(roots []RootSpec, providers []ResolvedProvider, target ResolvedProvider) []string {
	byOutput := make(map[string]ResolvedProvider, len(providers))
	byConstructor := make(map[string]ResolvedProvider, len(providers))
	for _, provider := range providers {
		key := provider.OutputKey
		if key == "" {
			key = provider.OutputType
		}
		byOutput[key] = provider
		for _, output := range provider.Outputs {
			byOutput[output.Key] = provider
		}
		byConstructor[provider.Constructor] = provider
	}
	result := make([]string, 0)
	for _, root := range roots {
		if root.Provider == "" {
			continue
		}
		seen := make(map[string]struct{})
		var visit func(ResolvedProvider)
		visit = func(provider ResolvedProvider) {
			if _, exists := seen[provider.Constructor]; exists {
				return
			}
			seen[provider.Constructor] = struct{}{}
			if provider.Constructor == target.Constructor {
				result = append(result, root.Name)
			}
			for _, input := range provider.InputTypes {
				if strings.HasPrefix(input, "[]") {
					for _, dependency := range providers {
						groupKey := "[]" + dependency.OutputType + "[group=" + dependency.Group + "]"
						if dependency.Group != "" && groupKey == input {
							visit(dependency)
						}
					}
					continue
				}
				if dependency, exists := byOutput[input]; exists {
					visit(dependency)
				}
			}
		}
		if provider, exists := byConstructor[root.Provider]; exists {
			visit(provider)
		}
	}
	return result
}

func exportedRootName(name string) string {
	var builder strings.Builder
	upper := true
	for _, character := range name {
		if character < 'a' || character > 'z' {
			if character >= 'A' && character <= 'Z' {
				builder.WriteRune(character)
				continue
			}
			upper = true
			continue
		}
		if upper {
			character -= 'a' - 'A'
			upper = false
		}
		builder.WriteRune(character)
	}
	if builder.Len() == 0 {
		return "Application"
	}
	return builder.String()
}

func generatedTypeName(typeName string, aliases map[string]string, providers []ResolvedProvider) string {
	// service.Profile is the facade's profile type even when the generated
	// project also has an internal/service package containing the constructor.
	if alias, ok := aliases["github.com/keelab/keelith/service"]; ok {
		typeName = strings.ReplaceAll(typeName, "service.", alias+".")
	}
	for _, provider := range providers {
		alias, ok := aliases[provider.ImportPath]
		if !ok || provider.PackageName == "" || provider.PackageName == alias {
			continue
		}
		typeName = strings.ReplaceAll(typeName, provider.PackageName+".", alias+".")
	}
	return typeName
}
