// Package generator implements Keelith's standard Protobuf code generator.
package generator

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

// ProtocolVersion identifies the generated adapter contract.
const ProtocolVersion = "v20"

var (
	contextPackage       = protogen.GoImportPath("context")
	fmtPackage           = protogen.GoImportPath("fmt")
	ioPackage            = protogen.GoImportPath("io")
	timePackage          = protogen.GoImportPath("time")
	protoPackage         = protogen.GoImportPath("google.golang.org/protobuf/proto")
	grpcPackage          = protogen.GoImportPath("google.golang.org/grpc")
	errorsPackage        = protogen.GoImportPath("github.com/keelab/keelith/errors")
	middlewarePackage    = protogen.GoImportPath("github.com/keelab/keelith/middleware")
	operationPackage     = protogen.GoImportPath("github.com/keelab/keelith/operation")
	servicePackage       = protogen.GoImportPath("github.com/keelab/keelith/service")
	idempotencyPackage   = protogen.GoImportPath("github.com/keelab/keelith/governance/idempotency")
	httpPackage          = protogen.GoImportPath("github.com/keelab/keelith/transport/http")
	ssePackage           = protogen.GoImportPath("github.com/keelab/keelith/transport/sse")
	hertzPackage         = protogen.GoImportPath("github.com/keelab/keelith/x/transport/hertz")
	grpcTransportPackage = protogen.GoImportPath(
		"github.com/keelab/keelith/transport/grpc",
	)
)

// Options controls opt-in generated adapters.
type Options struct {
	ExperimentalHertz bool
}

// SetParameter applies one protoc plugin parameter.
func (options *Options) SetParameter(name, value string) error {
	if options == nil {
		return fmt.Errorf("generator: options are nil")
	}
	switch name {
	case "experimental_hertz":
		enabled, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf(
				"generator: experimental_hertz must be true or false: %w",
				err,
			)
		}
		options.ExperimentalHertz = enabled
		return nil
	default:
		return fmt.Errorf("generator: unknown parameter %q", name)
	}
}

// Generate converts one protoc request into a deterministic response.
func Generate(request *pluginpb.CodeGeneratorRequest) (
	*pluginpb.CodeGeneratorResponse,
	error,
) {
	settings := Options{}
	plugin, err := (protogen.Options{
		ParamFunc: settings.SetParameter,
	}).New(request)
	if err != nil {
		return nil, fmt.Errorf("generator: create plugin: %w", err)
	}
	if err := GeneratePluginWithOptions(plugin, settings); err != nil {
		return nil, err
	}
	return plugin.Response(), nil
}

// GeneratePlugin emits Keelith adapters for every generated service file.
func GeneratePlugin(plugin *protogen.Plugin) error {
	return GeneratePluginWithOptions(plugin, Options{})
}

// GeneratePluginWithOptions emits standard adapters and explicitly enabled
// experimental profiles.
func GeneratePluginWithOptions(
	plugin *protogen.Plugin,
	settings Options,
) error {
	if plugin == nil {
		return fmt.Errorf("generator: plugin is nil")
	}
	plugin.SupportedFeatures = uint64(
		pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL,
	)
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		errorDefinitions, err := collectErrorDefinitions(file)
		if err != nil {
			return fmt.Errorf(
				"generator: file %s: %w",
				file.Desc.Path(),
				err,
			)
		}
		projectionRules, err := fileProjectionRules(file)
		if err != nil {
			return fmt.Errorf(
				"generator: file %s projections: %w",
				file.Desc.Path(),
				err,
			)
		}
		hasProjection := len(projectionRules) > 0
		if len(file.Services) == 0 &&
			len(errorDefinitions) == 0 &&
			!hasProjection {
			continue
		}
		if err := generateFile(
			plugin,
			file,
			errorDefinitions,
			hasProjection,
		); err != nil {
			return err
		}
		if settings.ExperimentalHertz {
			if err := generateHertzFile(plugin, file); err != nil {
				return err
			}
		}
	}
	return nil
}

func generateFile(
	plugin *protogen.Plugin,
	file *protogen.File,
	errorDefinitions []errorDefinition,
	hasProjection bool,
) error {
	output := plugin.NewGeneratedFile(
		file.GeneratedFilenamePrefix+".keelith.gen.go",
		file.GoImportPath,
	)
	output.P("// Code generated by protoc-gen-go-keelith. DO NOT EDIT.")
	output.P("// source: ", file.Desc.Path())
	output.P()
	output.P("package ", file.GoPackageName)
	output.P()
	for _, service := range file.Services {
		if err := generateService(output, file, service); err != nil {
			return fmt.Errorf(
				"generator: service %s: %w",
				service.Desc.FullName(),
				err,
			)
		}
	}
	generateErrorDefinitions(output, errorDefinitions)
	if err := generateProgrammable(output, plugin, file); err != nil {
		return fmt.Errorf(
			"generator: programmable API in %s: %w",
			file.Desc.Path(),
			err,
		)
	}
	if len(file.Services) > 0 {
		if err := generateOpenAPI(plugin, file); err != nil {
			return err
		}
	}
	if len(file.Services) > 0 || hasProjection {
		return generateManifest(plugin, file)
	}
	return nil
}

func generateService(
	output *protogen.GeneratedFile,
	file *protogen.File,
	service *protogen.Service,
) error {
	serverName := service.GoName + "KeelithServer"
	clientName := service.GoName + "KeelithClient"
	output.P(
		"const ",
		service.GoName,
		"KeelithGeneratorProtocol = ",
		fmt.Sprintf("%q", ProtocolVersion),
	)
	output.P()
	generateServerInterface(output, service, serverName)
	generateUnimplementedServer(output, service, serverName)
	generateClientInterface(output, service, clientName)
	generateGRPCClient(output, service, clientName)
	generateManagedGRPCClient(output, service, clientName)
	if err := generateHTTPClient(output, service); err != nil {
		return err
	}
	if err := generateHTTPRegistration(output, service, serverName); err != nil {
		return err
	}
	if err := generateHTTPGateway(output, service, clientName); err != nil {
		return err
	}
	generateGRPCRegistration(output, file, service, serverName)
	if err := generateServiceBinding(output, service, serverName); err != nil {
		return err
	}
	if err := generateIdempotencyRegistrations(output, service); err != nil {
		return err
	}
	for _, method := range service.Methods {
		reason, ok, err := methodErrorReason(method)
		if err != nil {
			return err
		}
		if ok {
			generateErrorHelper(output, service, method, reason)
		}
	}
	return nil
}

func generateServiceBinding(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	serverName string,
) error {
	httpMappings, err := serviceHTTPMappings(service)
	if err != nil {
		return err
	}
	functionName := "Bind" + service.GoName
	output.P(
		"// ", functionName,
		" creates one immutable HTTP/gRPC binding for this generated service.",
	)
	output.P(
		"func ", functionName, "(implementation ", serverName,
		", options ...",
		output.QualifiedGoIdent(servicePackage.Ident("BindingOption")),
		") ", output.QualifiedGoIdent(servicePackage.Ident("Binding")), " {",
	)
	output.P(
		"return ", output.QualifiedGoIdent(servicePackage.Ident("NewBinding")),
		"(", output.QualifiedGoIdent(servicePackage.Ident("BindingSpec")), "{",
	)
	output.P("Name: ", fmt.Sprintf("%q", string(service.Desc.FullName())), ",")
	output.P("Implementation: implementation,")
	if len(httpMappings) > 0 {
		output.P(
			"RegisterHTTP: func(router *",
			output.QualifiedGoIdent(httpPackage.Ident("Router")),
			") error { return Register", service.GoName,
			"HTTP(router, implementation) },",
		)
	}
	output.P(
		"RegisterGRPC: func(registrar ",
		output.QualifiedGoIdent(grpcPackage.Ident("ServiceRegistrar")),
		") error { Register", service.GoName,
		"GRPC(registrar, implementation); return nil },",
	)
	output.P("}, options...)")
	output.P("}")
	output.P()
	return nil
}

func generateIdempotencyRegistrations(
	output *protogen.GeneratedFile,
	service *protogen.Service,
) error {
	type declaredRule struct {
		method     *protogen.Method
		rule       idempotencyRule
		transports []string
	}
	declarations := make([]declaredRule, 0)
	for _, method := range service.Methods {
		rule, enabled, err := methodIdempotencyRule(method)
		if err != nil {
			return err
		}
		if !enabled {
			continue
		}
		transports := []string{"grpc"}
		if _, hasHTTP, err := methodHTTPRule(method); err != nil {
			return err
		} else if hasHTTP {
			transports = append(transports, "http")
		}
		declarations = append(declarations, declaredRule{
			method:     method,
			rule:       rule,
			transports: transports,
		})
	}
	functionName := service.GoName + "KeelithIdempotencyRegistrations"
	output.P(
		"// ", functionName,
		" returns generated exact unary rules for every declared transport.",
	)
	output.P(
		"func ", functionName, "() ([]",
		output.QualifiedGoIdent(idempotencyPackage.Ident("Registration")),
		", error) {",
	)
	if len(declarations) == 0 {
		output.P("return nil, nil")
		output.P("}")
		output.P()
		return nil
	}
	registrationCount := 0
	for _, declaration := range declarations {
		registrationCount += len(declaration.transports)
	}
	output.P(
		"registrations := make([]",
		output.QualifiedGoIdent(idempotencyPackage.Ident("Registration")),
		", 0, ", registrationCount, ")",
	)
	for index, declaration := range declarations {
		requestName := fmt.Sprintf("request%d", index)
		codecName := fmt.Sprintf("codec%d", index)
		output.P(
			requestName, ", err := ",
			output.QualifiedGoIdent(idempotencyPackage.Ident("ProtoRequest")),
			"(", fmt.Sprintf("%q", declaration.rule.MetadataKey), ")",
		)
		output.P(
			"if err != nil { return nil, ",
			output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
			"(", fmt.Sprintf("%q", "idempotency request "+declaration.method.GoName+": %w"),
			", err) }",
		)
		output.P(
			codecName, ", err := ",
			output.QualifiedGoIdent(idempotencyPackage.Ident("NewProtoCodec")),
			"(func() ", output.QualifiedGoIdent(protoPackage.Ident("Message")),
			" { return &", declaration.method.Output.GoIdent, "{} })",
		)
		output.P(
			"if err != nil { return nil, ",
			output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
			"(", fmt.Sprintf("%q", "idempotency codec "+declaration.method.GoName+": %w"),
			", err) }",
		)
		for transportIndex, transport := range declaration.transports {
			operationName := fmt.Sprintf("operation%d_%d", index, transportIndex)
			output.P(
				operationName, ", err := ",
				output.QualifiedGoIdent(operationPackage.Ident("New")),
				"(", fmt.Sprintf("%q", transport), ", ",
				fmt.Sprintf("%q", string(service.Desc.FullName())), ", ",
				fmt.Sprintf("%q", string(declaration.method.Desc.Name())), ", ",
				output.QualifiedGoIdent(operationPackage.Ident("KindUnary")), ")",
			)
			output.P(
				"if err != nil { return nil, ",
				output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
				"(", fmt.Sprintf("%q", "idempotency operation "+declaration.method.GoName+": %w"),
				", err) }",
			)
			output.P(
				"registrations = append(registrations, ",
				output.QualifiedGoIdent(idempotencyPackage.Ident("Registration")), "{",
				"Operation: ", operationName, ", ",
				"Rule: ", output.QualifiedGoIdent(idempotencyPackage.Ident("Rule")), "{",
				"Namespace: ", fmt.Sprintf("%q", declaration.rule.Namespace), ", ",
				"ProcessingTTL: ", declaration.rule.ProcessingTTLSecond, " * ",
				output.QualifiedGoIdent(timePackage.Ident("Second")), ", ",
				"ResultTTL: ", declaration.rule.ResultTTLSecond, " * ",
				output.QualifiedGoIdent(timePackage.Ident("Second")), ", ",
				"Request: ", requestName, ", Codec: ", codecName,
				"}})",
			)
		}
	}
	output.P("return registrations, nil")
	output.P("}")
	output.P()
	return nil
}

func generateUnimplementedServer(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	interfaceName string,
) {
	name := "Unimplemented" + interfaceName
	output.P(
		"// ",
		name,
		" provides forward-compatible defaults for application implementations.",
	)
	output.P("type ", name, " struct{}")
	output.P()
	for _, method := range service.Methods {
		switch {
		case !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			output.P(
				"func (*",
				name,
				") ",
				method.GoName,
				"(",
				output.QualifiedGoIdent(contextPackage.Ident("Context")),
				", *",
				method.Input.GoIdent,
				") (*",
				method.Output.GoIdent,
				", error) {",
			)
			output.P(
				"return nil, ",
				output.QualifiedGoIdent(errorsPackage.Ident("New")),
				"(501, ",
				fmt.Sprintf("%q", "UNIMPLEMENTED"),
				", ",
				fmt.Sprintf(
					"%q",
					string(service.Desc.FullName())+"."+method.GoName+
						" is not implemented",
				),
				")",
			)
		case !method.Desc.IsStreamingClient():
			output.P(
				"func (*",
				name,
				") ",
				method.GoName,
				"(*",
				method.Input.GoIdent,
				", ",
				serverStreamName(service, method),
				") error {",
			)
			output.P(
				"return ",
				output.QualifiedGoIdent(errorsPackage.Ident("New")),
				"(501, ",
				fmt.Sprintf("%q", "UNIMPLEMENTED"),
				", ",
				fmt.Sprintf(
					"%q",
					string(service.Desc.FullName())+"."+method.GoName+
						" is not implemented",
				),
				")",
			)
		default:
			output.P(
				"func (*",
				name,
				") ",
				method.GoName,
				"(",
				serverStreamName(service, method),
				") error {",
			)
			output.P(
				"return ",
				output.QualifiedGoIdent(errorsPackage.Ident("New")),
				"(501, ",
				fmt.Sprintf("%q", "UNIMPLEMENTED"),
				", ",
				fmt.Sprintf(
					"%q",
					string(service.Desc.FullName())+"."+method.GoName+
						" is not implemented",
				),
				")",
			)
		}
		output.P("}")
		output.P()
	}
	output.P("var _ ", interfaceName, " = (*", name, ")(nil)")
	output.P()
}

func generateServerInterface(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	name string,
) {
	output.P("// ", name, " is the transport-neutral implementation contract.")
	output.P("type ", name, " interface {")
	for _, method := range service.Methods {
		switch {
		case !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			output.P(
				method.GoName,
				"(",
				output.QualifiedGoIdent(contextPackage.Ident("Context")),
				", *",
				method.Input.GoIdent,
				") (*",
				method.Output.GoIdent,
				", error)",
			)
		case !method.Desc.IsStreamingClient():
			output.P(
				method.GoName,
				"(*",
				method.Input.GoIdent,
				", ",
				serverStreamName(service, method),
				") error",
			)
		default:
			output.P(
				method.GoName,
				"(",
				serverStreamName(service, method),
				") error",
			)
		}
	}
	output.P("}")
	output.P()
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			generateServerStream(output, service, method)
		}
	}
}

func generateClientInterface(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	name string,
) {
	output.P("// ", name, " is the typed gRPC client contract.")
	output.P("type ", name, " interface {")
	for _, method := range service.Methods {
		output.P(clientMethodSignature(output, service, method))
	}
	output.P("}")
	output.P()
}

func clientMethodSignature(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	method *protogen.Method,
) string {
	contextName := output.QualifiedGoIdent(contextPackage.Ident("Context"))
	callOption := output.QualifiedGoIdent(grpcPackage.Ident("CallOption"))
	switch {
	case !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
		return fmt.Sprintf(
			"%s(%s, *%s, ...%s) (*%s, error)",
			method.GoName,
			contextName,
			output.QualifiedGoIdent(method.Input.GoIdent),
			callOption,
			output.QualifiedGoIdent(method.Output.GoIdent),
		)
	case !method.Desc.IsStreamingClient():
		return fmt.Sprintf(
			"%s(%s, *%s, ...%s) (%s, error)",
			method.GoName,
			contextName,
			output.QualifiedGoIdent(method.Input.GoIdent),
			callOption,
			clientStreamName(service, method),
		)
	default:
		return fmt.Sprintf(
			"%s(%s, ...%s) (%s, error)",
			method.GoName,
			contextName,
			callOption,
			clientStreamName(service, method),
		)
	}
}

func generateGRPCClient(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	interfaceName string,
) {
	implementation := unexported(service.GoName) + "GRPCClient"
	output.P("type ", implementation, " struct {")
	output.P(
		"connection ",
		output.QualifiedGoIdent(grpcPackage.Ident("ClientConnInterface")),
	)
	output.P("}")
	output.P()
	output.P(
		"func New",
		service.GoName,
		"GRPCClient(connection ",
		output.QualifiedGoIdent(grpcPackage.Ident("ClientConnInterface")),
		") ",
		interfaceName,
		" {",
	)
	output.P("return &", implementation, "{connection: connection}")
	output.P("}")
	output.P()
	streamIndex := 0
	for _, method := range service.Methods {
		fullMethod := "/" + string(service.Desc.FullName()) + "/" +
			string(method.Desc.Name())
		if !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
			output.P(
				"func (client *",
				implementation,
				") ",
				method.GoName,
				"(ctx ",
				output.QualifiedGoIdent(contextPackage.Ident("Context")),
				", input *",
				method.Input.GoIdent,
				", options ...",
				output.QualifiedGoIdent(grpcPackage.Ident("CallOption")),
				") (*",
				method.Output.GoIdent,
				", error) {",
			)
			output.P("output := new(", method.Output.GoIdent, ")")
			output.P(
				"if err := client.connection.Invoke(ctx, ",
				fmt.Sprintf("%q", fullMethod),
				", input, output, options...); err != nil {",
			)
			output.P("return nil, err")
			output.P("}")
			output.P("return output, nil")
			output.P("}")
			output.P()
			continue
		}
		generateStreamingClientMethod(
			output,
			service,
			method,
			implementation,
			fullMethod,
			streamIndex,
		)
		streamIndex++
	}
}

func generateManagedGRPCClient(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	interfaceName string,
) {
	constructor := "New" + service.GoName + "ManagedGRPCClient"
	serviceName := string(service.Desc.FullName())
	output.P(
		"// ",
		constructor,
		" binds the generated typed client to a lifecycle-managed dependency.",
	)
	output.P(
		"func ",
		constructor,
		"(dependency *",
		output.QualifiedGoIdent(
			grpcTransportPackage.Ident("ManagedDependency"),
		),
		") (",
		interfaceName,
		", error) {",
	)
	output.P("if dependency == nil {")
	output.P(
		"return nil, ",
		output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
		"(",
		fmt.Sprintf(
			"%q",
			"keelith generated gRPC client: managed dependency is nil",
		),
		")",
	)
	output.P("}")
	output.P(
		"if dependency.Service() != ",
		fmt.Sprintf("%q", serviceName),
		" {",
	)
	output.P(
		"return nil, ",
		output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
		"(",
		fmt.Sprintf(
			"%q",
			"keelith generated gRPC client: dependency service %q does not match %q",
		),
		", dependency.Service(), ",
		fmt.Sprintf("%q", serviceName),
		")",
	)
	output.P("}")
	output.P(
		"return New",
		service.GoName,
		"GRPCClient(dependency.ClientConn()), nil",
	)
	output.P("}")
	output.P()
}

func generateStreamingClientMethod(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	method *protogen.Method,
	implementation string,
	fullMethod string,
	streamIndex int,
) {
	output.P(
		"func (client *",
		implementation,
		") ",
		method.GoName,
		"(ctx ",
		output.QualifiedGoIdent(contextPackage.Ident("Context")),
		",",
	)
	if !method.Desc.IsStreamingClient() {
		output.P("input *", method.Input.GoIdent, ",")
	}
	output.P(
		"options ...",
		output.QualifiedGoIdent(grpcPackage.Ident("CallOption")),
		") (",
		clientStreamName(service, method),
		", error) {",
	)
	output.P(
		"stream, err := client.connection.NewStream(ctx, &",
		service.GoName,
		"KeelithGRPCServiceDesc.Streams[",
		streamIndex,
		"], ",
		fmt.Sprintf("%q", fullMethod),
		", options...)",
	)
	output.P("if err != nil { return nil, err }")
	wrapper := unexported(service.GoName + method.GoName + "Client")
	output.P("result := &", wrapper, "{ClientStream: stream}")
	if !method.Desc.IsStreamingClient() {
		output.P("if err := result.SendMsg(input); err != nil { return nil, err }")
		output.P("if err := result.CloseSend(); err != nil { return nil, err }")
	}
	output.P("return result, nil")
	output.P("}")
	output.P()
}

type mappedHTTPMethod struct {
	method *protogen.Method
	rule   httpRule
	rules  []httpRule
}

func serviceHTTPMappings(
	service *protogen.Service,
) ([]mappedHTTPMethod, error) {
	mapped := make([]mappedHTTPMethod, 0)
	routes := make(map[string]string)
	for _, method := range service.Methods {
		rules, ok, err := methodHTTPRules(method)
		if err != nil {
			return nil, err
		}
		if ok {
			for _, rule := range rules {
				if err := validateHTTPMapping(method, rule); err != nil {
					return nil, err
				}
				key := rule.Method + "\x00" + canonicalHTTPRoutePath(rule.Path)
				if owner, duplicate := routes[key]; duplicate {
					return nil, fmt.Errorf(
						"HTTP route %s %s on %s conflicts with %s",
						rule.Method,
						rule.Path,
						method.Desc.FullName(),
						owner,
					)
				}
				routes[key] = string(method.Desc.FullName())
			}
			mapped = append(mapped, mappedHTTPMethod{
				method: method,
				rule:   rules[0],
				rules:  append([]httpRule(nil), rules...),
			})
		}
	}
	return mapped, nil
}

func validateHTTPMapping(
	method *protogen.Method,
	rule httpRule,
) error {
	switch {
	case method.Desc.IsStreamingClient():
		return fmt.Errorf(
			"HTTP mapping on client-streaming method %s is unsupported",
			method.Desc.FullName(),
		)
	case method.Desc.IsStreamingServer() &&
		(rule.Method != "GET" || rule.Body != ""):
		return fmt.Errorf(
			"HTTP mapping on server-streaming method %s must use GET without a body",
			method.Desc.FullName(),
		)
	default:
	}
	if method.Desc.IsStreamingServer() &&
		httpResponseUsesHTTPBody(method.Output, rule.ResponseBody) {
		return fmt.Errorf(
			"HTTP mapping on server-streaming method %s uses streaming google.api.HttpBody, which is unsupported",
			method.Desc.FullName(),
		)
	}
	if rule.ResponseBody != "" {
		if _, err := httpResponseBodyField(method.Output, rule.ResponseBody); err != nil {
			return fmt.Errorf(
				"HTTP mapping on %s: %w",
				method.Desc.FullName(),
				err,
			)
		}
	}
	pathBindings, err := httpPathBindings(method.Input, rule.Path)
	if err != nil {
		return fmt.Errorf("HTTP mapping on %s: %w", method.Desc.FullName(), err)
	}
	excluded := make(
		[][]protoreflect.FieldDescriptor,
		0,
		len(pathBindings)+1,
	)
	for _, binding := range pathBindings {
		excluded = append(excluded, binding.fields)
	}
	for left := 0; left < len(excluded); left++ {
		for right := left + 1; right < len(excluded); right++ {
			if generatorOneofFieldPathsConflict(excluded[left], excluded[right]) {
				return fmt.Errorf(
					"HTTP mapping on %s binds different members of one oneof in the path",
					method.Desc.FullName(),
				)
			}
		}
	}
	if rule.Body == "*" {
		return nil
	}
	if rule.Body != "" {
		bodyPath, bodyErr := httpBodyFieldPath(method.Input, rule.Body)
		if bodyErr != nil {
			return fmt.Errorf(
				"HTTP mapping on %s: %w",
				method.Desc.FullName(),
				bodyErr,
			)
		}
		for _, pathField := range excluded {
			if generatorFieldPathsOverlap(pathField, bodyPath) {
				return fmt.Errorf(
					"HTTP mapping on %s binds overlapping path and body field %q",
					method.Desc.FullName(),
					rule.Body,
				)
			}
			if generatorOneofFieldPathsConflict(pathField, bodyPath) {
				return fmt.Errorf(
					"HTTP mapping on %s binds path and body fields from one oneof",
					method.Desc.FullName(),
				)
			}
		}
		excluded = append(excluded, bodyPath)
	}
	if _, err := httpQueryFields(method.Input, excluded); err != nil {
		return fmt.Errorf("HTTP mapping on %s: %w", method.Desc.FullName(), err)
	}
	return nil
}

func generatorOneofFieldPathsConflict(
	left []protoreflect.FieldDescriptor,
	right []protoreflect.FieldDescriptor,
) bool {
	if len(left) == 0 || len(left) != len(right) {
		return false
	}
	for index := 0; index < len(left)-1; index++ {
		if left[index].FullName() != right[index].FullName() {
			return false
		}
	}
	leftField := left[len(left)-1]
	rightField := right[len(right)-1]
	if leftField.FullName() == rightField.FullName() {
		return false
	}
	leftOneof := leftField.ContainingOneof()
	rightOneof := rightField.ContainingOneof()
	return leftOneof != nil && rightOneof != nil &&
		!leftOneof.IsSynthetic() && !rightOneof.IsSynthetic() &&
		leftOneof.FullName() == rightOneof.FullName()
}

func generatorFieldPathsOverlap(
	left []protoreflect.FieldDescriptor,
	right []protoreflect.FieldDescriptor,
) bool {
	if len(left) == 0 || len(right) == 0 {
		return false
	}
	limit := len(left)
	if len(right) < limit {
		limit = len(right)
	}
	for index := 0; index < limit; index++ {
		if left[index].FullName() != right[index].FullName() {
			return false
		}
	}
	return true
}

func generateHTTPRegistration(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	serverName string,
) error {
	mapped, err := serviceHTTPMappings(service)
	if err != nil {
		return err
	}
	output.P(
		"// Register",
		service.GoName,
		"HTTP binds annotated unary and server-streaming methods to a Keelith router.",
	)
	output.P(
		"func Register",
		service.GoName,
		"HTTP(router *",
		output.QualifiedGoIdent(httpPackage.Ident("Router")),
		", service ",
		serverName,
		") error {",
	)
	output.P("if router == nil || service == nil {")
	output.P(
		"return ",
		output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
		"(",
		fmt.Sprintf("%q", "keelith generated HTTP: router or service is nil"),
		")",
	)
	output.P("}")
	if hasServerStreamingHTTPMapping(mapped) {
		output.P(
			"sseEncoder, err := ",
			output.QualifiedGoIdent(httpPackage.Ident("NewSSEEncoder")),
			"(",
			output.QualifiedGoIdent(httpPackage.Ident("SSEConfig")),
			"{})",
		)
		output.P("if err != nil { return err }")
	}
	for _, mapping := range mapped {
		method := mapping.method
		operationVariable := unexported(
			service.GoName + method.GoName + "HTTPOperation",
		)
		output.P(
			operationVariable,
			", err := ",
			output.QualifiedGoIdent(operationPackage.Ident("New")),
			"(",
			fmt.Sprintf("%q", "http"),
			", ",
			fmt.Sprintf("%q", string(service.Desc.FullName())),
			", ",
			fmt.Sprintf("%q", string(method.Desc.Name())),
			", ",
			output.QualifiedGoIdent(
				operationPackage.Ident(httpOperationKind(method)),
			),
			")",
		)
		output.P("if err != nil { return err }")
		for _, rule := range mapping.rules {
			decoder, pathBindings, err := protoDecoderExpression(
				output,
				httpPackage,
				method.Input,
				rule,
			)
			if err != nil {
				return err
			}
			registration, route := standardHTTPRegistration(
				rule.Path,
				pathBindings,
			)
			if method.Desc.IsStreamingServer() {
				output.P(
					"if err := router.", registration, "(",
					fmt.Sprintf("%q", rule.Method),
					", ",
					fmt.Sprintf("%q", route),
					", ",
					operationVariable,
					", ",
					decoder,
					", ",
					unexported(service.GoName+method.GoName+"HTTPHandler"),
					"(service, ",
					fmt.Sprintf("%q", rule.ResponseBody),
					"), sseEncoder, ",
					output.QualifiedGoIdent(httpPackage.Ident("WithStreaming")),
					"()); err != nil { return err }",
				)
			} else {
				output.P(
					"if err := router.", registration, "(",
					fmt.Sprintf("%q", rule.Method),
					", ",
					fmt.Sprintf("%q", route),
					", ",
					operationVariable,
					", ",
					decoder,
					", ",
					unexported(service.GoName+method.GoName+"HTTPHandler"),
					"(service), ",
					protoResponseEncoderExpression(
						output,
						httpPackage,
						method.Output,
						rule.ResponseBody,
					),
					"); err != nil { return err }",
				)
			}
		}
	}
	output.P("return nil")
	output.P("}")
	output.P()
	for _, mapping := range mapped {
		method := mapping.method
		handlerName := unexported(service.GoName + method.GoName + "HTTPHandler")
		if method.Desc.IsStreamingServer() {
			output.P(
				"func ",
				handlerName,
				"(service ",
				serverName,
				", responseBody string) ",
				output.QualifiedGoIdent(middlewarePackage.Ident("Handler")),
				" {",
			)
		} else {
			output.P(
				"func ",
				handlerName,
				"(service ",
				serverName,
				") ",
				output.QualifiedGoIdent(middlewarePackage.Ident("Handler")),
				" {",
			)
		}
		output.P(
			"return func(ctx ",
			output.QualifiedGoIdent(contextPackage.Ident("Context")),
			", request any) (any, error) {",
		)
		output.P("input, ok := request.(*", method.Input.GoIdent, ")")
		output.P("if !ok {")
		output.P(
			"return nil, ",
			output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
			"(",
			fmt.Sprintf("%q", "keelith generated HTTP: unexpected request type %T"),
			", request)",
		)
		output.P("}")
		if method.Desc.IsStreamingServer() {
			streamType := unexported(
				service.GoName + method.GoName + "HTTPServer",
			)
			output.P(
				"events := make(chan ",
				output.QualifiedGoIdent(httpPackage.Ident("SSEEvent")),
				")",
			)
			output.P("failures := make(chan error)")
			output.P(
				"stream := &",
				streamType,
				"{ctx: ctx, events: events, responseBody: responseBody}",
			)
			output.P("go func() {")
			output.P(
				"if err := service.",
				method.GoName,
				"(input, stream); err != nil {",
			)
			output.P(
				"select { case failures <- err: case <-ctx.Done(): }",
			)
			output.P("close(failures)")
			output.P("close(events)")
			output.P("return")
			output.P("}")
			output.P("close(events)")
			output.P("close(failures)")
			output.P("}()")
			output.P(
				"return ",
				output.QualifiedGoIdent(
					httpPackage.Ident("NewServerSentEvents"),
				),
				"(events, failures)",
			)
		} else {
			output.P("return service.", method.GoName, "(ctx, input)")
		}
		output.P("}")
		output.P("}")
		output.P()
		if method.Desc.IsStreamingServer() {
			generateHTTPServerStream(output, service, method)
		}
	}
	return nil
}

func hasServerStreamingHTTPMapping(mappings []mappedHTTPMethod) bool {
	for _, mapping := range mappings {
		if mapping.method.Desc.IsStreamingServer() {
			return true
		}
	}
	return false
}

func httpOperationKind(method *protogen.Method) string {
	if method.Desc.IsStreamingServer() {
		return "KindServerStream"
	}
	return "KindUnary"
}

func generateHTTPServerStream(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	method *protogen.Method,
) {
	name := unexported(service.GoName + method.GoName + "HTTPServer")
	output.P("type ", name, " struct {")
	output.P("ctx ", output.QualifiedGoIdent(contextPackage.Ident("Context")))
	output.P(
		"events chan<- ",
		output.QualifiedGoIdent(httpPackage.Ident("SSEEvent")),
	)
	output.P("responseBody string")
	output.P("}")
	output.P(
		"func (stream *",
		name,
		") Context() ",
		output.QualifiedGoIdent(contextPackage.Ident("Context")),
		" { return stream.ctx }",
	)
	output.P(
		"func (stream *",
		name,
		") Send(message *",
		method.Output.GoIdent,
		") error {",
	)
	output.P(
		"event, err := ",
		output.QualifiedGoIdent(httpPackage.Ident("NewSSEProtoResponseBodyEvent")),
		"(",
		fmt.Sprintf("%q", ""),
		", ",
		fmt.Sprintf("%q", string(method.Output.Desc.FullName())),
		", message, stream.responseBody, 0)",
	)
	output.P("if err != nil { return err }")
	output.P(
		"select { case stream.events <- event: return nil; case <-stream.ctx.Done(): return ",
		output.QualifiedGoIdent(contextPackage.Ident("Cause")),
		"(stream.ctx) }",
	)
	output.P("}")
	output.P()
}

func protoResponseEncoderExpression(
	output *protogen.GeneratedFile,
	packagePath protogen.GoImportPath,
	message *protogen.Message,
	responseBody string,
) string {
	if httpResponseUsesHTTPBody(message, responseBody) {
		return output.QualifiedGoIdent(
			packagePath.Ident("EncodeProtoHTTPBody"),
		) + "(" + fmt.Sprintf("%q", responseBody) + ")"
	}
	if responseBody == "" {
		return output.QualifiedGoIdent(packagePath.Ident("EncodeProto"))
	}
	return output.QualifiedGoIdent(
		packagePath.Ident("EncodeProtoResponseBody"),
	) + "(" + fmt.Sprintf("%q", responseBody) + ")"
}

func generateErrorHelper(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	method *protogen.Method,
	reason string,
) {
	name := service.GoName + method.GoName + "ErrorReason"
	output.P("const ", name, " = ", fmt.Sprintf("%q", reason))
	output.P(
		"func New",
		service.GoName,
		method.GoName,
		"Error(code int32, message string) error {",
	)
	output.P(
		"return ",
		output.QualifiedGoIdent(errorsPackage.Ident("New")),
		"(code, ",
		name,
		", message)",
	)
	output.P("}")
	output.P()
}

func serverStreamName(
	service *protogen.Service,
	method *protogen.Method,
) string {
	return service.GoName + "_" + method.GoName + "KeelithServer"
}

func clientStreamName(
	service *protogen.Service,
	method *protogen.Method,
) string {
	return service.GoName + "_" + method.GoName + "KeelithClient"
}

func unexported(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
