package generator

import (
	"fmt"

	"github.com/keelab/keelith/internal/httptemplate"
	"google.golang.org/protobuf/compiler/protogen"
)

const hertzGeneratorProtocolVersion = "v1alpha13"

type hertzServiceMapping struct {
	service  *protogen.Service
	mappings []mappedHTTPMethod
}

func generateHertzFile(
	plugin *protogen.Plugin,
	file *protogen.File,
) error {
	services := make([]hertzServiceMapping, 0, len(file.Services))
	for _, service := range file.Services {
		mappings, err := serviceHTTPMappings(service)
		if err != nil {
			return fmt.Errorf(
				"generator: experimental Hertz service %s: %w",
				service.Desc.FullName(),
				err,
			)
		}
		if len(mappings) == 0 {
			continue
		}
		for _, mapping := range mappings {
			for _, rule := range mapping.rules {
				if _, err := hertzRoutePath(rule.Path); err != nil {
					return fmt.Errorf(
						"generator: experimental Hertz method %s: %w",
						mapping.method.Desc.FullName(),
						err,
					)
				}
			}
		}
		services = append(services, hertzServiceMapping{
			service:  service,
			mappings: mappings,
		})
	}
	if len(services) == 0 {
		return nil
	}

	output := plugin.NewGeneratedFile(
		file.GeneratedFilenamePrefix+".keelith.hertz.gen.go",
		file.GoImportPath,
	)
	output.P("// Code generated by protoc-gen-go-keelith. DO NOT EDIT.")
	output.P("// source: ", file.Desc.Path())
	output.P("// profile: experimental_hertz")
	output.P()
	output.P("package ", file.GoPackageName)
	output.P()
	for _, service := range services {
		output.P(
			"const ",
			service.service.GoName,
			"KeelithHertzGeneratorProtocol = ",
			fmt.Sprintf("%q", hertzGeneratorProtocolVersion),
		)
		output.P()
		generateHertzRegistration(
			output,
			service.service,
			service.mappings,
		)
		generateHertzClient(
			output,
			service.service,
			service.mappings,
		)
	}
	return nil
}

func generateHertzRegistration(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	mappings []mappedHTTPMethod,
) {
	output.P(
		"// Register",
		service.GoName,
		"Hertz binds annotated unary and server-streaming methods to an experimental Hertz server.",
	)
	output.P(
		"func Register",
		service.GoName,
		"Hertz(server *",
		output.QualifiedGoIdent(hertzPackage.Ident("Server")),
		", service ",
		service.GoName,
		"KeelithServer) error {",
	)
	output.P("if server == nil || service == nil {")
	output.P(
		"return ",
		output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
		"(",
		fmt.Sprintf(
			"%q",
			"keelith generated Hertz: server or service is nil",
		),
		")",
	)
	output.P("}")
	if hasServerStreamingHTTPMapping(mappings) {
		output.P(
			"sseEncoder, err := ",
			output.QualifiedGoIdent(hertzPackage.Ident("NewSSEEncoder")),
			"(",
			output.QualifiedGoIdent(ssePackage.Ident("Config")),
			"{})",
		)
		output.P("if err != nil { return err }")
	}
	for _, mapping := range mappings {
		method := mapping.method
		operationVariable := unexported(
			service.GoName + method.GoName + "HertzOperation",
		)
		output.P(
			operationVariable,
			", err := ",
			output.QualifiedGoIdent(operationPackage.Ident("New")),
			"(",
			fmt.Sprintf("%q", "http"),
			", ",
			fmt.Sprintf("%q", string(service.Desc.FullName())),
			", ",
			fmt.Sprintf("%q", string(method.Desc.Name())),
			", ",
			output.QualifiedGoIdent(
				operationPackage.Ident(httpOperationKind(method)),
			),
			")",
		)
		output.P("if err != nil { return err }")
		for _, rule := range mapping.rules {
			decoder, pathBindings, _ := protoDecoderExpression(
				output,
				hertzPackage,
				method.Input,
				rule,
			)
			route := hertzHTTPRoutePath(rule.Path, pathBindings)
			if method.Desc.IsStreamingServer() {
				output.P(
					"if err := server.Handle(",
					fmt.Sprintf("%q", rule.Method),
					", ",
					fmt.Sprintf("%q", route),
					", ",
					operationVariable,
					", ",
					decoder,
					", ",
					unexported(service.GoName+method.GoName+"HTTPHandler"),
					"(service, ",
					fmt.Sprintf("%q", rule.ResponseBody),
					"), sseEncoder, ",
					output.QualifiedGoIdent(hertzPackage.Ident("WithStreaming")),
					"()); err != nil { return err }",
				)
			} else {
				output.P(
					"if err := server.Handle(",
					fmt.Sprintf("%q", rule.Method),
					", ",
					fmt.Sprintf("%q", route),
					", ",
					operationVariable,
					", ",
					decoder,
					", ",
					unexported(service.GoName+method.GoName+"HTTPHandler"),
					"(service), ",
					protoResponseEncoderExpression(
						output,
						hertzPackage,
						method.Output,
						rule.ResponseBody,
					),
					"); err != nil { return err }",
				)
			}
		}
	}
	output.P("return nil")
	output.P("}")
	output.P()
}

func generateHertzClient(
	output *protogen.GeneratedFile,
	service *protogen.Service,
	mappings []mappedHTTPMethod,
) {
	interfaceName := service.GoName + "KeelithHertzClient"
	implementation := unexported(service.GoName) + "HertzClient"
	output.P(
		"// ",
		interfaceName,
		" is the experimental annotated Hertz client contract.",
	)
	output.P("type ", interfaceName, " interface {")
	for _, mapping := range mappings {
		if mapping.method.Desc.IsStreamingServer() {
			output.P(
				mapping.method.GoName,
				"(ctx ",
				output.QualifiedGoIdent(contextPackage.Ident("Context")),
				", input *",
				mapping.method.Input.GoIdent,
				", options ...",
				output.QualifiedGoIdent(
					hertzPackage.Ident("SSEClientOption"),
				),
				") (*",
				output.QualifiedGoIdent(
					hertzPackage.Ident("SSEClientStream"),
				),
				"[*",
				mapping.method.Output.GoIdent,
				"], error)",
			)
		} else {
			output.P(
				mapping.method.GoName,
				"(ctx ",
				output.QualifiedGoIdent(contextPackage.Ident("Context")),
				", input *",
				mapping.method.Input.GoIdent,
				") (*",
				mapping.method.Output.GoIdent,
				", error)",
			)
		}
	}
	output.P("}")
	output.P()
	output.P("type ", implementation, " struct {")
	output.P("client *", output.QualifiedGoIdent(hertzPackage.Ident("Client")))
	output.P("baseURL string")
	for _, mapping := range mappings {
		output.P(
			unexported(mapping.method.GoName),
			"Operation ",
			output.QualifiedGoIdent(operationPackage.Ident("Operation")),
		)
	}
	output.P("}")
	output.P()
	output.P(
		"func New",
		service.GoName,
		"HertzClient(client *",
		output.QualifiedGoIdent(hertzPackage.Ident("Client")),
		", baseURL string) (",
		interfaceName,
		", error) {",
	)
	output.P("if client == nil {")
	output.P(
		"return nil, ",
		output.QualifiedGoIdent(fmtPackage.Ident("Errorf")),
		"(",
		fmt.Sprintf("%q", "keelith generated Hertz client: client is nil"),
		")",
	)
	output.P("}")
	output.P(
		"normalizedBaseURL, err := ",
		output.QualifiedGoIdent(
			hertzPackage.Ident("NormalizeClientBaseURL"),
		),
		"(baseURL)",
	)
	output.P("if err != nil { return nil, err }")
	for _, mapping := range mappings {
		method := mapping.method
		variable := unexported(method.GoName) + "Operation"
		output.P(
			variable,
			", err := ",
			output.QualifiedGoIdent(operationPackage.Ident("New")),
			"(",
			fmt.Sprintf("%q", "http"),
			", ",
			fmt.Sprintf("%q", string(service.Desc.FullName())),
			", ",
			fmt.Sprintf("%q", string(method.Desc.Name())),
			", ",
			output.QualifiedGoIdent(
				operationPackage.Ident(httpOperationKind(method)),
			),
			")",
		)
		output.P("if err != nil { return nil, err }")
	}
	output.P("return &", implementation, "{")
	output.P("client: client,")
	output.P("baseURL: normalizedBaseURL,")
	for _, mapping := range mappings {
		field := unexported(mapping.method.GoName) + "Operation"
		output.P(field, ": ", field, ",")
	}
	output.P("}, nil")
	output.P("}")
	output.P()
	for _, mapping := range mappings {
		generateHertzClientMethod(
			output,
			mapping,
			implementation,
		)
	}
}

func generateHertzClientMethod(
	output *protogen.GeneratedFile,
	mapping mappedHTTPMethod,
	implementation string,
) {
	method := mapping.method
	if method.Desc.IsStreamingServer() {
		output.P(
			"func (client *",
			implementation,
			") ",
			method.GoName,
			"(ctx ",
			output.QualifiedGoIdent(contextPackage.Ident("Context")),
			", input *",
			method.Input.GoIdent,
			", options ...",
			output.QualifiedGoIdent(hertzPackage.Ident("SSEClientOption")),
			") (*",
			output.QualifiedGoIdent(hertzPackage.Ident("SSEClientStream")),
			"[*",
			method.Output.GoIdent,
			"], error) {",
		)
		output.P(
			"request, err := ",
			output.QualifiedGoIdent(hertzPackage.Ident("NewProtoRequest")),
			"(ctx, client.baseURL, ",
			fmt.Sprintf("%q", mapping.rule.Method),
			", ",
			fmt.Sprintf("%q", mapping.rule.Path),
			", input, ",
			fmt.Sprintf("%q", mapping.rule.Body),
			")",
		)
		output.P("if err != nil { return nil, err }")
		openFunction := "OpenProtoSSE"
		responseArgument := ""
		if mapping.rule.ResponseBody != "" {
			openFunction = "OpenProtoSSEResponseBody"
			responseArgument = ", " + fmt.Sprintf("%q", mapping.rule.ResponseBody)
		}
		output.P(
			"return ",
			output.QualifiedGoIdent(hertzPackage.Ident(openFunction)),
			"(ctx, client.client, client.",
			unexported(method.GoName),
			"Operation, request, func() *",
			method.Output.GoIdent,
			" { return new(",
			method.Output.GoIdent,
			") }",
			responseArgument,
			", options...)",
		)
		output.P("}")
		output.P()
		return
	}
	output.P(
		"func (client *",
		implementation,
		") ",
		method.GoName,
		"(ctx ",
		output.QualifiedGoIdent(contextPackage.Ident("Context")),
		", input *",
		method.Input.GoIdent,
		") (*",
		method.Output.GoIdent,
		", error) {",
	)
	output.P(
		"request, err := ",
		output.QualifiedGoIdent(hertzPackage.Ident("NewProtoRequest")),
		"(ctx, client.baseURL, ",
		fmt.Sprintf("%q", mapping.rule.Method),
		", ",
		fmt.Sprintf("%q", mapping.rule.Path),
		", input, ",
		fmt.Sprintf("%q", mapping.rule.Body),
		")",
	)
	output.P("if err != nil { return nil, err }")
	invokeFunction := "InvokeProto"
	responseArgument := ""
	if httpResponseUsesHTTPBody(method.Output, mapping.rule.ResponseBody) {
		invokeFunction = "InvokeProtoHTTPBody"
		responseArgument = ", " + fmt.Sprintf("%q", mapping.rule.ResponseBody)
	} else if mapping.rule.ResponseBody != "" {
		invokeFunction = "InvokeProtoResponseBody"
		responseArgument = ", " + fmt.Sprintf("%q", mapping.rule.ResponseBody)
	}
	output.P(
		"return ",
		output.QualifiedGoIdent(hertzPackage.Ident(invokeFunction)),
		"(ctx, client.client, client.",
		unexported(method.GoName),
		"Operation, request, func() *",
		method.Output.GoIdent,
		" { return new(",
		method.Output.GoIdent,
		") }",
		responseArgument,
		")",
	)
	output.P("}")
	output.P()
}

func hertzRoutePath(path string) (string, error) {
	template, err := httptemplate.Parse(path)
	if err != nil {
		return "", err
	}
	if template.Verb != "" && template.EndsWithVariable() {
		return "", fmt.Errorf(
			"hertz cannot exactly route variable custom verb path %q",
			path,
		)
	}
	bindings, err := httpPathBindingSpecs(path)
	if err != nil {
		return "", err
	}
	return hertzHTTPRoutePath(path, bindings), nil
}
