// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: projection/v1/protocol.proto

package projectionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectionService_Subscribe_FullMethodName = "/keelith.projection.v1.ProjectionService/Subscribe"
)

// ProjectionServiceClient is the client API for ProjectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProjectionService is the additive shard-aware projection protocol. A
// subscription is always scoped to exactly one shard; callers must opt in to
// fan-out by opening more than one stream.
type ProjectionServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
}

type projectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectionServiceClient(cc grpc.ClientConnInterface) ProjectionServiceClient {
	return &projectionServiceClient{cc}
}

func (c *projectionServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectionService_ServiceDesc.Streams[0], ProjectionService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectionService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

// ProjectionServiceServer is the server API for ProjectionService service.
// All implementations must embed UnimplementedProjectionServiceServer
// for forward compatibility.
//
// ProjectionService is the additive shard-aware projection protocol. A
// subscription is always scoped to exactly one shard; callers must opt in to
// fan-out by opening more than one stream.
type ProjectionServiceServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	mustEmbedUnimplementedProjectionServiceServer()
}

// UnimplementedProjectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectionServiceServer struct{}

func (UnimplementedProjectionServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedProjectionServiceServer) mustEmbedUnimplementedProjectionServiceServer() {}
func (UnimplementedProjectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeProjectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectionServiceServer will
// result in compilation errors.
type UnsafeProjectionServiceServer interface {
	mustEmbedUnimplementedProjectionServiceServer()
}

func RegisterProjectionServiceServer(s grpc.ServiceRegistrar, srv ProjectionServiceServer) {
	// If the following call panics, it indicates UnimplementedProjectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectionService_ServiceDesc, srv)
}

func _ProjectionService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProjectionServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectionService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

// ProjectionService_ServiceDesc is the grpc.ServiceDesc for ProjectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keelith.projection.v1.ProjectionService",
	HandlerType: (*ProjectionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ProjectionService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "projection/v1/protocol.proto",
}
