// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: projection/v1/protocol.proto

package projectionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mutation_Kind int32

const (
	Mutation_KIND_UNSPECIFIED Mutation_Kind = 0
	Mutation_KIND_UPSERT      Mutation_Kind = 1
	Mutation_KIND_DELETE      Mutation_Kind = 2
)

// Enum value maps for Mutation_Kind.
var (
	Mutation_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_UPSERT",
		2: "KIND_DELETE",
	}
	Mutation_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_UPSERT":      1,
		"KIND_DELETE":      2,
	}
)

func (x Mutation_Kind) Enum() *Mutation_Kind {
	p := new(Mutation_Kind)
	*p = x
	return p
}

func (x Mutation_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mutation_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_projection_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (Mutation_Kind) Type() protoreflect.EnumType {
	return &file_projection_v1_protocol_proto_enumTypes[0]
}

func (x Mutation_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mutation_Kind.Descriptor instead.
func (Mutation_Kind) EnumDescriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{3, 0}
}

type Schema struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fingerprint            string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	KeyFingerprint         string                 `protobuf:"bytes,3,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	CompatibleFingerprints []string               `protobuf:"bytes,4,rep,name=compatible_fingerprints,json=compatibleFingerprints,proto3" json:"compatible_fingerprints,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_projection_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schema) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Schema) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *Schema) GetCompatibleFingerprints() []string {
	if x != nil {
		return x.CompatibleFingerprints
	}
	return nil
}

type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_projection_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Shard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shard) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	After         string                 `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	ForceSnapshot bool                   `protobuf:"varint,3,opt,name=force_snapshot,json=forceSnapshot,proto3" json:"force_snapshot,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,4,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_projection_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *SubscribeRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *SubscribeRequest) GetForceSnapshot() bool {
	if x != nil {
		return x.ForceSnapshot
	}
	return false
}

func (x *SubscribeRequest) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Mutation_Kind          `protobuf:"varint,1,opt,name=kind,proto3,enum=keelith.projection.v1.Mutation_Kind" json:"kind,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_projection_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Mutation) GetKind() Mutation_Kind {
	if x != nil {
		return x.Kind
	}
	return Mutation_KIND_UNSPECIFIED
}

func (x *Mutation) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Mutation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SnapshotBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotBegin) Reset() {
	*x = SnapshotBegin{}
	mi := &file_projection_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotBegin) ProtoMessage() {}

func (x *SnapshotBegin) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotBegin.ProtoReflect.Descriptor instead.
func (*SnapshotBegin) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotBegin) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *SnapshotBegin) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type SnapshotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutations     []*Mutation            `protobuf:"bytes,1,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_projection_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotChunk) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type SnapshotEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	SourceTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=source_time,json=sourceTime,proto3" json:"source_time,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnd) Reset() {
	*x = SnapshotEnd{}
	mi := &file_projection_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnd) ProtoMessage() {}

func (x *SnapshotEnd) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnd.ProtoReflect.Descriptor instead.
func (*SnapshotEnd) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotEnd) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SnapshotEnd) GetSourceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceTime
	}
	return nil
}

func (x *SnapshotEnd) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Previous      string                 `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	SourceTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=source_time,json=sourceTime,proto3" json:"source_time,omitempty"`
	Mutations     []*Mutation            `protobuf:"bytes,5,rep,name=mutations,proto3" json:"mutations,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,6,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_projection_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Delta) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Delta) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *Delta) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Delta) GetSourceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceTime
	}
	return nil
}

func (x *Delta) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *Delta) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	SourceTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=source_time,json=sourceTime,proto3" json:"source_time,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_projection_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Heartbeat) GetSourceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceTime
	}
	return nil
}

func (x *Heartbeat) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type Gap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requested     string                 `protobuf:"bytes,1,opt,name=requested,proto3" json:"requested,omitempty"`
	Floor         string                 `protobuf:"bytes,2,opt,name=floor,proto3" json:"floor,omitempty"`
	Shard         *Shard                 `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gap) Reset() {
	*x = Gap{}
	mi := &file_projection_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gap) ProtoMessage() {}

func (x *Gap) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gap.ProtoReflect.Descriptor instead.
func (*Gap) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *Gap) GetRequested() string {
	if x != nil {
		return x.Requested
	}
	return ""
}

func (x *Gap) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *Gap) GetShard() *Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SubscribeResponse_SnapshotBegin
	//	*SubscribeResponse_SnapshotChunk
	//	*SubscribeResponse_SnapshotEnd
	//	*SubscribeResponse_Delta
	//	*SubscribeResponse_Heartbeat
	//	*SubscribeResponse_Gap
	Body          isSubscribeResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_projection_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projection_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_projection_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeResponse) GetBody() isSubscribeResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SubscribeResponse) GetSnapshotBegin() *SnapshotBegin {
	if x != nil {
		if x, ok := x.Body.(*SubscribeResponse_SnapshotBegin); ok {
			return x.SnapshotBegin
		}
	}
	return nil
}

func (x *SubscribeResponse) GetSnapshotChunk() *SnapshotChunk {
	if x != nil {
		if x, ok := x.Body.(*SubscribeResponse_SnapshotChunk); ok {
			return x.SnapshotChunk
		}
	}
	return nil
}

func (x *SubscribeResponse) GetSnapshotEnd() *SnapshotEnd {
	if x != nil {
		if x, ok := x.Body.(*SubscribeResponse_SnapshotEnd); ok {
			return x.SnapshotEnd
		}
	}
	return nil
}

func (x *SubscribeResponse) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Body.(*SubscribeResponse_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *SubscribeResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*SubscribeResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SubscribeResponse) GetGap() *Gap {
	if x != nil {
		if x, ok := x.Body.(*SubscribeResponse_Gap); ok {
			return x.Gap
		}
	}
	return nil
}

type isSubscribeResponse_Body interface {
	isSubscribeResponse_Body()
}

type SubscribeResponse_SnapshotBegin struct {
	SnapshotBegin *SnapshotBegin `protobuf:"bytes,1,opt,name=snapshot_begin,json=snapshotBegin,proto3,oneof"`
}

type SubscribeResponse_SnapshotChunk struct {
	SnapshotChunk *SnapshotChunk `protobuf:"bytes,2,opt,name=snapshot_chunk,json=snapshotChunk,proto3,oneof"`
}

type SubscribeResponse_SnapshotEnd struct {
	SnapshotEnd *SnapshotEnd `protobuf:"bytes,3,opt,name=snapshot_end,json=snapshotEnd,proto3,oneof"`
}

type SubscribeResponse_Delta struct {
	Delta *Delta `protobuf:"bytes,4,opt,name=delta,proto3,oneof"`
}

type SubscribeResponse_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

type SubscribeResponse_Gap struct {
	Gap *Gap `protobuf:"bytes,6,opt,name=gap,proto3,oneof"`
}

func (*SubscribeResponse_SnapshotBegin) isSubscribeResponse_Body() {}

func (*SubscribeResponse_SnapshotChunk) isSubscribeResponse_Body() {}

func (*SubscribeResponse_SnapshotEnd) isSubscribeResponse_Body() {}

func (*SubscribeResponse_Delta) isSubscribeResponse_Body() {}

func (*SubscribeResponse_Heartbeat) isSubscribeResponse_Body() {}

func (*SubscribeResponse_Gap) isSubscribeResponse_Body() {}

var File_projection_v1_protocol_proto protoreflect.FileDescriptor

const file_projection_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1cprojection/v1/protocol.proto\x12\x15keelith.projection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x06Schema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12'\n" +
	"\x0fkey_fingerprint\x18\x03 \x01(\tR\x0ekeyFingerprint\x127\n" +
	"\x17compatible_fingerprints\x18\x04 \x03(\tR\x16compatibleFingerprints\"7\n" +
	"\x05Shard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\"\xba\x01\n" +
	"\x10SubscribeRequest\x125\n" +
	"\x06schema\x18\x01 \x01(\v2\x1d.keelith.projection.v1.SchemaR\x06schema\x12\x14\n" +
	"\x05after\x18\x02 \x01(\tR\x05after\x12%\n" +
	"\x0eforce_snapshot\x18\x03 \x01(\bR\rforceSnapshot\x122\n" +
	"\x05shard\x18\x04 \x01(\v2\x1c.keelith.projection.v1.ShardR\x05shard\"\xac\x01\n" +
	"\bMutation\x128\n" +
	"\x04kind\x18\x01 \x01(\x0e2$.keelith.projection.v1.Mutation.KindR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\">\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vKIND_UPSERT\x10\x01\x12\x0f\n" +
	"\vKIND_DELETE\x10\x02\"z\n" +
	"\rSnapshotBegin\x125\n" +
	"\x06schema\x18\x01 \x01(\v2\x1d.keelith.projection.v1.SchemaR\x06schema\x122\n" +
	"\x05shard\x18\x02 \x01(\v2\x1c.keelith.projection.v1.ShardR\x05shard\"N\n" +
	"\rSnapshotChunk\x12=\n" +
	"\tmutations\x18\x01 \x03(\v2\x1f.keelith.projection.v1.MutationR\tmutations\"\x96\x01\n" +
	"\vSnapshotEnd\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12;\n" +
	"\vsource_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"sourceTime\x122\n" +
	"\x05shard\x18\x03 \x01(\v2\x1c.keelith.projection.v1.ShardR\x05shard\"\xa2\x02\n" +
	"\x05Delta\x125\n" +
	"\x06schema\x18\x01 \x01(\v2\x1d.keelith.projection.v1.SchemaR\x06schema\x12\x1a\n" +
	"\bprevious\x18\x02 \x01(\tR\bprevious\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12;\n" +
	"\vsource_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"sourceTime\x12=\n" +
	"\tmutations\x18\x05 \x03(\v2\x1f.keelith.projection.v1.MutationR\tmutations\x122\n" +
	"\x05shard\x18\x06 \x01(\v2\x1c.keelith.projection.v1.ShardR\x05shard\"\x94\x01\n" +
	"\tHeartbeat\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12;\n" +
	"\vsource_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"sourceTime\x122\n" +
	"\x05shard\x18\x03 \x01(\v2\x1c.keelith.projection.v1.ShardR\x05shard\"m\n" +
	"\x03Gap\x12\x1c\n" +
	"\trequested\x18\x01 \x01(\tR\trequested\x12\x14\n" +
	"\x05floor\x18\x02 \x01(\tR\x05floor\x122\n" +
	"\x05shard\x18\x03 \x01(\v2\x1c.keelith.projection.v1.ShardR\x05shard\"\xaa\x03\n" +
	"\x11SubscribeResponse\x12M\n" +
	"\x0esnapshot_begin\x18\x01 \x01(\v2$.keelith.projection.v1.SnapshotBeginH\x00R\rsnapshotBegin\x12M\n" +
	"\x0esnapshot_chunk\x18\x02 \x01(\v2$.keelith.projection.v1.SnapshotChunkH\x00R\rsnapshotChunk\x12G\n" +
	"\fsnapshot_end\x18\x03 \x01(\v2\".keelith.projection.v1.SnapshotEndH\x00R\vsnapshotEnd\x124\n" +
	"\x05delta\x18\x04 \x01(\v2\x1c.keelith.projection.v1.DeltaH\x00R\x05delta\x12@\n" +
	"\theartbeat\x18\x05 \x01(\v2 .keelith.projection.v1.HeartbeatH\x00R\theartbeat\x12.\n" +
	"\x03gap\x18\x06 \x01(\v2\x1a.keelith.projection.v1.GapH\x00R\x03gapB\x06\n" +
	"\x04body2u\n" +
	"\x11ProjectionService\x12`\n" +
	"\tSubscribe\x12'.keelith.projection.v1.SubscribeRequest\x1a(.keelith.projection.v1.SubscribeResponse0\x01B:Z8github.com/keelab/keelith/api/projection/v1;projectionv1b\x06proto3"

var (
	file_projection_v1_protocol_proto_rawDescOnce sync.Once
	file_projection_v1_protocol_proto_rawDescData []byte
)

func file_projection_v1_protocol_proto_rawDescGZIP() []byte {
	file_projection_v1_protocol_proto_rawDescOnce.Do(func() {
		file_projection_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projection_v1_protocol_proto_rawDesc), len(file_projection_v1_protocol_proto_rawDesc)))
	})
	return file_projection_v1_protocol_proto_rawDescData
}

var file_projection_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_projection_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_projection_v1_protocol_proto_goTypes = []any{
	(Mutation_Kind)(0),            // 0: keelith.projection.v1.Mutation.Kind
	(*Schema)(nil),                // 1: keelith.projection.v1.Schema
	(*Shard)(nil),                 // 2: keelith.projection.v1.Shard
	(*SubscribeRequest)(nil),      // 3: keelith.projection.v1.SubscribeRequest
	(*Mutation)(nil),              // 4: keelith.projection.v1.Mutation
	(*SnapshotBegin)(nil),         // 5: keelith.projection.v1.SnapshotBegin
	(*SnapshotChunk)(nil),         // 6: keelith.projection.v1.SnapshotChunk
	(*SnapshotEnd)(nil),           // 7: keelith.projection.v1.SnapshotEnd
	(*Delta)(nil),                 // 8: keelith.projection.v1.Delta
	(*Heartbeat)(nil),             // 9: keelith.projection.v1.Heartbeat
	(*Gap)(nil),                   // 10: keelith.projection.v1.Gap
	(*SubscribeResponse)(nil),     // 11: keelith.projection.v1.SubscribeResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_projection_v1_protocol_proto_depIdxs = []int32{
	1,  // 0: keelith.projection.v1.SubscribeRequest.schema:type_name -> keelith.projection.v1.Schema
	2,  // 1: keelith.projection.v1.SubscribeRequest.shard:type_name -> keelith.projection.v1.Shard
	0,  // 2: keelith.projection.v1.Mutation.kind:type_name -> keelith.projection.v1.Mutation.Kind
	1,  // 3: keelith.projection.v1.SnapshotBegin.schema:type_name -> keelith.projection.v1.Schema
	2,  // 4: keelith.projection.v1.SnapshotBegin.shard:type_name -> keelith.projection.v1.Shard
	4,  // 5: keelith.projection.v1.SnapshotChunk.mutations:type_name -> keelith.projection.v1.Mutation
	12, // 6: keelith.projection.v1.SnapshotEnd.source_time:type_name -> google.protobuf.Timestamp
	2,  // 7: keelith.projection.v1.SnapshotEnd.shard:type_name -> keelith.projection.v1.Shard
	1,  // 8: keelith.projection.v1.Delta.schema:type_name -> keelith.projection.v1.Schema
	12, // 9: keelith.projection.v1.Delta.source_time:type_name -> google.protobuf.Timestamp
	4,  // 10: keelith.projection.v1.Delta.mutations:type_name -> keelith.projection.v1.Mutation
	2,  // 11: keelith.projection.v1.Delta.shard:type_name -> keelith.projection.v1.Shard
	12, // 12: keelith.projection.v1.Heartbeat.source_time:type_name -> google.protobuf.Timestamp
	2,  // 13: keelith.projection.v1.Heartbeat.shard:type_name -> keelith.projection.v1.Shard
	2,  // 14: keelith.projection.v1.Gap.shard:type_name -> keelith.projection.v1.Shard
	5,  // 15: keelith.projection.v1.SubscribeResponse.snapshot_begin:type_name -> keelith.projection.v1.SnapshotBegin
	6,  // 16: keelith.projection.v1.SubscribeResponse.snapshot_chunk:type_name -> keelith.projection.v1.SnapshotChunk
	7,  // 17: keelith.projection.v1.SubscribeResponse.snapshot_end:type_name -> keelith.projection.v1.SnapshotEnd
	8,  // 18: keelith.projection.v1.SubscribeResponse.delta:type_name -> keelith.projection.v1.Delta
	9,  // 19: keelith.projection.v1.SubscribeResponse.heartbeat:type_name -> keelith.projection.v1.Heartbeat
	10, // 20: keelith.projection.v1.SubscribeResponse.gap:type_name -> keelith.projection.v1.Gap
	3,  // 21: keelith.projection.v1.ProjectionService.Subscribe:input_type -> keelith.projection.v1.SubscribeRequest
	11, // 22: keelith.projection.v1.ProjectionService.Subscribe:output_type -> keelith.projection.v1.SubscribeResponse
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_projection_v1_protocol_proto_init() }
func file_projection_v1_protocol_proto_init() {
	if File_projection_v1_protocol_proto != nil {
		return
	}
	file_projection_v1_protocol_proto_msgTypes[10].OneofWrappers = []any{
		(*SubscribeResponse_SnapshotBegin)(nil),
		(*SubscribeResponse_SnapshotChunk)(nil),
		(*SubscribeResponse_SnapshotEnd)(nil),
		(*SubscribeResponse_Delta)(nil),
		(*SubscribeResponse_Heartbeat)(nil),
		(*SubscribeResponse_Gap)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projection_v1_protocol_proto_rawDesc), len(file_projection_v1_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projection_v1_protocol_proto_goTypes,
		DependencyIndexes: file_projection_v1_protocol_proto_depIdxs,
		EnumInfos:         file_projection_v1_protocol_proto_enumTypes,
		MessageInfos:      file_projection_v1_protocol_proto_msgTypes,
	}.Build()
	File_projection_v1_protocol_proto = out.File
	file_projection_v1_protocol_proto_goTypes = nil
	file_projection_v1_protocol_proto_depIdxs = nil
}
