// Code generated by protoc-gen-go-keelith. DO NOT EDIT.
// source: projection/v1/protocol.proto

package projectionv1

import (
	context "context"
	fmt "fmt"
	errors "github.com/keelab/keelith/errors"
	idempotency "github.com/keelab/keelith/governance/idempotency"
	service "github.com/keelab/keelith/service"
	http "github.com/keelab/keelith/transport/http"
	grpc "google.golang.org/grpc"
)

const ProjectionServiceKeelithGeneratorProtocol = "v1"

// ProjectionServiceKeelithServer is the transport-neutral implementation contract.
type ProjectionServiceKeelithServer interface {
	Subscribe(*SubscribeRequest, ProjectionService_SubscribeKeelithServer) error
}

type ProjectionService_SubscribeKeelithServer interface {
	Context() context.Context
	Send(*SubscribeResponse) error
}
type projectionServiceSubscribeServer struct {
	grpc.ServerStream
}

func (stream *projectionServiceSubscribeServer) Send(message *SubscribeResponse) error {
	return stream.SendMsg(message)
}

// UnimplementedProjectionServiceKeelithServer provides forward-compatible defaults for application implementations.
type UnimplementedProjectionServiceKeelithServer struct{}

func (*UnimplementedProjectionServiceKeelithServer) Subscribe(*SubscribeRequest, ProjectionService_SubscribeKeelithServer) error {
	return errors.New(501, "UNIMPLEMENTED", "keelith.projection.v1.ProjectionService.Subscribe is not implemented")
}

var _ ProjectionServiceKeelithServer = (*UnimplementedProjectionServiceKeelithServer)(nil)

// ProjectionServiceKeelithClient is the typed gRPC client contract.
type ProjectionServiceKeelithClient interface {
	Subscribe(context.Context, *SubscribeRequest, ...grpc.CallOption) (ProjectionService_SubscribeKeelithClient, error)
}

type projectionServiceGRPCClient struct {
	connection grpc.ClientConnInterface
}

func NewProjectionServiceGRPCClient(connection grpc.ClientConnInterface) ProjectionServiceKeelithClient {
	return &projectionServiceGRPCClient{connection: connection}
}

func (client *projectionServiceGRPCClient) Subscribe(ctx context.Context,
	input *SubscribeRequest,
	options ...grpc.CallOption) (ProjectionService_SubscribeKeelithClient, error) {
	stream, err := client.connection.NewStream(ctx, &ProjectionServiceKeelithGRPCServiceDesc.Streams[0], "/keelith.projection.v1.ProjectionService/Subscribe", options...)
	if err != nil {
		return nil, err
	}
	result := &projectionServiceSubscribeClient{ClientStream: stream}
	if err := result.SendMsg(input); err != nil {
		return nil, err
	}
	if err := result.CloseSend(); err != nil {
		return nil, err
	}
	return result, nil
}

// ProjectionServiceGRPCDependency exposes the connection required by a lifecycle-managed dependency.
type ProjectionServiceGRPCDependency interface {
	Service() string
	ClientConn() grpc.ClientConnInterface
}

// NewProjectionServiceManagedGRPCClient binds the generated typed client to a lifecycle-managed dependency.
func NewProjectionServiceManagedGRPCClient(dependency ProjectionServiceGRPCDependency) (ProjectionServiceKeelithClient, error) {
	if dependency == nil {
		return nil, fmt.Errorf("keelith generated gRPC client: managed dependency is nil")
	}
	if dependency.Service() != "keelith.projection.v1.ProjectionService" {
		return nil, fmt.Errorf("keelith generated gRPC client: dependency service %q does not match %q", dependency.Service(), "keelith.projection.v1.ProjectionService")
	}
	return NewProjectionServiceGRPCClient(dependency.ClientConn()), nil
}

// RegisterProjectionServiceHTTP binds annotated unary and server-streaming methods to a Keelith router.
func RegisterProjectionServiceHTTP(router *http.Router, service ProjectionServiceKeelithServer) error {
	if router == nil || service == nil {
		return fmt.Errorf("keelith generated HTTP: router or service is nil")
	}
	return nil
}

type ProjectionService_SubscribeKeelithClient interface {
	grpc.ClientStream
	Recv() (*SubscribeResponse, error)
}
type projectionServiceSubscribeClient struct {
	grpc.ClientStream
}

func (stream *projectionServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	message := new(SubscribeResponse)
	if err := stream.RecvMsg(message); err != nil {
		return nil, err
	}
	return message, nil
}

// RegisterProjectionServiceGRPC registers the generated adapter with grpc-go.
func RegisterProjectionServiceGRPC(registrar grpc.ServiceRegistrar, service ProjectionServiceKeelithServer) {
	registrar.RegisterService(&ProjectionServiceKeelithGRPCServiceDesc, service)
}

func projectionServiceSubscribeGRPCStreamHandler(service any, stream grpc.ServerStream) error {
	input := new(SubscribeRequest)
	if err := stream.RecvMsg(input); err != nil {
		return err
	}
	return service.(ProjectionServiceKeelithServer).Subscribe(input, &projectionServiceSubscribeServer{ServerStream: stream})
}

var ProjectionServiceKeelithGRPCServiceDesc = grpc.ServiceDesc{
	ServiceName: "keelith.projection.v1.ProjectionService",
	HandlerType: (*ProjectionServiceKeelithServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       projectionServiceSubscribeGRPCStreamHandler,
			ServerStreams: true,
			ClientStreams: false,
		},
	},
	Metadata: "projection/v1/protocol.proto",
}

// BindProjectionService creates one immutable HTTP/gRPC binding for this generated service.
func BindProjectionService(implementation ProjectionServiceKeelithServer, options ...service.BindingOption) service.Binding {
	return service.NewBinding(service.BindingSpec{
		Name:           "keelith.projection.v1.ProjectionService",
		Implementation: implementation,
		RegisterGRPC: func(registrar grpc.ServiceRegistrar) error {
			RegisterProjectionServiceGRPC(registrar, implementation)
			return nil
		},
	}, options...)
}

// ProjectionServiceKeelithIdempotencyRegistrations returns generated exact unary rules for every declared transport.
func ProjectionServiceKeelithIdempotencyRegistrations() ([]idempotency.Registration, error) {
	return nil, nil
}
